### ISSUE TITLE
Issue with running android on Ubuntu 16

### ISSUE THREAD

**Issue by aurimas535** [pavjacko/renative#10]
Running `npm run android`on Linux Ubuntu 16.04 and got this error:

> react-native-vanilla@0.7.0 android /var/www/react-native-vanilla
> cd platforms/android && ./gradlew appStart
> Task :app:checkDebugClasspath FAILED
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find org.webkit:android-jsc:r224109.
  Searched in the following locations:
    - file:/home/aurimas/Android/Sdk/extras/m2repository/org/webkit/android-jsc/r224109/android-jsc-r224109.pom
    - file:/home/aurimas/Android/Sdk/extras/m2repository/org/webkit/android-jsc/r224109/android-jsc-r224109.jar
    - file:/home/aurimas/Android/Sdk/extras/google/m2repository/org/webkit/android-jsc/r224109/android-jsc-r224109.pom
    - file:/home/aurimas/Android/Sdk/extras/google/m2repository/org/webkit/android-jsc/r224109/android-jsc-r224109.jar
    - file:/home/aurimas/Android/Sdk/extras/android/m2repository/org/webkit/android-jsc/r224109/android-jsc-r224109.pom
    - file:/home/aurimas/Android/Sdk/extras/android/m2repository/org/webkit/android-jsc/r224109/android-jsc-r224109.jar
    - https://dl.google.com/dl/android/maven2/org/webkit/android-jsc/r224109/android-jsc-r224109.pom
    - https://dl.google.com/dl/android/maven2/org/webkit/android-jsc/r224109/android-jsc-r224109.jar
    - https://jcenter.bintray.com/org/webkit/android-jsc/r224109/android-jsc-r224109.pom
    - https://jcenter.bintray.com/org/webkit/android-jsc/r224109/android-jsc-r224109.jar
    - https://repo.maven.apache.org/maven2/org/webkit/android-jsc/r224109/android-jsc-r224109.pom
    - https://repo.maven.apache.org/maven2/org/webkit/android-jsc/r224109/android-jsc-r224109.jar
    - file:/var/www/react-native-vanilla/node_modules/react-native/android/org/webkit/android-jsc/r224109/android-jsc-r224109.pom
    - file:/var/www/react-native-vanilla/node_modules/react-native/android/org/webkit/android-jsc/r224109/android-jsc-r224109.jar
    - https://jitpack.io/org/webkit/android-jsc/r224109/android-jsc-r224109.pom
    - https://jitpack.io/org/webkit/android-jsc/r224109/android-jsc-r224109.jar
    - file:/var/www/react-native-vanilla/platforms/node_modules/jsc-android/dist/org/webkit/android-jsc/r224109/android-jsc-r224109.pom
    - file:/var/www/react-native-vanilla/platforms/node_modules/jsc-android/dist/org/webkit/android-jsc/r224109/android-jsc-r224109.jar
  Required by:
      project :app > com.facebook.react:react-native:0.56.0

**Comment by pavjacko** [comment]
@aurimas535 Linux is not officially supported just yet. but will keep eye on it!

**Comment by maximilize** [comment]
@aurimas535 With the current LTS 18.04 it is working. Do you still face this issues with 16.04?

**Comment by pavjacko** [comment]
@aurimas535 @maximilize worked for me as well. closing
