### ISSUE TITLE
Which player to use for WebTV 

### ISSUE THREAD

**Issue by MwareSolutons** [pavjacko/renative#110]
We have tried react-native-video which is perfect for android and ios but for webtv it needs react-native-dom

1. does someone have a clue where to find a good player for this
2. or does someone know how we can move to react-native-dom

thanks

**Comment by lukutism** [comment]
Have you tried https://video-react.js.org/components/player/ ? :) for tv you can bind keys to play/pause or foward video .

**Comment by MwareSolutons** [comment]
Good one maybe i can squeeze that one in...thanks!!

**Comment by lukutism** [comment]
Also you can use _<video/>_ tag and from ref's you can use play pause and etc methods.

**Comment by FPerellocano** [comment]
Hi, did you get the player to work?

**Comment by MwareSolutons** [comment]
Yes we used VideoJS and loaded it via the template.js just think as if it was a website then you should be able to figure it out.

**Comment by FPerellocano** [comment]
> Yes we used VideoJS and loaded it via the template.js just think as if it was a website then you should be able to figure it out.

Thank you, got it working with hls videos now.
