### ISSUE TITLE
Android Build Failed (GRADEL VERSION)

### ISSUE THREAD

**Issue by iamsabet** [pavjacko/renative#112]
Hi im using master version of renative now , 
i have a little problem with android build (web , desktop and ios are fine )

<img width="1249" alt="Screen Shot 2019-06-25 at 1 24 56 PM" src="https://user-images.githubusercontent.com/20267993/60084389-ab5fc600-974c-11e9-8003-1331d34c9154.png">
<img width="1225" alt="Screen Shot 2019-06-25 at 1 25 01 PM" src="https://user-images.githubusercontent.com/20267993/60084390-ab5fc600-974c-11e9-9ffa-c5e4c8f33f79.png">

i searched and i get this : https://github.com/kmagiera/react-native-gesture-handler/issues/350

and this guy noted : https://github.com/wix/react-native-navigation/issues/4757#issuecomment-468133753

but cant change gradle version to downgrade it when i run its overridden by cli
can you help me here ?

**Comment by lukutism** [comment]
Use command **rnv platform eject**, then will appear **platformTemplates** folder from there you able to change gradle version and etc.
