### ISSUE TITLE
File naming bug

### ISSUE THREAD

**Issue by AignerTom** [pavjacko/renative#115]
After installation of rnv i receive an error that the module ‘fileUtils.js’ couldn’t be found. This is because of the file has a typo. The file is lowercased and are imported within 'cleaner.js' with a uppercase ‘U’ in Utils. On non-case-sensetive systems this error won’t occur. My system has case-sensetive enabled, so the different file name will cause an error.

**Comment by mihaiblaga89** [comment]
has been fixed in #113
