### ISSUE TITLE
Error running Android wear

### ISSUE THREAD

**Issue by Vijay-mRoads** [pavjacko/renative#133]
I am getting below error when I try to run below command

`rnv run -p androidwear`

ReNative run - ERRROR! Cannot read property 'runScheme' of undefined

**Comment by Vijay-mRoads** [comment]
Also, If I run the app using Android Studio I am getting below error

`
Unable to start activity ComponentInfo{renative.helloworld.debug/renative.helloworld.debug.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
`

**Comment by pavjacko** [comment]
@Vijay-mRoads what is your `rnv --version` ? seems like you have old version of appConfig or rnv itself

check if this solves your issue:

`npm install rnv` ( `0.23.20` as of writing)
`rnv new` (follow the steps to create new app)
`rnv run -p androidwear`

**Comment by Vijay-mRoads** [comment]
`rnv version `= 0.23.23

Still getting  below error

`Cannot read property 'runScheme' of undefined`

**Comment by pavjacko** [comment]
@Vijay-mRoads ok I think I found it. should be fixed with `0.23.26` I hope!

**Comment by Vijay-mRoads** [comment]
I am still getting below error


`Unable to start activity ComponentInfo{renative.helloworld.debug/renative.helloworld.debug.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.`.

Is there a running sample project for android wear?

**Comment by mihaiblaga89** [comment]
Yes, you can create a new project with `rnv new` and when prompted for a template use the default one, `renative-template-hello-world`. Then go into that directory and run `rnv run -p androidwear`

**Comment by Vijay-mRoads** [comment]
I was able to get it running. But the app fails when the packager is running. Do I need to run the app again to see my javascript changes? Is there a way to connect the app to packager during development like we do for regular react native apps?
