### ISSUE TITLE
Rnv can't find android tv

### ISSUE THREAD

**Issue by aurimas535** [pavjacko/renative#134]
Have shield connected to computer `rnv run -p androidtv` fails because can't find any device connect. Works running via android studio.

**Comment by mihaiblaga89** [comment]
Can you give me the output of 'rnv run - p android tv --info' please?

**Comment by pavjacko** [comment]
@aurimas535 could you re-test this with `0.23.19`

**Comment by aurimas535** [comment]
@pavjacko works now. thanks
