### ISSUE TITLE
Cannot find assets configs and need to be relative

### ISSUE THREAD

**Issue by Ivanov89** [pavjacko/renative#136]
Could you config the assets path to be relative, because the project configs required to be relative and is there some config about that - we could not find it, please?

Thanks!

**Comment by pavjacko** [comment]
@Ivanov89 could you be more specific which file/section are you talking about? maybe an example of what you want to achieve will help

**Comment by Ivanov89** [comment]
My `index.html` is located under `http://domain.com/a/b `when asset is required it is looking it in `http://domain/assets/the_assets` and there is no way to make it relative to look it at `http://domain/a/b/assets.`
`a, b ` path is unknown for us...

**Comment by pavjacko** [comment]
@Ivanov89 this will be added as dynamic prop into `appConfigs` in near future

for now you can try:

`rnv platform eject`
=> select `web`

you'll now run web in ejected mode (platformTemplate managed directly in your project)

then you'll see file `platformTemplates/web/_privateConfig/webpack.config.dev.js`

try to change:
```
baseUrl: '/',
```
