### ISSUE TITLE
Error: jest-haste-map: Haste module naming collision

### ISSUE THREAD

**Issue by SatadruBhattacharjee** [pavjacko/renative#155]
Facing this error:
`Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: Sample
This error is caused by `hasteImpl` returning the same name for different files.`

Got it fixed by changing the `rn-cli.config.js` file

const path = require('path');
const blacklist = require('metro-config/src/defaults/blacklist');

const config = {
    resolver:{
        blacklistRE: blacklist([
            /packages\/rnv\/node_modules\/react-native\/.*/
        ])
    },
    projectRoot: path.resolve(__dirname),
    watchFolders: [path.resolve(__dirname)],
    modulePaths: [path.resolve(__dirname)],
};

module.exports = config;

Note: I was using the `rnv template apply`

**Comment by pavjacko** [comment]
Thx @SatadruBhattacharjee .will check add this into default template to avoid same issue for others

**Comment by SatadruBhattacharjee** [comment]
> Thx @SatadruBhattacharjee .will check add this into default template to avoid same issue for others

Thanks, I have updated the snippet. This seems to be a known issue and will be solved by the snippet
