### ISSUE TITLE
can't run project

### ISSUE THREAD

**Issue by HectorLobatoSilva** [pavjacko/renative#160]
![error](https://user-images.githubusercontent.com/19859424/62065366-71bf2680-b1f4-11e9-93d7-6fab3a92fcc8.PNG)

**Comment by mihaiblaga89** [comment]
Windows support is still work in progress. Should be finished this week.

**Comment by mihaiblaga89** [comment]
you can also track the progress on this issue #154

**Comment by HectorLobatoSilva** [comment]
Thanks a lot, we can run the project in linux mint

**Comment by hajtuJ** [comment]
Can't wait for windows support !

**Comment by pavjacko** [comment]
@hajtuJ released early preview of ReNative with windows support  `0.25.0-alpha8` 🚀
