### ISSUE TITLE
can't run android project

### ISSUE THREAD

**Issue by Zeroxys** [pavjacko/renative#161]
when i run "rnv run -p android -d" the device screen show the next message : "Unknow" someone know why this happened ?  
![WhatsApp Image 2019-07-29 at 3 13 16 PM](https://user-images.githubusercontent.com/9330442/62079032-7ba45200-b213-11e9-9e32-30ee219d2061.jpeg)

**Comment by mihaiblaga89** [comment]
Did you start the packager? Rnv start

**Comment by Zeroxys** [comment]
I forgot "rnv start" now the project run well, thanks ! sorry for the issue
