### ISSUE TITLE
Cannot run android project

### ISSUE THREAD

**Issue by Ivanov89** [pavjacko/renative#165]
When I try to run Android project with `rnv run -p android -d`,  there is error:
`Task 'bundleReleaseJsAndAssets' not found in root project 'helloWorld_android'.
`
RNV version: 0.23.20
Could you tell me, how to fix that, please?

Thanks!

**Comment by lukutism** [comment]
Hey @Ivanov89, can you update project, to the latest version of RNV? @0.24.

**Comment by Ivanov89** [comment]
Hello @lukutism , I updated RNV with @0.24.0-alpha5 and now when I add `react-native-fbsdk` (0.8.0)  iOS and Android builds still crash with: 

` rnv run -p ios - ERRROR! process exited with code 1
Error: process exited with code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/rnv/dist/systemTools/exec.js:75:8)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
`
How to fix that?
Thanks!

**Comment by pavjacko** [comment]
@Ivanov89 would be good to get more logs including SUMMARY box. that would help to debug it

but assuming if you added it already you should see "react-native-fbsdk" object in `./projectConfig/plugins.json`

can you replace it with following:

```
"react-native-fbsdk": {
  "ios": {
    "plist": {
      "FacebookAppID": "REPLACE_FACEBOOK_ID",
      "FacebookDisplayName": "REPLACE_YOUR_DISPLAY_NAME",
      "LSApplicationQueriesSchemes": [
        "fbauth2",
        "fb-messenger-api",
        "fb-messenger-share-api"
      ],
      "CFBundleURLTypes": [{
          "CFBundleTypeRole": "Editor",
          "CFBundleURLSchemes": [
            "fbREPLACE_FACEBOOK_ID"
          ]
        }

      ]
    }
  },
  "androidtv": null,
  "android": {
    "AndroidManifest": {
      "children": [{
        "tag": "application",
        "android:name": ".MainApplication",
        "children": [{
            "tag": "meta-data",
            "android:name": "com.facebook.sdk.ApplicationId",
            "android:value": "@string/facebook_app_id"
          },
          {
            "tag": "meta-data",
            "android:name": "uriScheme",
            "android:value": "somecustomscheme"
          }
        ]
      }]
    },
    "ResourceStrings": {
      "children": [{
        "tag": "string",
        "name": "facebook_app_id",
        "child_value": "REPLACE_FACEBOOK_ID"
      }]
    }
  }
},
```
