### ISSUE TITLE
Navigation parameters

### ISSUE THREAD

**Issue by maximilize** [pavjacko/renative#177]
react-navigation has a second optional argument to `navigate(route, [params])` where you can specify parameters passed to the screen. However, renative only allows the route parameter to `Api.navigation.navigate`.

Is this possible in renative, or should we use a workaround for this?

**Comment by pavjacko** [comment]
@maximilize this will be added soon. ETA today/tmrw. `renative` runtime is still in early stages of development. if it's blocking you you can copy  https://github.com/pavjacko/renative/tree/master/packages/renative/src to your local dev environment (for now) until new more robust version comes out.
