### ISSUE TITLE
Create AAB for Android

### ISSUE THREAD

**Issue by MwareSolutons** [pavjacko/renative#180]
How to create an AAB for Android for upload to Google App Store?

**Comment by pavjacko** [comment]
@MwareSolutons will add this in upcoming releases

until then you could utilise buildHooks as in this example:
https://github.com/pavjacko/renative/blob/master/buildHooks/src/index.js

adding something like:

```
import somePromiseFunctionToTriggerGradleBundle from './bundleAndroid'
const hooks = {
    bundleAndroid: somePromiseFunctionToTriggerGradleBundle
}
...
```

and run it with `npx rnv hooks run -x bundleAndroid -p android`

**Comment by pavjacko** [comment]
@MwareSolutons this is now supported in `0.25.5`

simply add this to the `platforms.android.buildSchemes.[BUILD_SCHEME]` object you want to produce aab located in `./appConfigs/[YOUR_APP_ID]/config.json`

```
...
{
  ...
  "aab": true
}
...
```

**Comment by MwareSolutons** [comment]
Perfect thanks for the update...
