### ISSUE TITLE
android build is failing

### ISSUE THREAD

**Issue by aurimas535** [pavjacko/renative#183]
Android failing with error below. Doesn't matter what I'm trying production/debug device/simulator. Sometimes very rarely it's good but usually failing. Can't tell what is pattern which causing that

```
> Task :app:packageRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageRelease'.
> Execution of compression failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 20s
769 actionable tasks: 727 executed, 42 up-to-date
```

Current version is: Env Info: darwin | x64 | node v10.13.0 | rnv v0.23.42-alpha19 
Situation with latest version is even worse actually got dozens errors.

**Comment by pavjacko** [comment]
@aurimas535 could you add this:
```
"android": {
    "gradle.properties": {
      "org.gradle.jvmargs": "-Xmx4608M"
    },
```

to the root of `./projectConfig/plugins.json`

**Comment by aurimas535** [comment]
@pavjacko that helped
