### ISSUE TITLE
LG TV does not work

### ISSUE THREAD

**Issue by RicardasSimcikas** [pavjacko/renative#185]
White window loading
![Image from iOS](https://user-images.githubusercontent.com/52383327/63027498-bf56b700-beb5-11e9-8efc-e60a089ad464.jpg)
and then 
![Image from iOS (1)](https://user-images.githubusercontent.com/52383327/63027517-caa9e280-beb5-11e9-847f-5d368767f847.jpg)

**Comment by mihaiblaga89** [comment]
@RicardasSimcikas is the ip displayed on TV correct? Should be the ip of your dev machine. Also, check the console for webpack errors. The app tries to load the build from webpack-dev-server which is started after installing and starting the app on TV. Have a look at the latest lines of the console and check for any errors that might prevent webpack from starting/building. Also worth mentioning.

**Comment by RicardasSimcikas** [comment]
When you deploy the project, server does not start by itself, you have to start the server by running command 'rnv run -p webos --port 8083' , in this case rnv opens emulator and starts webpack server which also works on TV. Solution is that user choose between run emulator with webpack server or without emulator, just the server.

**Comment by mihaiblaga89** [comment]
that should not be necessary. when running `rnv run -p webos -t <ip> -d` webpack should start automatically right before starting the app on the TV. Just tested it and it works as expected. Please have a look at the output to see why webpack is failing to start. Even better, add `--info` to the command, to get the debug logs.
