### ISSUE TITLE
Issues with web and tabbed navigation

### ISSUE THREAD

**Issue by maximilize** [pavjacko/renative#191]
When using `createBottomTabNavigator` of react-navigation, I run into this error when opening the website:

`TypeError: _ReanimatedModule.default is undefined`

Is there a quick and easy solution for this? I'm not very familar with web so far.

**Comment by maximilize** [comment]
I'm using the renative `createSideMenuNavigator` method which just works find and is doing what I need.

**Comment by pavjacko** [comment]
@maximilize  yes `createBottomTabNavigator` should not be used on web based platforms, I created `createSideMenuNavigator` for this reason but want to refactor to more generic name in the future as it can be used both horizontally and vertically resp.
