### ISSUE TITLE
RNV does not print the usual output anymore

### ISSUE THREAD

**Issue by mihaiblaga89** [pavjacko/renative#192]
Running on ios for example, does not display the xcode building process anymore. Most likely due to some changes in exec.js functions

**Comment by pavjacko** [comment]
yes we need to refactor exec.js to make it more robust.

- ability to support interactive shell (should be tested with SDK tools + fastlane)
- print console logs of spawned processes (should be tested with .sh, pods, ios build, & gradle runs)
- capture errors of spawned processes (error returns + inline errors ie pods)
- keep running processes and support CTRL + c to stop them (as an option)

**Comment by mihaiblaga89** [comment]
closed by #198
