### ISSUE TITLE
Request to Add Product in Start React

### ISSUE THREAD

**Issue by maheshwari-1153** [pavjacko/renative#195]
Hello,

I am Maheshwari from team [GeekyAnts](https://geekyants.com/). 

On behalf of [Start React](https://startreact.com/), we add open source products which we find helpful to the community & also we provide credits to author itself.

Let me know if you are interested showcase your product in our open source website.

If yes, then I request you to add MIT Licence in your repo.

Looking forward to hear from you.

**Comment by pavjacko** [comment]
Hi @maheshwari-1153 . thanks. sounds great! 
Is this LICENSE enough or you need specific format? 
here is the link:
https://github.com/pavjacko/renative/blob/master/LICENSE
