### ISSUE TITLE
Errors on RNV: 0.26.0-alpha1

### ISSUE THREAD

**Issue by Ivanov89** [pavjacko/renative#197]
Updated to RNV version: `0.26.0-alpha1`

Created new project with `rnv new`

Ejected the project with `rnv platform eject`

When hit `rnv start`, the error is:

`Looking for JS files in
   /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp
   /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp 

(node:1974) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: {{PACKAGE_NAME}}-macos
  Paths: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/platformTemplates/macos/package.json collides with /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/platformBuilds/helloWorld_macos/package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (/Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/node_modules/metro/node_modules/jest-haste-map/build/index.js:569:17)
    at workerReply (/Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/node_modules/metro/node_modules/jest-haste-map/build/index.js:641:9)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Promise.all (index 11)
(node:1974) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1974) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1974) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: {{PACKAGE_NAME}}-macos
  Paths: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/platformTemplates/macos/package.json collides with /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/platformBuilds/helloWorld_macos/package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (/Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/node_modules/metro/node_modules/jest-haste-map/build/index.js:569:17)
    at workerReply (/Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/node_modules/metro/node_modules/jest-haste-map/build/index.js:641:9)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Promise.all (index 11)
(node:1974) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
`

When hit `rnv run -p web` the error is:
`┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv run -p web                                                      │
│        Start Time: 8/21/2019, 11:18:43 AM                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

$ rnv run -p web - initializeBuilder - Starting!
⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/renative.local.json does not exists!
⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/renative.private.json does not exists!
$ rnv run -p web - _generateBuildConfig - Starting!
Merged: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/renative.json
$ rnv run -p web - _generateBuildConfig:14:3:1:1 - Starting!
ℹ️  $ rnv run -p web - NOTE: Path undefined is not defined. using default: undefined
⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/.rnv/cmslobbyapp/renative.json does not exists!
⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/.rnv/cmslobbyapp/renative.local.json does not exists!
⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/.rnv/cmslobbyapp/renative.private.json does not exists!
$ rnv run -p web - _generateBuildConfig - Starting!
Merged: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/renative.json
$ rnv run -p web - _generateBuildConfig:14:6:1:1 - Starting!
ℹ️  $ rnv run -p web - NOTE: Path appConfigsDir is not defined. using default: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/appConfigs
$ rnv run -p web - configureRnvGlobal - Starting!
/Users/user/.rnv folder exists!
/Users/user/.rnv/renative.json file exists!
$ rnv run -p web - checkIfTemplateInstalled - Starting!
$ rnv run -p web - fixRenativeConfigsSync - Starting!
$ rnv run -p web - checkAndCreateProjectPackage:undefined - Starting!
$ rnv run -p web - checkAndCreateGitignore - Starting!
$ rnv run -p web - configureProject:check rn-cli - Starting!
$ rnv run -p web - configureProject:check babel config - Starting!
$ rnv run -p web - configureNodeModules - Starting!
$ rnv run -p web - applyTemplate - Starting!
$ rnv run -p web - _applyTemplate:/Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/node_modules/renative-template-hello-world - Starting!
$ rnv run -p web - configureProject:check src - Starting!
$ rnv run -p web - configureProject:check appConfigs - Starting!
$ rnv run -p web - setAppConfig:helloWorld - Starting!
⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/appConfigs/helloWorld/renative.local.json does not exists!
⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/appConfigs/helloWorld/renative.private.json does not exists!
$ rnv run -p web - _generateBuildConfig - Starting!
Merged: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/renative.json
Merged: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/appConfigs/helloWorld/renative.json
$ rnv run -p web - _generateBuildConfig:14:9:2:2 - Starting!
⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/.rnv/cmslobbyapp/appConfigs/helloWorld/renative.json does not exists!
⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/.rnv/cmslobbyapp/appConfigs/helloWorld/renative.local.json does not exists!
⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/.rnv/cmslobbyapp/appConfigs/helloWorld/renative.private.json does not exists!
$ rnv run -p web - _generateBuildConfig - Starting!
Merged: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/renative.json
Merged: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/appConfigs/helloWorld/renative.json
$ rnv run -p web - _generateBuildConfig:14:12:2:2 - Starting!
$ rnv run -p web - _generateBuildConfig - Starting!
Merged: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/renative.json
Merged: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/appConfigs/helloWorld/renative.json
$ rnv run -p web - _generateBuildConfig:14:12:2:2 - Starting!
$ rnv run -p web - configureProject:check projectConfigs - Starting!
$ rnv run -p web - configureNodeModules - Starting!
$ rnv run -p web - configureApp:helloWorld - Starting!
$ rnv run -p web - updateConfig:helloWorld - Starting!
$ rnv run -p web - setAppConfig:helloWorld - Starting!
⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/appConfigs/helloWorld/renative.local.json does not exists!
⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/appConfigs/helloWorld/renative.private.json does not exists!
$ rnv run -p web - _generateBuildConfig - Starting!
Merged: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/renative.json
Merged: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/appConfigs/helloWorld/renative.json
$ rnv run -p web - _generateBuildConfig:14:12:2:2 - Starting!
⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/.rnv/cmslobbyapp/appConfigs/helloWorld/renative.json does not exists!
⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/.rnv/cmslobbyapp/appConfigs/helloWorld/renative.local.json does not exists!
⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/.rnv/cmslobbyapp/appConfigs/helloWorld/renative.private.json does not exists!
$ rnv run -p web - _generateBuildConfig - Starting!
Merged: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/renative.json
Merged: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/appConfigs/helloWorld/renative.json
$ rnv run -p web - _generateBuildConfig:14:12:2:2 - Starting!
$ rnv run -p web - _generateBuildConfig - Starting!
Merged: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/renative.json
Merged: /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/appConfigs/helloWorld/renative.json
$ rnv run -p web - _generateBuildConfig:14:12:2:2 - Starting!
ADDADADA helloWorld /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/appConfigs/helloWorld
$ rnv run -p web - configureEntryPoints - Starting!

----------------------------------------------------------
ℹ️  Current App Config: helloWorld
----------------------------------------------------------
$ rnv run -p web - run - Starting!
$ rnv run -p web - _runApp:web - Starting!
$ rnv run -p web - isPlatformSupported:web - Starting!
$ rnv run -p web - isBuildSchemeSupported:web - Starting!
$ rnv run -p web - _runAppWithPlatform:web - Starting!
$ rnv run -p web - _runAppWithPlatform:web:8080:undefined - Starting!
$ rnv run -p web - getConfigProp:web:bundleAssets:undefined - Starting!
$ rnv run -p web - executePipe:run:before - Starting!
$ rnv run -p web - buildHooks - Starting!
$ rnv run -p web - _configureIfRequired:web - Starting!
$ rnv run -p web - createPlatformBuild:web - Starting!
$ rnv run -p web - run - Starting!
$ rnv run -p web - _runConfigure:web - Starting!
$ rnv run -p web - executePipe:configure:before - Starting!
$ rnv run -p web - buildHooks - Starting!
$ rnv run -p web - _checkAndCreatePlatforms:web - Starting!
$ rnv run -p web - copyRuntimeAssets - Starting!
$ rnv run -p web - _copySharedPlatform:web - Starting!
$ rnv run -p web - _runPlugins:/usr/local/lib/node_modules/rnv/plugins - Starting!
$ rnv run -p web - _runPlugins:/Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/projectConfig/plugins - Starting!
ℹ️  $ rnv run -p web - NOTE: Your project plugin folder /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/projectConfig/plugins does not exists. skipping plugin configuration
$ rnv run -p web - configureWebProject:web - Starting!
$ rnv run -p web - copyBuildsFolder:web - Starting!
$ rnv run -p web - parsePlugins:web - Starting!
$ rnv run -p web - getConfigProp:web:includedPlugins:* - Starting!
$ rnv run -p web - getConfigProp:web:excludedPlugins:undefined - Starting!
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 8/21/2019, 11:18:43 AM                                        │
│  $ rnv run -p web                                                            │
├──────────────────────────────────────────────────────────────────────────────┤
│  Project Name: cmslobbyapp                                                   │
│  Project Version: 0.1.0                                                      │
│  App Config: helloWorld                                                      │
│  Supported Platfroms: ios, android, androidtv, androidwear,                  │
│  web, tizen, tizenmobile, tvos, webos, macos, windows, tizenwatch,           │
│  kaios, firefoxos, firefoxtv                                                 │
│  Master Template: renative-template-hello-world                              │
│  Env Info: darwin | x64 | node v12.4.0 | rnv vundefined                      │
│  Platform: web                                                               │
│  Executed Time: 0h:0m:0s:53ms                                                │
│                                                                              │
│ ⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/renative.local.json does not exists!
│ ⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/renative.private.json does not exists!
│ ⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/.rnv/cmslobbyapp/renative.json does not exists!
│ ⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/.rnv/cmslobbyapp/renative.local.json does not exists!
│ ⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/.rnv/cmslobbyapp/renative.private.json does not exists!
│ ⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/appConfigs/helloWorld/renative.local.json does not exists!
│ ⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/Development/PROJECTS/cmslobbyapp/CMSLobbyApp2/CMSLobbyApp/appConfigs/helloWorld/renative.private.json does not exists!
│ ⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/.rnv/cmslobbyapp/appConfigs/helloWorld/renative.json does not exists!
│ ⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/.rnv/cmslobbyapp/appConfigs/helloWorld/renative.local.json does not exists!
│ ⚠️  $ rnv run -p web - WARNING: _loadFile: Path /Users/user/.rnv/cmslobbyapp/appConfigs/helloWorld/renative.private.json does not exists!
│ 🛑  $ rnv run -p web - ERRROR! Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at parsePlugins (/usr/local/lib/node_modules/rnv/dist/pluginTools/index.js:34:8)
    at /usr/local/lib/node_modules/rnv/dist/common.js:639:30
    at new Promise (<anonymous>)
    at copyBuildsFolder (/usr/local/lib/node_modules/rnv/dist/common.js:617:67)
    at /usr/local/lib/node_modules/rnv/dist/platformTools/web.js:127:29
    at new Promise (<anonymous>)
    at configureWebProject (/usr/local/lib/node_modules/rnv/dist/platformTools/web.js:120:73)
    at /usr/local/lib/node_modules/rnv/dist/cli/app.js:128:80
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
│                                                                        
`

How to build the project guys, every time there is some errors, how to downgrade older stable build with RNV - I just want to start a new project with the RNV but every time something is broken ?
Thanks!

**Comment by pavjacko** [comment]
@Ivanov89 don't use `0.26.0-alphaXXX` releases. 

we're in the middle of major cleanup and unfortunately to test whole lifecycle I need to run it trough NPM published flow

next stable release will be `0.26.0` (without -alphaXXX)
either today or tmrw

until then use `0.25.x` instead

**Comment by Ivanov89** [comment]
@pavjacko  thank you, but how to downgrade for example to `0.25.x` release?

**Comment by pavjacko** [comment]
@Ivanov89 should be easy

globally:

`npm install rnv@0.25.7 -g`

and you can manually downgrade per project in `package.json` 

```
{
   "devDependencies": {
        "rnv": "0.25.7"
     }
}
```

**Comment by Ivanov89** [comment]
@pavjacko  thank you, `0.25.7`  seems to work and it is build correctly and now I can start my project with this version :)

**Comment by Ivanov89** [comment]
@pavjacko where I can get some know how how to use the `react-navigation` in the current `0.25.7` release, because it is a lot different from `0.21.4` ?

Thanks!
