### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by GeekRishabh** [pavjacko/renative#20]
• Add Hot reloading to android wear 
• How to run on Apple watch 
• How to add native library of React Native to android wear and other platform 
• How redux , navigation work for other platforms

**Comment by pavjacko** [comment]
@GeekRishabh thx for the feedback. created separate tickets to track this:

Apple Watch:  https://github.com/pavjacko/react-native-vanilla/issues/21
Navigation: https://github.com/pavjacko/react-native-vanilla/issues/22
Android wear hot reloading: https://github.com/pavjacko/react-native-vanilla/issues/25
