### ISSUE TITLE
permission.json IOS format

### ISSUE THREAD

**Issue by MwareSolutons** [pavjacko/renative#206]
what is the format for adding key + string in plist permissions.json 

i have done this but it only adds the key not the string value

{
    "permissions": {
        "ios": {
            "NSBluetoothPeripheralUsageDescription": {
                "key": "NSBluetoothPeripheralUsageDescription",
                "string" : "for app analytics"
            
            },  
            "NSMicrophoneUsageDescription": {
                "key": "NSMicrophoneUsageDescription",
                "string": "for app analytics"
            
            },
            "NSLocationAlwaysUsageDescription": {
                "key": "NSLocationAlwaysUsageDescription",
                "string": "for app analytics"
            
            },
            "NSLocationWhenInUseUsageDescription": {
                "key": "NSLocationWhenInUseUsageDescription",
                "string": "for app analytics"
            }   
        },
        "android": {}
    }
}

**Comment by pavjacko** [comment]
@MwareSolutons in your 
`./appConfigs/[APP_ID]/config.json` if running  0.25.x and lower
`./appConfigs/[APP_ID]/renative.json` if running `0.26.x` and higher

make sure include specific (key) or all (*) permissions defined above:

```
{
   ...
   "platforms": {
         "ios": {
               "permissions": ["*"]
         }
   }
}
```
