### ISSUE TITLE
Run androidtv on device target?

### ISSUE THREAD

**Issue by jfrux** [pavjacko/renative#208]
How would one go about this?

**Comment by pavjacko** [comment]
@jfrux  `rnv run -p androidtv -d`

**Comment by jfrux** [comment]
Thanks for the response… it’s not detecting my device for some reason even though it shows up in `adb devices` list.
Does it matter that it’s TECHNICALLY a FireTV?

--
Joshua F. Rountree
UX Developer
Newsy, The E.W. Scripps Company
312 Walnut Street, Suite 2800, Floor 29th, Office 29W109
Cincinnati, Ohio 45202-4024
(513) 977-3840 (office, M-F, 7a-4p)
(513) 827-7936 (mobile)


Newsy is America’s fastest-growing news network

**Comment by pavjacko** [comment]
@jfrux hmm that should still be treated as android TV at least for now. it would be useful if you run your command with `--info` and share logs especially the part where loads of device info arrays are printed out

@mihaiblaga89 could you check it out

I got one spare FireTV around will try to replicate it as well sometime tmrw

**Comment by mihaiblaga89** [comment]
@jfrux issue should be fixed. You can also specify the device's IP if it's not connected via cable with `rnv run -p androidtv -d -t <ip>`. If for some reason it doesn't work, please send me the output of `--info` like suggested above.

**Comment by jfrux** [comment]
Siiiick! Thanks my dude.  I was actually about to look into this issue a bit more myself to see if I can contribute back.
Very promising work you’re doing, but nobody will tell you or talk about it… this industry is super hush.  It’s like nobody really wants to help others get into this space… I appreciate the efforts you guys are pushing.

<3 jfrux

Newsy is America’s fastest-growing news network

**Comment by mihaiblaga89** [comment]
Yeah, it still 'sees' your firetv as a tablet (`isTablet: true`), that's the main issue. Detecting a device is a bit of trial and error and apparently our firetv and yours return very different props. I'll update the checks.

**Comment by pavjacko** [comment]
@jfrux  this should unblock any unknown devices if encountered in future https://github.com/pavjacko/renative/pull/217

we're doing massive testing regression + bug fixing of 0.26.x that's priority to get it out. it'a big upgrade and will unblock further platform expansion.
btw thanks for reporting issues back. very much appreciated! 💯
