### ISSUE TITLE
`rnv new`+ `rnv run -p web` fails first try. 

### ISSUE THREAD

**Issue by IevaJacko** [pavjacko/renative#209]
I get this after `rnv run -p web` when creating new app

ERROR in ./node_modules/renative/src/Navigation/menuNavigator/utils/createTabNavigator.js
Module not found: Error: Can't resolve '@react-navigation/core' in '/Users/ievapipinyte/DEV/Code/talk-now/node_modules/renative/src/Navigation/menuNavigator/utils'

second try works fine

I'm using version 0.26.0-alpha9

**Comment by pavjacko** [comment]
fixed in `0.26.0-rc2`
