### ISSUE TITLE
In Alpha RC7, hello-world template chosen regardless of selection of blank in `rnv new`

### ISSUE THREAD

**Issue by jfrux** [pavjacko/renative#219]

**Comment by mihaiblaga89** [comment]
please explain `selection of blank`

**Comment by jfrux** [comment]
On the step that asks for the template to install, “hello-world”, “blank”, etc. when running `rnv new` it’s still using helloWorld instead of making a blank project.

--
Joshua F. Rountree
UX Developer
Newsy, The E.W. Scripps Company
312 Walnut Street, Suite 2800, Floor 29th, Office 29W109
Cincinnati, Ohio 45202-4024
(513) 977-3840 (office, M-F, 7a-4p)
(513) 827-7936 (mobile)


Newsy is America’s fastest-growing news network

**Comment by pavjacko** [comment]
@jfrux @mihaiblaga89 fix is included in `0.26.0-rc8`
