### ISSUE TITLE
ERRROR! ERROR: no app ID specified

### ISSUE THREAD

**Issue by rdobda-gaia** [pavjacko/renative#23]
Hey looks like a bunch of improvements have been being made (and may still be underway). This is awesome. However, i think there may be some documentation issues and instability. Here's what i found.
1. I ran all the setup stuff including changing my config file in ~/.rnv and running the setup
2. I got to the 3-panel terminal and ran in the first panel npm-start
3. In the second panel i ran npx rnv target list or npm run tizen
 or npm run webos and i get RNV target - ERRROR! ERROR: no app ID specified.
 
Also the new code has a lot of unused variables and general cleanup missing. It seems like this is indeed a major upgrade and maybe is not quite stable yet. Can you keep me in the loop when you feel that this release is stable and has all your latest ideas solid? thanks!

**Comment by aurimas535** [comment]
Did you run `npx rnv app configure -c helloWorld -u` successfully?

**Comment by pavjacko** [comment]
@rdobda-gaia thx for the feedback! 
Yes big (but necessary) upgrade. it's still under development so cleaning as I go :D
So there is new release `0.9.4` with simplified installation procedure.
you will only need:
`npm i`
then:
`npm run web` / `npm run ios` / ... that's it :)

to get you up and running straight away . more info:
https://github.com/pavjacko/react-native-vanilla#quick-start

**Comment by pavjacko** [comment]
@rdobda-gaia with major updates done over past few months, the general issues/remarks mentioned in this ticket should be solved by now so I'm closing it :)
