### ISSUE TITLE
createSideMenuNavigator can't handle navigation params

### ISSUE THREAD

**Issue by maximilize** [pavjacko/renative#231]
When adding a screen which needs a dynamic navigation parameter (from a call of `navigation.navigate('Screen', {param: 'eter'})`, there will be an instant exception when the app is starting, even the screen is not shown.

When creating a sub stack navigator which holds the screen, the initial render works fine, but a `navigate` to the screen will cause the same error, or if using a default `params` value of `{}`, the parameters of the function call will not be forwarded.

**Comment by mihaiblaga89** [comment]
duplicate of #214

**Comment by maximilize** [comment]
Thanks, so I'm closing this issue.
