### ISSUE TITLE
Fix vulnerabilities

### ISSUE THREAD

**Issue by maximilize** [pavjacko/renative#237]
There are quite many vulnerabilities when installing rnv:
`found 87 vulnerabilities (85 low, 1 moderate, 1 high)`

Updating jest to the latest version fixes already more than 50% of them.
With `css-loader` I don't have any experience, but this package causes the one high priority vulnerability.

**Comment by pavjacko** [comment]
@maximilize good point. I'll check the upgrades

**Comment by pavjacko** [comment]
tested locally and pushed hotfix to develop. will see what CI will say.
got it down to:
`found 22 low severity vulnerabilities`
all of them are react-native related which should be fixed one #239 is completed

**Comment by pavjacko** [comment]
HOTFIX released `0.26.2`
