### ISSUE TITLE
Upgrade to react-native 0.61.1

### ISSUE THREAD

**Issue by pavjacko** [pavjacko/renative#239]

**Comment by maximilize** [comment]
@pavjacko What is the plan here? There are many interesting new features and bugfixes in 0.60, and 0.61 is already on it's way.

**Comment by pavjacko** [comment]
@maximilize almost there! https://github.com/pavjacko/renative/pull/269 should be ready end of this week. Alpha preview should be even sooner. this will support `0.61.1` already

**Comment by maximilize** [comment]
@pavjacko That's great news. I'll have a look into this later when we start our migration to web and tizen.

**Comment by pavjacko** [comment]
@maximilize  `0.28.0-alpha.2` is out with support for RN 0.62.2 with all major platforms. 
PR https://github.com/pavjacko/renative/pull/269 will be open for QA/Fixes until we have stable release and can migrate fully to `0.28.0`
