### ISSUE TITLE
Workspaces

### ISSUE THREAD

**Issue by pavjacko** [pavjacko/renative#243]
This feature enables management multiple workspaces on developer machine ie:
`~/.rnv` (DEFAULT)
`~/.myCompanyX`
`~/.myCompanyY`
..

this will then enable support for dedicated private scoped plugins / templates / integrations / keys / sources etc which are only available per specific workspace and allows seamless integration into rnv commands like:

`rnv plugin add`
`rnv template add`

etc

Example how to add existing company-wide workspace (github route):

`rnv workspace add --git git@github.com:company-x/renative-workspace.git --dest ~/.myCompanyX`

**Comment by mihaiblaga89** [comment]
Already implemented
