### ISSUE TITLE
Add Hermes support (JavaScript Engine optimized for React Native)

### ISSUE THREAD

**Issue by sanderlooijenga** [pavjacko/renative#267]
Might be nice to add Hermes support (for Android), you can read about it [here](https://facebook.github.io/react-native/blog/2019/07/17/hermes) and [here](https://facebook.github.io/react-native/docs/hermes).

**Comment by pavjacko** [comment]
@sanderlooijenga `0.28.0-alpha.2` is out with support for Hermes. 
PR https://github.com/pavjacko/renative/pull/269 will be open for QA/Fixes until we have stable release and can migrate fully to `0.28.0`

**Comment by sanderlooijenga** [comment]
Thanks @pavjacko also be aware of; https://github.com/facebook/react-native/pull/26759 _"this fixes Hermes & Android App Bundle so it would be great to get it in 0.61.3"_
