### ISSUE TITLE
npm i rnv@latest -g on windows missing Python

### ISSUE THREAD

**Issue by RicardasSimcikas** [pavjacko/renative#272]
Installing rnv on windows returns this error. Should I expect rnv to take care of it?

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ricsim\AppData\Roaming\npm\node_modules\rnv\node_modules\node-expat
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by mihaiblaga89** [comment]
This seems like a `node-gyp` issue, it requires python (https://github.com/nodejs/node-gyp). At the moment `rnv` does not have support for installing python in this case but we might treat this case as well, in the future. For now make sure you have python installed, as per `node-gyp` requirements

**Comment by pavjacko** [comment]
fixed in #505
