### ISSUE TITLE
Android SDK path error

### ISSUE THREAD

**Issue by vittoriomigliore** [pavjacko/renative#284]
**Describe the bug**
Android build fails due to a SDK directory error

**To Reproduce**

- Just create a new rnv project with HelloWorld template.
- I set my AndroidSDK directory on **_MyUser_\\.rnv\renative.json** like follow:
`"sdks": {
        "ANDROID_SDK": "/Users/<USER>/AppData/Local/Android/Sdk",
...`
- I added some "\\"s at sharedBlacklist var on **_MyProject_\node_modules\metro-config\src\defaults\blacklist.js** to resolve [#453](https://github.com/facebook/metro/issues/453) metro issue
I don't know if it's relevant.
- `rnv build -p androidtv -i`
- Getting this error:
```
× FAILED: gradlew.bat assembleDebug -x bundleReleaseJsAndAssets                                                         
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> The SDK directory 'C:\Users\MyUser\projects\MyProject\platformBuilds\helloWorld_androidtv\Users\<USER>\AppData\Local\Android\Sdk' does not exist.
```
It appends ANDROID_SDK var at _MyProject_ path. It doesn't replace <USER> with _MyUser_ name too but I can easily adjust it replacing with _MyUser_

**Desktop (please complete the following information):**
 - OS: windows10
 - Node Version v12.11.0
 - RNV Version 0.27.3

**Comment by mihaiblaga89** [comment]
The `.rnv/config` file is created with default values. Change the path from whatever you have there to the absolute path of your Android SDK. Something like 
```
{
   "sdks": {
      "ANDROID_SDK": "C:\\Users\\User\\Android,
  }
}
```

**Comment by vittoriomigliore** [comment]
It's ok. Thank you.

**Comment by CarlosKvasir** [comment]
https://stackoverflow.com/questions/58120990/question-getting-error-on-react-native-start
