### ISSUE TITLE
Add missing/new platform to project

### ISSUE THREAD

**Issue by sanderlooijenga** [pavjacko/renative#288]
RNV Version;

```
Supported Platforms: ios, android, web, androidtv, tvos                                                                 
Env Info: darwin | x64 | node v11.10.0 | rnv v0.27.4
```

I've setup my project to support/include the aforementioned platforms, how do I go about adding support for another Platform to my project, e.g. **Tizen**? (other than doing it _manually_)

Is/will/should there be a command to achieve this?

Thanks in advance.

**Comment by sanderlooijenga** [comment]
For clarity reasons, how is this now fixed? Or; how can we now configure/enable new/missing platforms? :)

**Comment by mihaiblaga89** [comment]
`rnv platform setup`, forgot to add it in the docs. Good catch!
