### ISSUE TITLE
RNV development kit

### ISSUE THREAD

**Issue by aurimas535** [pavjacko/renative#31]
RNV itself is about CLI tools now, but what about to extending it with development kit? 

For example, highly useful tools would be helpers to determine which platform we work on. We have `src/api.js` now, but it does not always work or only works in render() method because it's initialized during runtime and often the values are 'unknown'.

Thinking about creating a separate module to provide information about each platform might look like this:
```
import { IS_TIZEN, IS_MOBILE } from 'rnv-helpers';
{IS_TIZEN && 'Its tizen'}
```
or 
```
import { Platform } from 'rnv-helpers';
{Platform('tizen') && 'Its tizen'}
```

So main question how to implement these into current RNV architecture?
1) Create it as local npm package(`file:./packages/rnvHelpers`) and copy over it into the project when `rnv create app` is executed
2) Publish it as separate npm package and include it into RNV dependencies with initial project setup

It's not only about these helpers mentioned above. I'm sure we will extend it with i.e. prepared multi platform navigation, focus management etc..

So what is your thoughts?

**Comment by pavjacko** [comment]
@aurimas535 correct. main purpose of RNV is to provide multi-platform build infrastructure. But agree there seem to be need for thin layer of abstraction helpers for runtime as well like `src/api.js` but properly decoupled

**Comment by pavjacko** [comment]
@aurimas535 
https://www.npmjs.com/package/renative now provides runtime SDK entry point. published from:
https://github.com/pavjacko/renative/tree/master/packages/renative

development of runtime utils can continue there

CLI is now served from https://www.npmjs.com/package/rnv published from:
https://github.com/pavjacko/renative/tree/master/packages/rnv
