### ISSUE TITLE
failed to connect to remote target

### ISSUE THREAD

**Issue by NazarElinskii** [pavjacko/renative#310]
Hi everyone
I have a problem with launching the sample project on SamsungTV(Tizen)
I use this cli command **rnv run -p tizen -d -t 192.168.100.96** and after that i see 

```
rnv run -p tizen -d -t 192.168.100.96 - ERRROR! error: failed to connect to remote target '192.168.100.96'
Error: error: failed to connect to remote target '192.168.100.96'
    at getDeviceID$ (/usr/local/lib/node_modules/rnv/dist/platformTools/tizen/index.js:94:94)
    at tryCatch (/usr/local/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.<computed> [as next] (/usr/local/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:114:21)
    at tryCatch (/usr/local/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:62:40)
    at invoke (/usr/local/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:152:20)
    at /usr/local/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:162:13
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by mihaiblaga89** [comment]
Did you follow the guide to set the TV for deployment? (https://developer.samsung.com/tv/develop/getting-started/using-sdk/tv-device).

**Comment by NazarElinskii** [comment]
Yes)

**Comment by mihaiblaga89** [comment]
Then you're not connected on the same network or a firewall is blocking the connection. That error comes from their CLI. What Tizen version is it?

**Comment by NazarElinskii** [comment]
SDK version is 3.0

**Comment by NazarElinskii** [comment]
SDK version is 3.0
And i checked that my device and my laptop are in the same network

**Comment by NazarElinskii** [comment]
All works good, thnx, I wasn't paying attention.

**Comment by mihaiblaga89** [comment]
No worries. If you have any more questions or issues please let us know.

**Comment by NazarElinskii** [comment]
Sure, thnx a lot)

**Comment by Guidogl** [comment]
I am trying to run template application on my Tizen TV, without much success. I already connected TV to my laptop and I can see that connection is ON. How to run this application on my TV? `rnv target launch -p tizen -t <device-name>` doesn't seem to find my device.

**Comment by mihaiblaga89** [comment]
@Guidogl please read the documentation. https://renative.org/docs/tizen
`rnv target launch` does exactly what it says, it launches a target (i.e. emulator). You should use `rnv run -p tizen -t <ip of the tv> -d`, but only after you configured the tv to accept your connection (https://developer.samsung.com/tv/develop/getting-started/using-sdk/tv-device)

**Comment by Guidogl** [comment]
@mihaiblaga89 I have tried several times without success. I successfully launched an emulator with `rnv target launch` but then received the following error after running `rnv run -p tizen` command: 

`FAILED with ERROR: 

Author password: An error has occurred. See the log file tizen-sdk\tools\ide\cli.log.`

When I am trying to run `-p tizen -t <ip of the tv> -d`, I just get the following message:` Could not find or connect to the specified target (T-samsung-5.0-x86).`
