### ISSUE TITLE
Failing to install ios-deploy package

### ISSUE THREAD

**Issue by doneitas** [pavjacko/renative#321]
Getting an error when trying to install **ios-deploy** package.

**To Reproduce**
1. Just try to install **ios-deploy**, e.g.:
 `npm i -g ios-deploy`
or
`sudo npm install -g ios-deploy --unsafe-perm=true`
2. See error

**Expected behavior**
ios-deploy package should be successfully installed.

**Error**
```
npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! ios-deploy@1.9.4 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! Exit status 65
npm ERR! 
npm ERR! Failed at the ios-deploy@1.9.4 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Desktop:**
 - OS: macOS Catalina 10.15
 - Node Version: v10.16.3
 - RNV Version: 0.28.0-alpha.10

**Comment by mihaiblaga89** [comment]
It's an issue with `ios-deploy` regarding Catalina. https://github.com/ios-control/ios-deploy/issues/400. You can get around it by installing it with `brew install ios-deploy` for now. We're waiting for them to release the fix
