### ISSUE TITLE
How to add dependencies

### ISSUE THREAD

**Issue by snakecharmer** [pavjacko/renative#34]
Hi,

How can I add a dependency to the project? For example I'm trying to add a video player or vector-icons and doesn't build anymore.

Is there any workflow to follow?

**Comment by pavjacko** [comment]
@snakecharmer it depends on specific dependency. there are 2 options. 

**1) RNV Plugins** (make sure your RNV is at least 0.17.5 ... `rnv --version`)

add new plugin to `./projectConfig/plugins.json` for video could use:

```
"plugins" : {
   "react-native-video" : {
      "version": "2.0.0",
      "ios": { "podName": "react-native-video" },
      "android": { "package": "com.brentvatne.react.ReactVideoPackage" }
    }
}
```

then you can use `import Video from 'react-native-video';` in you project

`rnv run -p ios` `rnv run -p android`

**2) Manually**
add your dependency to ./package.json
`npm i`

`rnv platform eject`

your platform templates will be located at `./platformTemplates` you can update android build.gradle and ios Pods just like you would do with standard react native cocoapods based projects

`rnv run -p ios` `rnv run -p android`

vector icons would have similar workflow but next release will most likely include them as standard due to high demand on various projects!

also with issues it's good to post error logs to understand your problem better :)

**Comment by iamsabet** [comment]
Hi dude ,
nice job really , 
im just having a trouble right now i added dependencies with rnv plugins like this 
`{
  "name": "board-game-baz",
  "defaultAppId": "com.tedon.boardgamebaz",
  "defaultAppConfigId": "boardGameBazExample",
  "title": "Board Game Baz",
  "version": "0.1.0",
  "dependencies": {
    "react-native-gesture-handler": "github:kmagiera/react-native-gesture-handler",
    "react-native-scrollable-navigation-bar": "0.0.4",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^3.6.1",
    "react-navigation-drawer": "^1.2.1",
    "react-navigation-stack": "^1.2.0",
    "react-navigation-tabs": "^2.1.0"
  },
  "devDependencies": {
    "install-peers": "^1.0.3",
    "react-native-vanilla": "0.17.5"
  },
  "jest": {
    "preset": "react-native",
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    }
  }
}
`

platform is connected ,
when i `rnv start` --> install and ovveride package.json like this 
`{
  "name": "board-game-baz",
  "defaultAppId": "com.tedon.boardgamebaz",
  "defaultAppConfigId": "boardGameBazExample",
  "title": "Board Game Baz",
  "version": "0.1.0",
  "dependencies": {
    "react-native-gesture-handler": "github:kmagiera/react-native-gesture-handler",
    "react-native-scrollable-navigation-bar": "0.0.4",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^3.6.1",
    "react-navigation-drawer": "^1.2.1",
    "react-navigation-stack": "^1.2.0",
    "react-navigation-tabs": "^2.1.0"
  },
  "devDependencies": {
    "install-peers": "^1.0.3",
    "react-native-vanilla": "0.17.5"
  },
  "jest": {
    "preset": "react-native",
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    }
  }
}
`

but still when i run -p web --> failed in load all of my installed dependencies ,
<img width="1100" alt="Screen Shot 2019-04-08 at 4 30 58 PM" src="https://user-images.githubusercontent.com/20267993/55722504-bf343f80-5a1b-11e9-81a9-731a3ae5aa73.png">

**Comment by danielmarino24i** [comment]
that's on web right?
try adding to your webpack babel loader this on the `include` part:
```
path.resolve(appDirectory, 'node_modules/react-navigation'),
        path.resolve(appDirectory, 'node_modules/@react-navigation/native'),
        path.resolve(appDirectory, 'node_modules/@react-navigation/core'),
        path.resolve(appDirectory, 'node_modules/react-native-gesture-handler'),
        path.resolve(appDirectory, 'node_modules/@react-navigation/web'),
        path.resolve(appDirectory, 'node_modules/@react-navigation/core'),
        path.resolve(appDirectory, 'node_modules/react-native-screens'),
```

**Comment by iamsabet** [comment]
@danielmarino24i yeah this totaly resolved ,

```

path.resolve(appDirectory, 'src'),
        path.resolve(appDirectory, 'node_modules'),
        path.resolve(appDirectory, 'node_modules/react-navigation'),
        path.resolve(appDirectory, 'node_modules/@react-navigation/native'),
        path.resolve(appDirectory, 'node_modules/@react-navigation/core'),
        path.resolve(appDirectory, 'node_modules/react-native-gesture-handler'),
        path.resolve(appDirectory, 'node_modules/@react-navigation/web'),
        path.resolve(appDirectory, 'node_modules/@react-navigation/core'),
        path.resolve(appDirectory, 'node_modules/react-native-screens'),
        path.resolve(appDirectory, 'node_modules/react-native-scrollable-navigation-bar'),

```

thanks

**Comment by pavjacko** [comment]
good one @danielmarino24i  I'll extend plugin script to support web platforms as well

**Comment by pavjacko** [comment]
as of `0.23.0-alpha.15` dynamic plugins support webpack configs. so closing it
