### ISSUE TITLE
Deploy Web

### ISSUE THREAD

**Issue by ahwelgemoed** [pavjacko/renative#35]
Hey - 
I'm very new to RNV and have played with it for last couple of days - Really liking it, I have an app running on tvOS and would like to build it to web as well.
I am familiar on how to build Create React Apps for deployment, but how do you build and deploy a RNV web app? 

Sorry if it a trivial or stupid question. 

Thanks

**Comment by pavjacko** [comment]
@ahwelgemoed  Not stupid at all. quite relevant actually :) web builds / deploy is coming soon. you can already try in preview version `0.18.0-alpha3` it includes support for `rnv build -p web` which creates `public` directory in `./platformBuilds/<CONFIG_ID>_web` for you to upload to any hosting provider.

`rnv deploy -p web` coming soon as well. You will able to configure and deploy web apps in similar way as Create React Apps

**Comment by ahwelgemoed** [comment]
Thanks - I upgraded and It worked. 🔥
