### ISSUE TITLE
 I can't run my web project because dependency (You may need an appropriate loader to handle this file type.)

### ISSUE THREAD

**Issue by RafaelAugustoS** [pavjacko/renative#353]
I can't run my project on the web because of one component (my own)

> You may need an appropriate loader to handle this file type.
![Screen Shot 2019-11-18 at 14 05 37](https://user-images.githubusercontent.com/5261655/69073630-85dd9c80-0a0c-11ea-89e6-573928de97b6.png)

**Comment by sanderlooijenga** [comment]
Did you add it to the plugins section of your project's `renative.json`?

So add something like;

```json
{
    …
    "plugins": {
        …
        "popup-ui": {
            "version": "1.2.3", // <YOUR PACKAGE VERSION>
            "webpack": {
                "modulePaths": true
            }
        },
        …
    }
    …
}

**Comment by CHaNGeTe** [comment]
@RafaelAugustoS what Sander suggests will feed your package on the babel flow, which AFAIK has the proper babel config to use static members, and JSX, Which I see is what is giving you problems on webpack.
Try @sanderlooijenga 's suggestion, at least the error should change, but my guess it will just work.
Let us know!
