### ISSUE TITLE
Hot reload on electron?

### ISSUE THREAD

**Issue by DonsWayo** [pavjacko/renative#36]
I can do the hot reload on electron like on react native or web?

**Comment by pavjacko** [comment]
@DonsWayo hot reload on electron is not supported yet. but it is coming soon! scheduled for `0.19.0` release

**Comment by pavjacko** [comment]
@DonsWayo 0.19.0 now includes hot reload for electron projects.
I advise to create new project with `rnv app create`
Then simply run `rnv run -p macos`
For production build run `rnv run -p macos -s release`

**Comment by DonsWayo** [comment]
@pavjacko many thanks and good work!
