### ISSUE TITLE
rnv new stuck at question 'What workspace to use?'

### ISSUE THREAD

**Issue by amitbravo** [pavjacko/renative#368]
![Screenshot 2019-12-13 at 2 02 41 PM](https://user-images.githubusercontent.com/16644357/70786278-4bb8ae00-1db2-11ea-916a-00bc6345d7fc.png)

I keep hitting arrows key and nothing is working , I can not pass through this question.

OS: OSX
Node Version: v13.3.0
RNV Version: rnv@0.28.11

**Comment by amitbravo** [comment]
![trimmed (1)](https://user-images.githubusercontent.com/16644357/70903267-86c21800-2024-11ea-859d-4ad70fbce9a5.gif)

**Comment by mihaiblaga89** [comment]
Working on it as we speak

**Comment by mihaiblaga89** [comment]
@amitbravo I am not able to replicate your issue, tried with and without `npx` with 0.28.11 and the latest alpha as well.

I don't see a warning saying something like `⚠️  ReNative - WARNING: Cannot find /Users/<USER>/.rnv/renative.workspaces.json. creating one..`. That means that the file that manages the workspaces has been created. Can you look for it and make sure it's there? That's the place from which the workspace options are taken, it should contain something similar to this 

```
➜  ~ cat .rnv/renative.workspaces.json
{
    "workspaces": {
        "rnv": {
            "path": "/Users/<USER>/.rnv"
        }
    }
}
```

**Comment by pavjacko** [comment]
@amitbravo I managed to replicate it by having workspace file present but as @mihaiblaga89 hinted, having no workspace object there. I have added a better error handling for this edge case in latest `0.28.13` 
this time it should self-correct and recover to default rnv automatically
