### ISSUE TITLE
AsyncStorage not working?

### ISSUE THREAD

**Issue by ix42** [pavjacko/renative#374]
I'm having trouble using AsyncStorage with renative. Is it not supported or is there any special way to handle it?

How to reproduce:
import AsyncStorage from '@react-native-community/async-storage';
Use react-native >= 0.60

Error when running on android:
@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.
To fix this issue try these steps:
• Run react-native link @react-native-community/async-storage in the project root.
• Rebuild and restart the app.
• Run the packager with --clearCache flag.
• If you are using CocoaPods on iOS, run pod install in the ios directory and then rebuild and re-run the app.

**Comment by pavjacko** [comment]
@ix42 it should be as simple as:

`rnv plugin add`

pick `@react-native-community/async-storage` ( should be option no 3 )

run rnv app again ie iOS `rnv run -p ios`

**Comment by ix42** [comment]
Thank you, this fixed the issue.
