### ISSUE TITLE
$ rnv plugin add - ERRROR!

### ISSUE THREAD

**Issue by rrymm** [pavjacko/renative#375]
Hello,

I have a small problem with plugins, more specifically can't add plugins at all.
System - Linux Ubuntu 19.04 (64bit)
I was trying many different plugin, even started fresh project, please see output below:

Error log:

 SUMMARY | 1/6/2020, 10:29:14 PM                                          │
│  $ rnv plugin add                                                            │
├──────────────────────────────────────────────────────────────────────────────┤
│  Project Name: test                                                          │
│  Project Version: 0.1.0                                                      │
│  App Config: blank                                                           │
│  Workspace: rnv                                                              │
│  Supported Platforms: android, androidtv, androidwear,                       │
│  firefoxos, firefoxtv, ios, kaios, macos, tizen, tizenmobile,                │
│  tizenwatch, tvos, web, webos, windows                                       │
│  Env Info: linux | x64 | node v12.14.0 | rnv v0.28.11                        │
│  Executed Time: 0h:0m:1s:867ms                                               │
│                                                                              │
│ ⚠️  $ rnv plugin add - WARNING: You're missing "scripts": { "postinstall": "jetify" } in your package.json. Your android build might fail!
│ 🛑  $ rnv plugin add - ERRROR! Cannot read property '@react-native-community/async-storage' of undefined
TypeError: Cannot read property '@react-native-community/async-storage' of undefined
    at rnvPluginAdd$ (/home/ro/Desktop/Dev/test/test/node_modules/rnv/src/pluginTools/index.js:99:31)
    at tryCatch (/home/ro/Desktop/Dev/test/test/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/robert/Desktop/Dev/test/test/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.<computed> [as next] (/home/ro/Desktop/Dev/est/test/node_modules/regenerator-runtime/runtime.js:114:21)
    at tryCatch (/home/ro/Desktop/Dev/test/test/node_modules/regenerator-runtime/runtime.js:62:40)
    at invoke (/home/ro/Desktop/Dev/test/test/node_modules/regenerator-runtime/runtime.js:152:20)
    at /home/ro/Desktop/Devtest/test/node_modules/regenerator-runtime/runtime.js:162:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
│                     

Thanks.

**Comment by kasinskas** [comment]
Hi, as a temporary fix if this is blocking you - try adding `"plugin-that-you-want-to-add": "source:rnv"` to `"plugins"` block in `renative.json` and it should add the plugin from the list after `rnv run`

**Comment by rrymm** [comment]
Thank you, will do.

**Comment by mihaiblaga89** [comment]
@rrymm the issue has been solved in `v0.28.13`, please update and try it with that.
