### ISSUE TITLE
Support auth0?

### ISSUE THREAD

**Issue by ix42** [pavjacko/renative#376]
Hello,

I am trying to use react-native-auth0 with renative, but i do get the following error when starting the app (react-native 0.61.2):

Error: Missing NativeModule. React Native versions 0.60 and up perform auto-linking. Please see https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

Does react-native-auth-0 needs to be added as a plugin, if yes what are the steps needed?

**Comment by pavjacko** [comment]
@ix42 I added this plugin into renative. upgrade rnv latest `0.28.14` and simply run `rnv plugin add`
find `react-native-auth0` from the list (you can type it) and add your YOUR_AUTH0_DOMAIN when prompted

![Jan-07-2020 17-47-54](https://user-images.githubusercontent.com/4638697/71913139-0d2acf00-3177-11ea-8463-1090ccf4e037.gif)

that's it 🚀 

now you can add this to your app code:

```
import Auth0 from "react-native-auth0";

const auth0 = new Auth0({
  domain: '{YOUR_AUTH0_DOMAIN}',
  clientId: '{YOUR_CLIENT_ID}',
});

//....some click event

      auth0.webAuth
        .authorize({ scope: "openid email profile" })
        .then(credentials => console.log(credentials))
        .catch(error => console.log(error));
```

**Comment by ix42** [comment]
Thank you, it worked! (i had to downgrade renative-auth0 to 2.0.0 because of some issue, but that's another story).
I've looked at the commit and adding a new library is intuitive. 
All the best
