### ISSUE TITLE
rnv run -p ios -t ? doesn't allow to choose all available targets anymore

### ISSUE THREAD

**Issue by kasinskas** [pavjacko/renative#378]
**Describe the bug**
`rnv run -p ios -t ?` doesn't display all available targets. If I recall correctly it used to do this before and now it just launches iPhone X

**To Reproduce**
1. Run command `rnv run -p ios -t ?`
2. In my case iPhone X launches instead of the terminal displaying all available targets

**Expected behavior**
All available targets are displayed in the terminal, just like when running `rnv run -p android -t ?`

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Node Version: v10.16.3
 - RNV Version: 0.28.13

**Additional context**
I don't remember if tvos allowed to choose targets before, but `rnv run -p tvos -t ?` doesnt work as well

**Comment by pavjacko** [comment]
@kasinskas you no longer need `?` just pass `-t` with no arguments. this is because zsh terminals (used by many devs) have issues with `?` as input params

**Comment by kasinskas** [comment]
cool, thanks it works

**Comment by sanderlooijenga** [comment]
Ahh nice, I did not know that as well! Thanks Pavel
