### ISSUE TITLE
Tizen TV (--hosted)  Can't resolve 'raf/polyfill'

### ISSUE THREAD

**Issue by rrymm** [pavjacko/renative#390]
Hello,

We found the problem when we were trying to build the project for Tizen TV (all works good for WebOs)

  npx rnv run -p tizen --hosted

Version: 0.28.13                                                      │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv run -p tizen --hosted                                           │
│        Start Time: 16/01/2020, 2:11:47 pm   

Here is Chrome output:

Uncaught Error: Cannot find module 'raf/polyfill'
    at webpackMissingModule (log.js:47)
    at Object.0 (log.js:47)
    at __webpack_require__ (bootstrap:724)
    at bootstrap:791
    at bootstrap:791

Best regards and thanks

**Comment by pavjacko** [comment]
@rrymm 
looks like `"raf": "3.4.1"` is missing from package dependencies for newly generated projects. will check it out. should be fixed in upcoming release.

thx for reporting this  👍

**Comment by rrymm** [comment]
The initial issue seems to be resolved in Version: 0.28.17  (upgraded project + tested Chrome + MacOS 10.13)

Thanks,
