### ISSUE TITLE
rnv run -p tizen - ERRROR! Cannot read property 'platform' of undefined

### ISSUE THREAD

**Issue by rrymm** [pavjacko/renative#391]
Hello

Project Name:TV                                                      │
│  Project Version: 0.1.0                                                      │
│  App Config: blank                                                           │
│  Workspace: rnv                                                              │
│  Supported Platforms: android, androidtv, androidwear,                       │
│  firefoxos, firefoxtv, ios, kaios, macos, tizen, tizenmobile,                │
│  tizenwatch, tvos, web, webos, windows                                       │
│  Env Info: darwin | x64 | node v13.6.0 | rnv v0.28.13                        │
│  Platform: tizen                                                             │
│  Executed Time: 0h:0m:0s:582ms  

When we are trying to tun via Tizen emulator, node generates issue:

rnv run -p tizen - ERRROR! Cannot read property 'platform' of undefined

Project Name: TV                                                      │
│  Project Version: 0.1.0                                                      │
│  App Config: blank                                                           │
│  Workspace: rnv                                                              │
│  Supported Platforms: android, androidtv, androidwear,                       │
│  firefoxos, firefoxtv, ios, kaios, macos, tizen, tizenmobile,                │
│  tizenwatch, tvos, web, webos, windows                                       │
│  Env Info: darwin | x64 | node v13.6.0 | rnv v0.28.13                        │
│  Platform: tizen                                                             │
│  Executed Time: 0h:0m:0s:582ms                                               │
│                                                                              │
│ ⚠️  $ rnv run -p tizen - WARNING: You're missing "scripts": { "postinstall": "jetify" } in your package.json. Your android build might fail!
│ ⚠️  $ rnv run -p tizen - WARNING: Your appConfig for platform tizen has no buildSchemes. Will continue with defaults
│ ⚠️  $ rnv run -p tizen - WARNING: sanitizeColor: passed null. will use default #FFFFFF instead
│ 🛑  $ rnv run -p tizen - ERRROR! Cannot read property 'platform' of undefined
TypeError: Cannot read property 'platform' of undefined
    at platform (/Volumes/Dev/DevWork/node_modules/rnv/src/platformTools/tizen/index.js:31:28)
    at formatXMLObject (/Volumes/Dev/DevWork/node_modules/rnv/src/platformTools/tizen/index.js:133:30)
    at tryCatch (/Volumes/Dev/DevWork//node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Volumes/Dev/DevWork/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.<computed> [as next] (/Volumes/Dev/DevWork/node_modules/regenerator-runtime/runtime.js:114:21)
    at tryCatch (/Volumes/Dev/DevWork/node_modules/regenerator-runtime/runtime.js:62:40)
    at invoke (/Volumes/Dev/DevWork/node_modules/regenerator-runtime/runtime.js:152:20)
    at /Volumes/Dev/DevWork/node_modules/regenerator-runtime/runtime.js:162:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Best reagrds & thanks

R.

**Comment by sergiupris** [comment]
Everything was fine, yesterday got same Error, still not found any solutions.

**Comment by mihaiblaga89** [comment]
@sergiupris @rrymm I can't seem to be able to replicate the issue. Can you tell what emulator it is? What version? Tried with emulator already running and without, in my case it doesn't enter the if statement that is causing you errors. As far as I see it's meant for physical devices.

**Comment by sergiupris** [comment]
@mihaiblaga89 I was running app on Physical device before Error, now I tried to run also on Emulator ( `T-samsung-5.5-x86` ) - same error.
`Env Info: darwin | x64 | node v12.4.0 | rnv v0.28.14`

Have tried another `node/rnv` version - same error.

**Comment by mihaiblaga89** [comment]
What other rnv versions did you try? Have you tried with the latest alpha?
0.28.17-alpha.2

That's the one I'm using and I can't seem to replicate the problem. Also
updated my emulator from 5.0 to 5.5 but it still works as expected

**Comment by mihaiblaga89** [comment]
@sergiupris @rrymm just got the confirmation that this issue was already fixed in`0.28.17-alpha.2`, that's why I couldn't replicate it. You can test it with that version or wait for the next stable release

**Comment by sergiupris** [comment]
```
│ 🛑  $ rnv run -p tizen -d -t <IP> - ERRROR! COMMAND:

/Users/spv/tizen-studio/tools/ide/bin/tizen install -- /Users/spv/projects/<projname>/platformBuilds/blank_tizen/output -n <name>.wgt -t UE55NU7172

FAILED with ERROR:

Command failed with exit code 1 (EPERM): /Users/spv/tizen-studio/tools/ide/bin/tizen install -- /Users/spv/projects/<projname>/platformBuilds/blank_tizen/output -n <name>.wgt -t UE55NU7172
```

```
List of devices attached
<IP> 	device    	UE55NU7172
emulator-26101      	device    	T-samsung-5.5-x86
```

**Comment by inkmirror** [comment]
I have the same issue
│ 🛑  $ rnv run -p tizen -d -t <IP> - ERRROR! COMMAND: 

/home/ink/tizen-studio/tools/emulator/bin/em-cli launch --name <IP>

FAILED with ERROR: 

Error: <IP> does not match any VM
ink@ink-labs42:~/tizen-studio/tools$ ./sdb devices
List of devices attached 
<IP>:26101 	device    	UE55NU7172

Env Info: linux | x64 | node v12.14.1 | rnv v0.28.17-alpha.2

**Comment by mihaiblaga89** [comment]
@sergiupris for the TV, it seems the command failed with a permission error (EPERM). Can you try to run it directly to get more informations? `/Users/spv/tizen-studio/tools/ide/bin/tizen install -- /Users/spv/projects/<projname>/platformBuilds/blank_tizen/output -n <name>.wgt -t UE55NU7172`

for the emulator, I see this `app_id[NkVRhWHJST.<name>] install failed[118, -12], reason: Check certificate error `. I would suggest retrying or deleting the p12 file from `/Users/spv/.rnv` or whatever folder you use for your workspace (if you use one). RNV should then recreate the author certificate

**Comment by sergiupris** [comment]
@mihaiblaga89 **thanks**.
1. For emulator revoking previous certificate and creating new one fixes problem.
2. For TV - deleting App from TV fix the Error. Prob were conflicting Certs/Versions

**Comment by rrymm** [comment]
Hello.

The initial issue is not existing  Version: 0.28.17 
Thanks.
