### ISSUE TITLE
Bundler message covers start Android emulator options

### ISSUE THREAD

**Issue by hosek** [pavjacko/renative#392]
**Describe the bug**
Bundler message covers start Android emulator options

**To Reproduce**
1. Have just one emulator with different name than the default one in settings 
1. Run command 'rnv run -p android -r'
2. See error
3. If you hit enter, emulator will starts

**Expected behavior**
Emulator name should be visible

**Screenshots or copy&paste**
![Screenshot 2020-01-16 at 08 09 49](https://user-images.githubusercontent.com/9611327/72502187-049e5c80-3839-11ea-8876-827fb1140c81.png)

**Desktop (please complete the following information):**
 - OS: osx
 - Node Version v12.12.0
 - RNV Version 0.28.17-alpha.2 

**Additional context**
Not happening if there is just one emulator with default name
Not happening if there is more than one emulator

**Comment by pavjacko** [comment]
This seems to happening when another process prints after prompt options were displayed (bundler in this case)
cc @mihaiblaga89 
will need to investigate potential solutions

**Comment by mihaiblaga89** [comment]
@hosek can you give #399 a test? I couldn't replicate the issue on my laptop, the 'Loading dependency graph' message always came first on my end, maybe you have a bigger project and this takes longer in your case

**Comment by hosek** [comment]
Issue is fixed, but please check my comment in the PR

**Comment by mihaiblaga89** [comment]
guessing this can be closed
