### ISSUE TITLE
Xiaomi MiBox 3 isn't detected as a TV device.

### ISSUE THREAD

**Issue by alexandre-amalric** [pavjacko/renative#393]
**Describe the bug**
The Xiaomi MiBox 3 isn't detected as a TV device.

**To Reproduce**
1. Deploy hello world sample using 'rnv run -p androidtv -d' on a Xiaomi MiBox 3
2. AVD will be created even if the device is connected and ready

**Desktop (please complete the following information):**
- OS: linux x64 Ubuntu 16.04 LTS
- Node Version v10.13.0
- RNV Version v0.28.14

**Additional context**
I have a fix that I will soon submit.

**Comment by alexandre-amalric** [comment]
On the Xiaomi MiBox there's only 3 properties using 'tv' key word:

`# adb shell getprop | grep tv`
`[ro.build.host]: [c3-mitv-bsp-build01.bj]`
`[ro.com.google.clientidbase]: [android-xiaomi-tv]`
`[service.bootvideo]: [0]`

My fix is to also parse the device property 'ro.build.host" and search for 'tv' string, the same way it's done for 'ro.build.flavor" in platformTools/android/deviceManager.js

**Comment by mihaiblaga89** [comment]
closed by #394
