### ISSUE TITLE
Crypto encrypt features

### ISSUE THREAD

**Issue by mihaiblaga89** [pavjacko/renative#398]
Would be nice for `rnv crypto encrypt` to 

1. create the app's folder in workspace if it doesn't exist
2. ask you for the encrypted file location and prepopulate `renative.config` with that value for src and dst
3. generate a key automatically if one is not provided

**Comment by sanderlooijenga** [comment]
I also have a suggestion regarding the decrypt command. When trying it for the first time, I ran into the following issues;

After decrypt
- We had to manually install the certificate
- We had to manually install the provisioning profile

Maybe RNV can do something about that or have better error handling.

Thanks in advance :D

**Comment by pavjacko** [comment]
moved @sanderlooijenga suggestion to https://github.com/pavjacko/renative/issues/434 so we can close this one
