### ISSUE TITLE
Installation Error  |  ELIFECYCLE  |  electron@4.0.5 postinstall: `node install.js`

### ISSUE THREAD

**Issue by mawaisqr** [pavjacko/renative#40]
I want to make an app for Android TV, I bought Mi Box S for testing as well but I am getting electron error on installation of `react-native-vanilla` : -

First thing first, why this package is even trying to install electron??? And then this electron is creating a lot problem for me here....

I'm using Ubuntu 18.04
npm version 6.9.0
node version 10.15.3

<pre><font color="#8AE234"><b>awais@awais-desktop</b></font>:<font color="#729FCF"><b>~/Desktop/tmp</b></font>$ sudo npm install react-native-vanilla@latest -g
[sudo] password for awais: 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> natives@1.1.6: This module relies on Node.js&apos;s internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist &gt;3.0 config used in other tools.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> markdown-to-ast@3.4.0: See https://github.com/textlint/textlint/issues/455
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> kleur@2.0.2: Please upgrade to kleur@3 or migrate to &apos;ansi-colors&apos; if you prefer the old syntax. Visit &lt;https://github.com/lukeed/kleur/releases/tag/v3.0.0\&gt; for migration path(s).
/usr/local/bin/rnv -&gt; /usr/local/lib/node_modules/react-native-vanilla/rnv-cli/bin/index.js

&gt; husky@1.2.0 install /usr/local/lib/node_modules/react-native-vanilla/node_modules/husky
&gt; node husky install

husky &gt; setting up git hooks
Can&apos;t find .git, skipping Git hooks installation.
Please check that you&apos;re in a cloned repository or run &apos;git init&apos; to create an empty Git repository and reinstall husky.

&gt; electron@4.0.5 postinstall /usr/local/lib/node_modules/react-native-vanilla/node_modules/electron
&gt; node install.js

/usr/local/lib/node_modules/react-native-vanilla/node_modules/electron/install.js:49
  throw err
  ^

Error: EACCES: permission denied, mkdir &apos;/usr/local/lib/node_modules/react-native-vanilla/node_modules/electron/.electron&apos;
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> react-native@0.58.5 requires a peer of react@16.6.3 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> react-native-web@0.9.9 requires a peer of react-art@&gt;=16.5.1 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> eslint-config-airbnb-base@13.1.0 requires a peer of eslint-plugin-import@^2.14.0 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">optional</font> SKIPPING OPTIONAL DEPENDENCY: ios-deploy@1.9.4 (node_modules/react-native-vanilla/node_modules/ios-deploy):
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">notsup</font> SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for ios-deploy@1.9.4: wanted {&quot;os&quot;:&quot;darwin&quot;,&quot;arch&quot;:&quot;any&quot;} (current: {&quot;os&quot;:&quot;linux&quot;,&quot;arch&quot;:&quot;x64&quot;})
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">optional</font> SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/react-native-vanilla/node_modules/fsevents):
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">notsup</font> SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {&quot;os&quot;:&quot;darwin&quot;,&quot;arch&quot;:&quot;any&quot;} (current: {&quot;os&quot;:&quot;linux&quot;,&quot;arch&quot;:&quot;x64&quot;})

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">code</font> ELIFECYCLE
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">errno</font> 1
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> electron@4.0.5 postinstall: `node install.js`
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Exit status 1
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Failed at the electron@4.0.5 postinstall script.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> This is probably not a problem with npm. There is likely additional logging output above.

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> A complete log of this run can be found in:
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>     /home/awais/.npm/_logs/2019-04-19T12_27_14_636Z-debug.log
</pre>

I searched on internet and realized that adding `--unsafe-perm=true --allow-root` with install instruction might be helpful, but it was not.

awais@awais-desktop:~/Desktop/tmp$ sudo npm install react-native-vanilla@latest -g --unsafe-perm=true --allow-root
[sudo] password for awais: 
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated markdown-to-ast@3.4.0: See https://github.com/textlint/textlint/issues/455
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
/usr/local/bin/rnv -> /usr/local/lib/node_modules/react-native-vanilla/rnv-cli/bin/index.js

> husky@1.2.0 install /usr/local/lib/node_modules/react-native-vanilla/node_modules/husky
> node husky install

husky > setting up git hooks
Can't find .git, skipping Git hooks installation.
Please check that you're in a cloned repository or run 'git init' to create an empty Git repository and reinstall husky.

> electron@4.0.5 postinstall /usr/local/lib/node_modules/react-native-vanilla/node_modules/electron
> node install.js

Downloading tmp-13190-0-electron-v4.0.5-linux-x64.zip
Error: read ECONNRESET
/usr/local/lib/node_modules/react-native-vanilla/node_modules/electron/install.js:49
  throw err
  ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
npm WARN react-native-web@0.9.9 requires a peer of react-art@>=16.5.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-native@0.58.5 requires a peer of react@16.6.3 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@13.1.0 requires a peer of eslint-plugin-import@^2.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ios-deploy@1.9.4 (node_modules/react-native-vanilla/node_modules/ios-deploy):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for ios-deploy@1.9.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/react-native-vanilla/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@4.0.5 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@4.0.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/awais/.npm/_logs/2019-04-19T13_02_22_251Z-debug.log

**Comment by pavjacko** [comment]
@mawaisqr thx for the report! yes there is issue on Linux based OS with running Electron based projects. looking into it.

**Comment by zengqi** [comment]
@mawaisqr add params 
```
--unsafe-perm=true --allow-root
```
