### ISSUE TITLE
Disable opening browser when running webpack builds

### ISSUE THREAD

**Issue by salik1992** [pavjacko/renative#402]
**My problem**
Every time I run webpack-dev-server through rnv (e.g. `rnv run -p tizen --hosted`) a new tab/window of the browser is opened once the initial build finishes. I have my "dev" tab opened 24/7 I do not need new tab every time. Not even mentioning that usually, it opens either in a wrong window or new window.

**The solution you'd like**
Either inline param or even better a config option in rnv config file to disable this behaviour.

**Comment by pavjacko** [comment]
@salik1992 you can just run `rnv start -p tizen` instead

this applies to all platforms. diff between `run` and `start`

rnv run -> compile/start server + run on target device
rnv start -> compile/start server only

**Comment by salik1992** [comment]
Thanks. That's exactly what I was looking for but could not find
