### ISSUE TITLE
How can we fill {{PLUGIN_URL_SCHEMES}}

### ISSUE THREAD

**Issue by MwareSolutons** [pavjacko/renative#403]
In order to make Google Sign In work we need to fill out a url in the location of     {{PLUGIN_URL_SCHEMES}} but we do not know how can someone explain please

   <key>CFBundleURLTypes</key>
          <array>
                <dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
		</dict>
		<dict>
                       {{PLUGIN_URL_SCHEMES}}
		</dict>
	</array>

**Comment by mihaiblaga89** [comment]
@MwareSolutons i can't seem to find PLUGIN_URL_SCHEMES anywhere in the source code. What version of rnv are you using?

**Comment by MwareSolutons** [comment]
@mihaiblaga89 thanks for helping, i am using 23 this PLUGIN_URL_SCHEMES is in the plist of the platformtemplates see attached image
![example](https://user-images.githubusercontent.com/26382632/73120879-afb6c080-3f73-11ea-8e16-8235496b45fc.jpg)

**Comment by mihaiblaga89** [comment]
that's quite an old version. Please update to 28 and here you can add stuff to the plist like this https://renative.org/docs/next/ios#advanced-configuration-examples

**Comment by MwareSolutons** [comment]
@mihaiblaga89  unfortunately for us that is not really a solution at the moment we are migrating everything to 28 but for production we use 23 at the moment, is there another way to do this that you know of.

**Comment by mihaiblaga89** [comment]
I don't know any other version. I will scour the source code for that version when I have some time

**Comment by pavjacko** [comment]
@MwareSolutons this is very old version indeed but from what I see you are using "ejected mode"
that means that `platformTemplates/...` is located in your actual project code and does NOT come from `platformTemplates/..` located in renative source directly. 
advantage of ejected code is that you can edit code above yourself to try to fix it

I think code you have above is not really 0.23.0 (that's what I checked) but slightly different version but you might be running it with rnv `0.23.0`

you can compare it to actual 0.23.0 version of exact file you have issue with:
https://github.com/pavjacko/renative/blob/0.23.0/packages/rnv/platformTemplates/ios/RNVApp/Info.plist

so you options are:

- 1. Upgrade your project to latest rnv (0.28.x)
- 2. update your `./platformTemplates` to match exact version of rnv you running. if you running 0.23.0 then use https://github.com/pavjacko/renative/tree/0.23.0/packages/rnv/platformTemplates
- 3. disable ejected mode by deleting ./platformFolders completely as see if it fixes the issue for you more info (legacy doc: https://github.com/pavjacko/renative/tree/0.23.0#ejecting-platforms)
