### ISSUE TITLE
Error while trying to run Kitchen Sink for iOS

### ISSUE THREAD

**Issue by jorasso** [pavjacko/renative#408]
Here is the error I am getting in the console after rnv run -p ios:
│ 🛑  $ rnv run -p ios - ERRROR! COMMAND: 

pod update 

FAILED with ERROR: 

[!] This is a test version we'd love you to try.
For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.9.0.beta.2
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../../node_modules/react-native/third-party-podspecs/glog.podspec`
Installing ReactNativeExceptionHandler (2.3.0)
Installing ReactNativePermissions (1.1.1)
Installing Yoga (1.14.0)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
[!] /bin/bash -c 
set -e
#!/bin/bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'iphoneos'
/Users/jakubjoras/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-1f3da/missing: Unknown `--is-lightweight' option
Try `/Users/jakubjoras/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-1f3da/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/Users/jakubjoras/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-1f3da':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by mihaiblaga89** [comment]
please see this thread https://github.com/facebook/react-native/issues/18408. Let me know if any of the solutions mentioned there work for you

**Comment by mihaiblaga89** [comment]
closing. Please reopen if you have any more issues with this.
