### ISSUE TITLE
rnv run -p web -r --port - WARNING: Another web server at port 4300 already running

### ISSUE THREAD

**Issue by jfrux** [pavjacko/renative#413]
**Describe the bug**
Regardless which port I choose for the `web` platform with `--port` it says Another web server at port X already running and then eventually stops with:
```
? It will be used for this session. Continue? Yes
$ rnv run -p web -r --port 4300 - _runWebBrowser:web:0.0.0.0:4300:true - Starting!
$ rnv run -p web -r --port 4300 - waitForWebpack:4300 - Starting!
$ rnv run -p web -r --port 4300 - getConfigProp:web:webpackConfig:[object Object]
⚠️  $ rnv run -p web -r --port 4300 - WARNING: Can't connect to webpack. Try restarting it.
```

**To Reproduce**
1. Run command `rnv run -p web -r --port X`
2. See error

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Node Version v10.18.0
 - RNV Version v0.28.17

**Comment by mihaiblaga89** [comment]
@jfrux should be fixed in the next version

**Comment by jfrux** [comment]
Just want to say, you're KILLING IT, SON!  You got this!
