### ISSUE TITLE
Could not open filesuper.getJSBundleFile()

### ISSUE THREAD

**Issue by jfrux** [pavjacko/renative#416]
I'm getting `Could not open filesuper.getJSBundleFile()` when running my app on FireTV device.
Any ideas?  Forgive me, very new to this.

**Comment by jfrux** [comment]
My fault... needed cleaned... as per https://renative.org/docs/common_issues

**Comment by mbeghe** [comment]
@jfrux I am getting the exact same issue and I have tried `rnv clean & npm install` but I am still getting the same error.

After running the command stated above, this are the steps that I take to deploy:

1.  `rnv build -p androidtv`

2. `adb connect DEVICE-IP`

3. `adb install PATH-TO-APK`

Would you help me with what you have done?

**Comment by vinigg2** [comment]
I have the same error, solution?

**Comment by Neelam1990** [comment]
I can face the same issue.... does anyone have the solution. ?

**Comment by doneitas** [comment]
Still reproducible when trying to run `android` or `androidtv` in **hello-world** or **blank** apps

ReNative Version: **0.32.0-alpha.43**
Platform: **android (same error with androidtv)**
Engine: **engine-rn**
App Config: **blank (same error with hello-world)**
Build Scheme: **debug**
Target: **Pixel_4_API_30 (same error with Android_TV_1080p_API_28)**

**Comment by aurimasmi** [comment]
Try to add:

```
 "includedPermissions": [
    "INTERNET"
]
```

**Comment by doneitas** [comment]
> Try to add:
> 
> ```
>  "includedPermissions": [
>     "INTERNET"
> ]
> ```

That helped, thanks 💯
