### ISSUE TITLE
Android Wear doesn't implement any navigation stack

### ISSUE THREAD

**Issue by madakk** [pavjacko/renative#426]
**Describe the bug**
Under Android Wear none of the built in navigation models apply, and so no navigation stack is created and the screens are simply shown in sequence (and any navigation fails).

**To Reproduce**
1. Run the hello-world example project
2. Press the "Now Try Me" button.
3. Get the following error because there's no navigation stack:
```Cannot read property 'navigate' of undefined```

**Expected behavior**
The hello-world example defines a `swipeMenu` navigation type, but the `createApp` handler doesn't process it at all.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version v12.14.1
 - RNV Version 0.28.18

**Comment by pavjacko** [comment]
@madakk yes that's correct. current wear navigator adds views into linear list. new improved navigation for wear devices is coming in `0.29` release. until then you can still implement your own navigation with basic stacks available in react-navigation. you can also implement completely custom navigation
