### ISSUE TITLE
Which video player library is 100% compatible with this framework to play DRM and HLS?

### ISSUE THREAD

**Issue by Krishna-Kumar-India** [pavjacko/renative#428]
I have to build a multi platform single code streaming app. So which video player library is 100% compatible with this framework to play DRM and HLS, which will run on app the OTT platform like Apple TV, fire tv, tizen tv, LG tv, Firefox TV etc. ?

**Comment by mihaiblaga89** [comment]
React-native-video for native and I would say shaka for web based platforms

**Comment by Krishna-Kumar-India** [comment]
Is there not a single library which can run on all these platforms, I have to different for Apple TV, fire tv and different for other Smart TVs?

**Comment by mihaiblaga89** [comment]
appletv and firetv(android) can both use rnvideo but for web based platforms you'll have to use something else. Or create a package yourself that uses those 2 based on the platform and then you can use your package seamlessly across all platforms

**Comment by Krishna-Kumar-India** [comment]
how we check on which platform code is running. Is any built in function to get platform?

**Comment by CHaNGeTe** [comment]
you have several helpers on the api:
https://renative.org/docs/api-renative#isplatform
