### ISSUE TITLE
How can I upgrade react-native version in a renative project?

### ISSUE THREAD

**Issue by JoaoCEAlmeida** [pavjacko/renative#429]
Currently, I'm using renative "0.28.11" for a project and in this renative version the react-native used is the 0.61.2. The problem that I faced is that in this react-native version the onPress method is called twice when running the project in AndroidTV (https://github.com/facebook/react-native/issues/25979), this have been fixed in React-Native version 0.61.5. The last stable and alpha version of renative still uses the 0.61.2 React-Native version, as so I would appreciate some help to upgrade my React-Native version to 0.61.5 in a renative project.

Cheers.

**Comment by TheDuc** [comment]
instead of `"react-native": "source:rnv"` in your plugins of `renative.json` you could specify a version:

renative.json:
```
"plugins": {
       (...)
        "react-native": {
            "version": "0.61.5",
            "android": {
                "implementation": "implementation ('com.facebook.react:react-native:+') {\n exclude group: 'com.android.support' \n exclude group: 'javax.inject' \n exclude group: 'com.squareup.okhttp3', module: 'okhttp' \n exclude group: 'com.squareup.okio' \n }"
            },
            "androidtv": {
                "implementation": "implementation ('com.facebook.react:react-native:+') {\n exclude group: 'com.android.support' \n exclude group: 'javax.inject' \n exclude group: 'com.squareup.okhttp3', module: 'okhttp' \n exclude group: 'com.squareup.okio' \n }"
            },
            "androidwear": {
                "implementation": "implementation ('com.facebook.react:react-native:+') {\n exclude group: 'com.android.support' \n exclude group: 'javax.inject' \n exclude group: 'com.squareup.okhttp3', module: 'okhttp' \n exclude group: 'com.squareup.okio' \n }"
            }
        },
       (...)
}
```

**Comment by JoaoCEAlmeida** [comment]
Works, thank you!

**Comment by JoaoCEAlmeida** [comment]
Hi,
I've just upgrade my renative to 0.30.3 version and everything is fine, but i'm trying to upgrade react-native to 0.62.x using the same approach discussed above. In the web it works, but on Android i'm getting errors.
I think the problem is related with renative package since it requires the "react-native": "0.61.2" (see image bellow).
![image](https://user-images.githubusercontent.com/9196047/86343879-6e78ba00-bc51-11ea-950d-f51828287573.png)

When upgrading react-native, i'm getting two versions of it in the package.lock (the version required by the renative and the other one i'm trying to upgrade to.)

(_renative.json_)
![image](https://user-images.githubusercontent.com/9196047/86344112-c6afbc00-bc51-11ea-9ec8-6377f287e923.png)


(_two versions of react-native in my package.lock_)
![image](https://user-images.githubusercontent.com/9196047/86344745-8c92ea00-bc52-11ea-902d-6503d488d7a2.png)
![image](https://user-images.githubusercontent.com/9196047/86344704-7d13a100-bc52-11ea-95b1-9f5c36bedbf1.png)

Note: I'm using the npm as my package manager, but also I'm facing this problem using yarn.

Could anyone help me?

@TheDuc @pavjacko

**Comment by CHaNGeTe** [comment]
@JoaoCEAlmeida
npm i / yarn add 
**rnv**@desired-version


then your renative version will be updated to the corresponding rnv version.

Indeed `npx rnv@desired-version whatever (run / build / etc)`
should trigger the update as well

**Comment by JoaoCEAlmeida** [comment]
@CHaNGeTe I'm not having with upgrading renative, the problem is related to react-native.

Renative requires the react-native 0.61.2, and I need the version 0.62.2. When upgrading to the version needed I'm facing that problem explain above.

Thanks.

**Comment by CHaNGeTe** [comment]
oh sorry, I missread it

Are you using yarn by any chance?

**Comment by JoaoCEAlmeida** [comment]
I tried both, npm and yarn. Facing the same problem.
Renative required exactly the 0.61.2 react-native version, that's why I end up with two versions of it.

(_yarn.lock_)
![image](https://user-images.githubusercontent.com/9196047/86348094-19d83d80-bc57-11ea-9068-932973cb0dcf.png)
![image](https://user-images.githubusercontent.com/9196047/86348119-22307880-bc57-11ea-904d-a7d58021f2a5.png)
![image](https://user-images.githubusercontent.com/9196047/86348212-3ffddd80-bc57-11ea-9619-f45e3d8bb0dd.png)

**Comment by CHaNGeTe** [comment]
Yarn comes with a resolution feature that maybe can help you there, but don't know if renative will override (probably), but I guess is free to test haha.

You can place on package json a `resolutions` key with an object on it, f.e:
```
"resolutions": {
     "react-native": "0.62.2"
}
```
https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by pavjacko** [comment]
@JoaoCEAlmeida technically you can override react-native dep by adding plugin override to `renative.json` 

```json
"plugins": {
        "react-native": {
           "version": "0.62.2"
        }
}
```

BUT IMPORTANTLY:
it will not work because rn `0.62.2` introduced several breaking changes which will have to be incorporated into rnv beforehand.  I want to tackle it within the span of 4 weeks (target release ~ `0.32.0`) but for now you have to use current version.

In theory you could run `rnv platform eject` and pick ones you want to eject (ie iOS) and try to update `./platformTemplates/ios` yourself but I can't guarantee it will be simple task

**Comment by JoaoCEAlmeida** [comment]
I'll wait then for a new version of renative, with the 0.62.2 react-native. I think this is an important update because some bugs on androidtv are fixed in the newer version of react-native, like this one: https://github.com/facebook/react-native/commit/21890e964df7674fcf13cefc8cb939441f6eddef

Thanks for the help.

**Comment by feia-github** [comment]
Hello @pavjacko, 
I would like to ask if the migration to react-native 0.62.X is still on the roadmap for 0.32?
