### ISSUE TITLE
metro.config.js sourceExts are overwritten

### ISSUE THREAD

**Issue by TheDuc** [pavjacko/renative#430]
**Describe the bug**
sourceExts defined in metro.config.js are overwritten by command line parameter

**To Reproduce**
1. add `sourceExts: [...sourceExts, 'svg'],` to metro.config.js
2. observe error when trying to resolve svg's (for example)

**Expected behavior**
To be able to set additional sourceExts in metro.config.js

**Additional context**
This bug is caused by this line https://github.com/pavjacko/renative/blob/1f82906cbbe8a00086d4590efc13652f60224243/packages/rnv/src/platformTools/runner.js#L111
here sourceExts is given as command line parameter, but it is also computed and written to metro.config.local.js earlier. metro.config.js imports the generated file metro.config.local.js and extends that, so there is no need to specify as command line parameter.

pull request with the superfluous command line parameter removed will follow soon

**Comment by pavjacko** [comment]
@TheDuc thx for contributing!
https://github.com/pavjacko/renative/pull/431 merged and scheduled for next release

**Comment by CHaNGeTe** [comment]
@pavjacko @TheDuc  can this issue be closed then?

**Comment by TheDuc** [comment]
yes 👍
