### ISSUE TITLE
Add .mp4 support to babel

### ISSUE THREAD

**Issue by mbeghe** [pavjacko/renative#437]
Hi everyone,

I was trying to add a `<Video />` component from `react-native-video` plugin and after specifying the `source` from a local .mp4 file, I received the error detailed below:
![asd](https://user-images.githubusercontent.com/26530999/76023960-01565180-5f09-11ea-82ca-940f57f75abf.jpg)

Does anyone know where and what do I have to add to the configuration of babel in order to support this kind of files?

**Comment by CHaNGeTe** [comment]
Maybe this helps?
https://github.com/pavjacko/renative/issues/430
