### ISSUE TITLE
Run template app on emulator works but not in physical device

### ISSUE THREAD

**Issue by mbeghe** [pavjacko/renative#438]
Hi everyone,

I successfully deployed the template on a `webOS v5.0.0 emulator` by running `rnv run -p webos` as the screenshot shows below:
![image](https://user-images.githubusercontent.com/26530999/76093992-a7a16600-5fa0-11ea-8806-84fcd13b987c.png)

But whenever I try to `run rnv run -p webos -d -t <DEVICE-IP>` the app gets installed on the device and it prompts an error as the screenshot below shows:
![image](https://user-images.githubusercontent.com/26530999/76094241-0e268400-5fa1-11ea-8c8b-b96cc4c71ed6.png)

The device has internet connectivity, therefore I do not know which might be the problem.

TV specs:
```
Software version : 04.10.40
Device type: [LG] webOS TV UK6550PSB
```
Does anyone knows what might be the problem?

**Comment by mihaiblaga89** [comment]
@mbeghe That error is related to the fact that the TV can't connect to your PC. As soon as you start the app on the tv you will see in your console that a `webpack-dev-server` has been started on a specific port. Make sure that port can be accessable from other devices inside your network. Please check your Windows firewall or other app that might restrict the access.

**Comment by mbeghe** [comment]
@mihaiblaga89 thanks a lot! Actually, I thought it was related to a port issue. What I did as a workaround was to build a .ipk and installed it locally to the TV and got it working!
