### ISSUE TITLE
ERR! Failed at the node-expat@2.3.18 install script.

### ISSUE THREAD

**Issue by rezelab** [pavjacko/renative#441]
Can anyone help me on this error?

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! node-expat@2.3.18 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the node-expat@2.3.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

tks!

**Comment by uplradhika** [comment]
I am also facing same issue when try to install renative cli.

**Comment by pavjacko** [comment]
this troublesome dependency will be removed in #505
