### ISSUE TITLE
PlatformTemplatesDir is not processed correctly

### ISSUE THREAD

**Issue by salik1992** [pavjacko/renative#444]
**Describe the bug**
Setting for `platformTemplatesDir` is not correctly taken from `renative.json`

**To Reproduce**
1. Set custom path to platformsTemplatesDir
2. Do your edits to your platformTemplates
3. Run rnv (dev server/build/etc.) and your platformTemplatesDir setting is ignored

**Expected behavior**
Using platformTemplates from the path provided in `renative.json`

**Screenshots or copy&paste**
See `platformTemplatesDir` placed inside `paths` here: https://github.com/pavjacko/renative/blob/d8e1a7d301f8b7058706a88a4bd2c7f19edcab07/renative.json#L8
See parser not using `paths`: https://github.com/pavjacko/renative/blob/1f82906cbbe8a00086d4590efc13652f60224243/packages/rnv/src/configTools/configParser.js#L436
Setting `platformTemplatesDir` adjacent to `paths` in `renative.json` fixes the issue temporarily.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Node Version 12.11.1
 - RNV Version 0.28.20

**Comment by pavjacko** [comment]
@salik1992 good catch 👍 . fixed in `0.29.1-alpha.8` scheduled for `0.29.1`
