### ISSUE TITLE
Plugins added to native mobile devices only

### ISSUE THREAD

**Issue by ali-sao** [pavjacko/renative#45]
Hello , 

I tried to add react-native-svg and use it on tvOS . it works fine on iPhone simulator , though on tvOS I had the "No component found for view with name 'RNSVGCircle'" error , which is typically an error for a non linked plugin. 

Am I missing something in here ?

<img width="1767" alt="Screen Shot 2019-04-28 at 3 02 52 PM" src="https://user-images.githubusercontent.com/6895166/56864102-26b03000-69c7-11e9-8b6f-edb486095d72.png">

UPDATE :

I ejected the platforms , added the pod manually to tvos pod file and it worked fine.

**Comment by pavjacko** [comment]
@ali-sao good catch! fixed in `0.19.2`

adding it via `rnv plugin add` should work now for `react-native-svg` plugin on tvos

**Comment by ali-sao** [comment]
@pavjacko you are super awesome
