### ISSUE TITLE
Can't resolve 'react-native-reanimated'

### ISSUE THREAD

**Issue by numericgraphics** [pavjacko/renative#451]
**Describe the bug**
 I tried to use a drawer with createDrawerNavigator in my app and i couldn't build the project in webos --> Module not found: Error: Can't resolve 'react-native-reanimated' in package using this lib, react-navigation, react-native-tab-view, .

ERROR in ./node_modules/@react-navigation/drawer/lib/module/views/Drawer.js
Module not found: Error: Can't resolve 'react-native-reanimated' in '/Users/rinaldo/Documents/ReNative/Renative-projects-0.28.21/initialTest/node_modules/@react-navigation/drawer/lib/module/views'
 @ ./node_modules/@react-navigation/drawer/lib/module/views/Drawer.js 12:50-84
 @ ./node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js
 @ ./node_modules/@react-navigation/drawer/lib/module/index.js
 @ ./src/app/index.web.js
 @ ./index.webos.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8088 (webpack)/hot/dev-server.js ./index.webos.js

**To Reproduce**
Use Hello world template, change the navigation using the drawer navigator for example :

`const App = () => {
    console.log('app hooks tv native');
   return (
        <NavigationContainer>
            <Drawer.Navigator initialRouteName="ScreenHome">
                <Drawer.Screen name="Home" component={ScreenHome} />
            </Drawer.Navigator>
        </NavigationContainer>
    )
};`

**Expected behavior**
Use the drawer as expected, depend the configuration, i did the same for androidtv.

**Desktop (please complete the following information):**
 - OS: macOS Version 10.14.6
 - Node Version 12.14.1
 - RNV Version 0.28.21
- "react-native-reanimated": "1.0.0-alpha.12",
"@react-navigation/bottom-tabs": "5.1.1",
 "@react-navigation/core": "5.2.1",
 "@react-navigation/drawer": "5.1.1",
"@react-navigation/material-bottom-tabs": "5.1.1",
 "@react-navigation/material-top-tabs": "5.1.1",
"@react-navigation/native": "5.0.9",

**Additional context**
i added react-native-gesture-handler in my main js file, i tried to follow all the best practice in react-navigation, renative implementation,  nothing changed. Before that i had issue building the helloworld template for webos, causing issue with proposal-numeric-separator, i resolved this following -> [https://stackoverflow.com/questions/60780664/could-not-find-plugin-proposal-numeric-separator](url)

**Comment by numericgraphics** [comment]
For all who can be blocked in the same way, i have fix this issue by adding a plugin property in the renative.json in the appConfigs folder : 

`"plugins": {
        "react-native-reanimated": "1.8.0"
    },`

this way, we update the global config file.

**Comment by delalama** [comment]
npm i react-native-reanimated

**Comment by ZeeshanAhmadKhalil** [comment]
@numericgraphics  I can't find `renative.json` in my react native project

**Comment by ZeeshanAhmadKhalil** [comment]
I was getting this issue because I first installed react drawer navigator and then react-native-reanimated.

I solved the issue by installing both `@react-navigation/drawer` and `react-native-reanimated` and then following commands:

1) `npm install react-native-reanimated`
2) `npm link react-native-reanimated`
3) `cd ios && pod install`
4) `npm install @react-navigation/drawer`

**Comment by softwareeenginer** [comment]
I have same problem. Is this fixed?

**Comment by agboolaidris** [comment]
> "plugins": { "react-native-reanimated": "1.8.0" },

this work for me

**Comment by agboolaidris** [comment]
> For all who can be blocked in the same way, i have fix this issue by adding a plugin property in the renative.json in the appConfigs folder :
> 
> `"plugins": { "react-native-reanimated": "1.8.0" },`
> 
> this way, we update the global config file.

this work for me
