### ISSUE TITLE
How can we get TouchableOpacity hover effect on the web?

### ISSUE THREAD

**Issue by SandeepKharbanda** [pavjacko/renative#454]
Hi,

I am developing a web application in ReNative and I have a Flatlist which contains a list of TouchableOpacity buttons. But whenever I run code on the web then I am not able to get the hover event on the TouchableOpacity button. I have to implement some animation on the button's hover but it contains only onFocus and onBlur events. So, could you please assist me in how can we achieve a button's hover effect on the web.

**Comment by kasinskas** [comment]
you can use onMouseEnter/onMouseLeave

**Comment by SandeepKharbanda** [comment]
@kasinskas : TouchableOpacity button doesn't include onMouseEnter/onMouseLeave event.

**Comment by kasinskas** [comment]
Have you tried using it?

**Comment by SandeepKharbanda** [comment]
Yes, It's working. Thanks @kasinskas for the help.

**Comment by sanderlooijenga** [comment]
The underlying technology ReNative uses for Web is; https://github.com/necolas/react-native-web . Have you tried looking for info there as well?
