### ISSUE TITLE
Android deviceManager.js emulatros typo

### ISSUE THREAD

**Issue by TheDuc** [pavjacko/renative#456]
https://github.com/pavjacko/renative/blob/d00c1ff03dbe2aacc751f4afcc343298c7023a2f/packages/rnv/src/platformTools/android/deviceManager.js#L504

**Comment by pavjacko** [comment]
@TheDuc thx for pointing up :) fixed in upcoming `0.29.0`

**Comment by TheDuc** [comment]
Thanks!
