### ISSUE TITLE
remote control keys on webOS simulator not working.

### ISSUE THREAD

**Issue by saubhagya23** [pavjacko/renative#458]
I want to control the remote control events i.e. fetch the keycode events and add custom functionality for remote control keys according to the key codes but I'm not able to handle the events for webOS.

For _tvOS_ , this is done using TVEventHandler. **How can we control events for webOS or Tizen?**

**Comment by kasinskas** [comment]
Standart keyboard events like `onKeyDown` `onKeyPress` `onKeyUp` should work on a wrapper view.
```javascript
<View
    onKeyDown={e => {
    console.log(e.keyCode);
    }}
>
{children}
</View>
```
or you can use event listener 
```javascript
document.addEventListener('keydown', function(e) {
            console.log(e.keyCode);
        });
```

**Comment by numericgraphics** [comment]
Any update for this question, maybe i'm doing things wrong ! Thx anyway.

**Comment by saubhagya23** [comment]
@kasinskas It worked. Thank you.
