### ISSUE TITLE
How can we write native code in Renative project?

### ISSUE THREAD

**Issue by SandeepKharbanda** [pavjacko/renative#461]
Hello, I am developing a cross-platform application(which will support all platforms) in ReNative.  But, If I need to write some native code, for example, LG webOS so how can we write it?

**Comment by SandeepKharbanda** [comment]
Any update on this question?

**Comment by CHaNGeTe** [comment]
Are you aware of form factors?
Sound like a nice approach for you to do that:
https://renative.org/docs/next/guide-file_extensions#form-factors

**Comment by SandeepKharbanda** [comment]
yes, I am using form factors in my project but in my case, index.webos.js is not rendering and it renders index.tv.js instead of index.webos.js. And, how can we return view from webOS as I guess, webOS doesn't support render function.

**Comment by SandeepKharbanda** [comment]
And, how can we write swift and android code in renative?

**Comment by pavjacko** [comment]
@SandeepKharbanda you can inject native ios code directly to project via `builds` folder.
for this you need latest alpha of 0.29 `0.29.0-alpha.34` (linking files to xcode project has been added there)

below snippet assumes you created app from `renative-hello-world-template` but applies to any project

STEP 1:
create file at `appConfigs/base/builds/ios/RNVApp/MySwiftFile.swift`

```swift
import UIKit

class MySwiftFile {
    func hello() -> Void {
        print("Hello")
    }
}
```

STEP 2:
Update `appConfigs/base/renative.json` 

```json
"platforms": {
     "ios": {
             "xcodeproj": {
                "sourceFiles": ["RNVApp/MySwiftFiless.swift"]
            }
     }
}
```
STEP 3:
run `rnv run -p ios`


you should see new file injected to xcode project if you open
`platformBuilds/helloWorld_ios/RNVApp.xcworkspace`

NOTE:
in the final `0.29.0` I plan to add support for injecting + linking above native code directly from `src` folder so no need to maintain renative.json `sourceFiles` but for now this should do the trick

**Comment by SandeepKharbanda** [comment]
Thanks, @pavjacko for the support but how can we import swift file in the renative project.

Shall we use this command 
`import {NativeModules} from 'react-native';`
or anything else?

**Comment by pavjacko** [comment]
@SandeepKharbanda to use native code in ReNative same rules apply as standard React Native modules ie:
https://reactnative.dev/docs/native-components-ios

to use RN plugin directly in ReNative project you can try this example:

`appConfigs/base/builds/ios/RNVApp/MyModuleView.swift`

```swift
import UIKit;

@objc(MyModuleView)
class MyModuleView: UIView {
    var shouldSetupConstraints = true
    var myButton = UILabel()
    
    @objc
    override init(frame: CGRect) {
        super.init(frame: frame)
        setupView()
    }

    @objc
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setupView()
    }

    private func setupView() {
        backgroundColor = .red
        myButton.font = UIFont.systemFont(ofSize: 22, weight: .medium)
        myButton.text = "Hello From Native"
        myButton.textAlignment = .center
        myButton.translatesAutoresizingMaskIntoConstraints = false
        self.addSubview(myButton)
    }
        
    override func updateConstraints() {
        if(shouldSetupConstraints) {
        // AutoLayout constraints
        shouldSetupConstraints = false
        }
        super.updateConstraints()
    }
}
```

`appConfigs/base/builds/ios/RNVApp/RCTMyModuleManager.m`

```objc
// RTCMyModuleManager.m
#import "RNVApp-Swift.h"

#import <React/RCTViewManager.h>

@interface RTCMyModuleManager : RCTViewManager
@end

@implementation RTCMyModuleManager

RCT_EXPORT_MODULE(RNTMyModule)

- (UIView *)view
{
  return [[MyModuleView alloc] init];
}

@end
```

`appConfigs/base/renative.json`

```json
{
    "platforms": {
        "ios": {
            "xcodeproj": {
                "sourceFiles": [
                    "RNVApp/MyModuleView.swift",
                    "RNVApp/RCTMyModuleManager.m"
                ]
            }
        }
    }
}
```

`src/MyNativeModuleView.js`

```js
import { requireNativeComponent } from 'react-native';

module.exports = requireNativeComponent('RNTMyModule');
```

Now you can use `MyNativeModuleView` as standard react view in your code

```
import from './MyNativeModuleView'
...
<MyNativeModuleView />
```

**Comment by numericgraphics** [comment]
hello, @pavjacko is it possible to do the same things for androidtv, or android ? thx

**Comment by CHaNGeTe** [comment]
sure https://reactnative.dev/docs/native-components-android

**Comment by numericgraphics** [comment]
@CHaNGeTe  Thx for link !
Im talking about implementing react native module in renative, like it is demonstraded above.
I'm trying to use the appConfig folder to override file like MainApplication.java file, to push for example a custom package (native module) to the getPackage function. Is it possible to use the appConfigs/base/renative.json to do the same thing, and adding java files, too.
thx

**Comment by CHaNGeTe** [comment]
I think there are some methods for android/androidtv as well, but @pavjacko knows best.
https://renative.org/docs/guide-plugins#adapt-3rd-party-plugins-to-support-rnv

But I am not used to it, I find much more easier to include your native code as an npm package as it was another RN library.

**Comment by numericgraphics** [comment]
Hello @CHaNGeTe, thx for your answer.
I need to implement a local package, made with create-react-native-module command.
I use this package only for androidtv.
I tried to had this package into the ./renative.json and to package.json : 

"plugins": { 
"react-native-letterbox-android": "file:./react-native-letterbox-android/"
....
}

I tried to add the plugin in the appConfig/blank/renative.json file : 

"plugins": {
    "androidtv": {
        "package": "com.reactlibrary.LetterboxAndroidPackage",
            "path": "node_modules/react-native-letterbox-android/android"
    }
},

But after building the project the package is still null : 
import LetterboxAndroid from 'react-native-letterbox-android';
console.log('LetterboxAndroid', LetterboxAndroid) === null

I tried the same thing with android, and i had the same result.
Is there something i miss ?
Thx anyway

**Comment by numericgraphics** [comment]
Any update on this question ?
Please let me know !

**Comment by aemre** [comment]
I have migrate my rn appplication as well native modules but rnv run override string.xml and build.gradle so my application build failed.

How can I give strings and build gradle  rnv?

**Comment by ParvinderjitSF** [comment]
Is it still valid ?
