### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by redgoalsuk** [pavjacko/renative#469]
Hi

First let me say thanks to the developers for providing this awesome platform to the community!

I am just starting out with setting up a basic app to run on a Tizen TV, I followed the instructions to install rnv but I keep getting this error when trying to launch on the Tizen TV.

Can someone shed some light on what this means and how to fix it?

![Screenshot from 2020-04-17 05-00-07](https://user-images.githubusercontent.com/63847979/79567403-1566a480-80ac-11ea-813a-0e716fce82c3.png)

**Comment by redgoalsuk** [comment]
I got this working on Tizen TV by installing the following, not sure if this is the correct fix but it launches the app fine.

npm i @babel/compat-data@7.8.0
npm i @noriginmedia/react-spatial-navigation
npm i @reach/router

However a new problem has arisen, I have created the HelloWorld template and launched it on the TizenTV (physical device) and it looks fine but the app is not responding to the keys on the remote - its like its frozen?

rnv run -p tizen -d -t 192.168.1.31

When I launch it via the web platform it works fine and no errors in the web console?

rnv run -p web 

any help would be appreciated.

**Comment by numericgraphics** [comment]
hello, its seem to be the same think for webos... 
issue --> Webos 05.10.30 - Hello World template keyEvent issue ! #459

**Comment by redgoalsuk** [comment]
yes it is a nice framework but not currently working on Smart TVs, im not sure if it is outdated modules or some configuration setting or something else, I did try using react-js-spatial-navigation but it also did not respond to any keys.
