### ISSUE TITLE
Tizen Build Issue

### ISSUE THREAD

**Issue by saubhagya23** [pavjacko/renative#470]
Hello,
I'm not able to create build for tizen. I tried creating a production build but it was not working. I also made changes in the build for tizen, replacing some files with that of webos build and it worked but
I need to execute my application on Tizen web simulator using _run_ command which fails as it is not able to find the simulator or the default emulator provided in _.rnv/renative.json_. 
How can I provide the current instance of tizen simulator as the target device for command **rnv run -p tizen -t <TARGET_DEVICE>** so the application build gets executed on web simulator.

**Comment by SandeepKharbanda** [comment]
Having the same issue. Whenever I try to run the Tizen TV app on the Tizen emulator, I get the following error: 
<img width="1209" alt="Screenshot 2020-04-18 at 5 45 13 AM" src="https://user-images.githubusercontent.com/33030857/79623076-fca3d080-8137-11ea-8cb0-16c19f726d6f.png">

I have also followed all steps which are mentioned in https://renative.org/docs/platform-tizen

**Comment by davidB** [comment]
to run with the tizen simulator: 
```
npx rnv run -p tizen --hosted
```

to run the emulator:
```
npx rnv run -p tizen -t <emulator_name>
```

before  you have to check that the emulator can run, start the emulator manager and launch the <emulator_name> (create it if not). I got issue on the emulator config (HW: CPU-vt was OFF) when I had issue with `rnv run -p tizen...`.

**Comment by avkan1087** [comment]
same here its open the emulator but not working (HW: CPU-vt was ON)
![Screenshot 2020-04-27_23-49-30-281](https://user-images.githubusercontent.com/56038330/80445240-c3aaef00-88e1-11ea-8fdc-207061868a7a.png)
