### ISSUE TITLE
I get error while running rnv build -p web

### ISSUE THREAD

**Issue by benz0is** [pavjacko/renative#474]
**Describe the bug**
I try to run "rnv build -p web" and I get this error:

"│ �  $ rnv build -p web - ERRROR! COMMAND:

npx cross-env PLATFORM=web NODE_ENV=production  node C:\Users\user\AppData\Roaming\npm\node_modules\rnv\node_modules\webpack\bin\webpack.js -p --config ./platformBuilds/helloWorld_web/webpack.config.js

FAILED with ERROR:

[133] ./src/app/index.web.js 3.07 KiB {2} [built] [failed] [1 error]
[337] ./index.web.js 167 bytes {2} [built]
 + 339 hidden modules
ERROR in ./src/app/index.web.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] C:\Users\user\seal\src\app\index.web.js: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. (While processing: "C:\\Users\\user\\seal\\node_modules\\@babel\\preset-env\\lib\\index.js")
 at getPlugin (C:\Users\user\seal\node_modules\@babel\preset-env\lib\index.js:67:11)
 at C:\Users\user\seal\node_modules\@babel\preset-env\lib\index.js:258:62
 at Array.map (<anonymous>)
 at C:\Users\user\seal\node_modules\@babel\preset-env\lib\index.js:258:43
 at C:\Users\user\seal\node_modules\@babel\helper-plugin-utils\lib\index.js:19:12
│                                                                              │"

**Desktop (please complete the following information):**
 - OS: [e.g. osx, windows 7, ubuntu 16.04]windows 10
 - Node Version [e.g. v10.16.3]12.16.2
 - RNV Version [e.g. 0.25.0]idk how to check but its the latest one

**Comment by TheDuc** [comment]
can you try adding this to your package.json?
```
"resolutions": {
    "@babel/preset-env": "^7.8.7"
}
```

**Comment by benz0is** [comment]
I tried to write it , but it didnt work. ( Is there a difference if I wrote it at the end of the file ?)

**Comment by benz0is** [comment]
I also notice , that when I run rnv build -p web and I get the error, my edit is deleted.
