### ISSUE TITLE
rnv run -p android gives me bug

### ISSUE THREAD

**Issue by benz0is** [pavjacko/renative#476]
I run " rnv run -p android" and get this error:
\ Review licenses that have not been accepted (y/N)?     
It does not let me write y or n , it doesnt even let me write anything else. It is just stuck there

**Desktop (please complete the following information):**
 - OS: [e.g. osx, windows 7, ubuntu 16.04]Windows 10
 - Node Version [e.g. v10.16.3]12.16.2
 - RNV Version [e.g. 0.25.0]latest one

**Comment by pavjacko** [comment]
@benz0is will add it to backlog. for now you should be able to resolve it by opening Android Studio and accepting licences directly there
