### ISSUE TITLE
Error when importing some modules and how to choose screen orientation

### ISSUE THREAD

**Issue by BrendelSantos** [pavjacko/renative#482]
When installing certain modules, an error like: Module parse failed: Unexpected token
You may need an appropriate loader to handle this file type.

Example:
ERROR in ./node_modules/react-native-video/Video.js 54: 7
Module parse failed: Unexpected token (54: 7)
You may need an appropriate loader to handle this file type.
| }
|
seek = (time, tolerance = 100) => {
| if (isNaN (time)) throw new Error ('Specified time is not a number');
|
  @ ./src/VideoMobile.js 1: 220-249
  @ ./src/app.js

Another question is how can I change the screen orientation for Android

Thanks

**Comment by redgoalsuk** [comment]
I am getting the same error when trying to use react-native-video with this platform

any fix anyone?

**Comment by BrendelSantos** [comment]
Hello. I made progress. I don't know if it's the best solution, but I'll share it.

To be able to use the react-native-video library, I created two App.js, one for the web (importing react-player) and another for mobile (importing react-native-video). This way, they are imported into index.web.js and index.android.js, respectively.

To rotate the screen on android, I changed the "AndroidManifest" section in the renative.json:

`            "AndroidManifest": {
                "children": [
                    {
                        "tag": "application",
                        "android: name": ".MainApplication",
                        "android: usesCleartextTraffic": true,
                        "tools: targetApi": 28,
                        "children": [
                            {
                                "tag": "activity",
                                "android: name": ".MainActivity",
                                "android: screenOrientation": "landscape"
                            }
                        ]
                    }
                ]
            }`
