### ISSUE TITLE
How can we create release build of Android TV, Web OS & tizen?

### ISSUE THREAD

**Issue by SandeepKharbanda** [pavjacko/renative#485]
I am developing a smart tv application in Renative for multiple platforms such as android tv, LG web os, and Samsung Tizen but could you please tell me the commands for creating release build of Android TV, WebOS, and Tizen as I am unable to run development build on physical devices.

**Comment by sanderlooijenga** [comment]
Hi @SandeepKharbanda, you can run a release build by specifying it as the scheme you want to run your project with, e.g. `npx rnv <command> -p tizen -s release`, where command in this case is probably `build`, but can also be others like `run`, check out the docs here; https://renative.org/docs/api-cli-build#options . That release config is stated in your appConfig, as you might be able to see here; https://github.com/pavjacko/renative/blob/master/packages/renative-template-hello-world/appConfigs/base/renative.json#L171 .
Hope this helps!

**Comment by SandeepKharbanda** [comment]
Hi @sanderlooijenga, I am now able to create the release build of android tv and it's working fine on the device, Thanks for your support, but still, I am getting the error while creating Tizen build. I run the following command for making Tizen build `rnv run build -p tizen -s release` but in return, I get the following error:

**Comment by sanderlooijenga** [comment]
@SandeepKharbanda are you trying to `run` it or `build` it? I would do either of them, not both. So `npx rnv run -p tizen -s release` or `npx rnv build -p tizen -s release`. Also. make sure to post the complete summary box of the command you just ran, so that we also see which version of `rnv` you're using etc.

**Comment by CHaNGeTe** [comment]
I think Tizen also requires to have the certificates up to date:
https://developer.samsung.com/smarttv/develop/getting-started/setting-up-sdk/creating-certificates.html
