### ISSUE TITLE
svg not converted to js correctly when in root runtime folder

### ISSUE THREAD

**Issue by TheDuc** [pavjacko/renative#490]
**Describe the bug**
Consider the following appConfigs structure: `[projectfolder]/appConfigs/base/assets/runtime/test.svg`. This svg is not converted by Svg2Js.
When placing the svg file one level deeper, the js file is correctly generated: `[projectfolder]/appConfigs/base/assets/runtime/svgs/test.svg`.

**Expected behaviour**
Svg's to be converted regardless of their placement in root or deeper nested

**Additional context**
It looks like in the first case only https://github.com/pavjacko/renative/blob/ece6c865e9c91077eb65fc2b127b02a94ac88fce/packages/rnv/src/systemTools/fileutils.js#L173 is called, but in the second case the other very similar function https://github.com/pavjacko/renative/blob/ece6c865e9c91077eb65fc2b127b02a94ac88fce/packages/rnv/src/systemTools/fileutils.js#L129 is called, that has an svg check

**Comment by pavjacko** [comment]
Fix deployed with `0.29.1-alpha.2`
