### ISSUE TITLE
Wrong pages on platform overview documentation

### ISSUE THREAD

**Issue by YuviGold** [pavjacko/renative#497]
**Describe the bug**
The links on the platforms overview page are redirected to wrong addresses.

**To Reproduce**

1. I visited [ReNative platform overview](https://renative.org/docs/platforms) website page
2. I clicked on any of the platforms links (ios, tvos, etc..)
3. I redirected `/docs/${OS}` and I get 404 error.

**Expected behavior**
The hyperlinks should be redirected to `/docs/platform-${OS}`

**Comment by mihaiblaga89** [comment]
It seems to work just fine now. I don't know it this was fixed in the meantime or not

**Comment by pavjacko** [comment]
@YuviGold thanks for reporting this. Redeployed the website with fixed links
