### ISSUE TITLE
Install error on Ubantu.  npm ERR! node-expat@2.3.18 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by mabhishek7081** [pavjacko/renative#499]
# i tried to install on Ubuntu but it is giving error. Please Help!
### Result ==>
> node-expat@2.3.18 install /usr/local/lib/nodejs/node-v14.0.0-linux-x64/lib/node_modules/rnv/node_modules/node-expat
> node-gyp rebuild

gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 5.3.0-51-generic
gyp ERR! command "/usr/local/lib/nodejs/node-v14.0.0-linux-x64/bin/node" "/usr/local/lib/nodejs/node-v14.0.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/nodejs/node-v14.0.0-linux-x64/lib/node_modules/rnv/node_modules/node-expat
gyp ERR! node -v v14.0.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/rnv/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN rnv@0.29.0 requires a peer of now@15.3.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.18 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.3.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/abhishek/.npm/_logs/2020-05-10T08_21_14_099Z-debug.log

**Comment by mihaiblaga89** [comment]
you have a serious issue with node. You should not be required to run it with `sudo`. If you do that it creates a whole range of permission issues, like the one you have above. ` Error: EACCES: permission denied, rmdir 'build'`. 

This has nothing to do with `node-gyp` or `rnv` or anything else except your config. I can't help you solve this since it's related to your config and the permissions you have on the node's folders. For more info on why you should not use sudo, https://medium.com/@ExplosionPills/dont-use-sudo-with-npm-still-66e609f5f92

**Comment by mabhishek7081** [comment]
i uninstalled node completely and reinstalled it . but it throws a new error

**Comment by mihaiblaga89** [comment]
@mabhishek7081 what error?

**Comment by mabhishek7081** [comment]
@mihaiblaga89  i used `NVM` to resinstall node
#### CMD --> npm install rnv -g
##### Result --> 
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
/home/abhishek/.nvm/versions/node/v14.2.0/bin/rnv -> /home/abhishek/.nvm/versions/node/v14.2.0/lib/node_modules/rnv/bin/index.js

> node-expat@2.3.18 install /home/abhishek/.nvm/versions/node/v14.2.0/lib/node_modules/rnv/node_modules/node-expat
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/abhishek/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/abhishek/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/abhishek/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/abhishek/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/abhishek/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/abhishek/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:175:21)
gyp ERR! System Linux 5.3.0-51-generic
gyp ERR! command "/home/abhishek/.nvm/versions/node/v14.2.0/bin/node" "/home/abhishek/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/abhishek/.nvm/versions/node/v14.2.0/lib/node_modules/rnv/node_modules/node-expat
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/rnv/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN rnv@0.29.0 requires a peer of now@15.3.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.18 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.3.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/abhishek/.npm/_logs/2020-05-13T06_28_21_680Z-debug.log

**Comment by mabhishek7081** [comment]
@mihaiblaga89 I fixed This Thanks a lot for your reply, it helped in getting the issue.
### to someone who is facing same issue 
follow the below reply
https://github.com/pavjacko/renative/issues/421#issuecomment-614826681
it worked for me!

**Comment by mihaiblaga89** [comment]
@mabhishek7081 was just about to send you that link. Glad it was solved!

**Comment by pavjacko** [comment]
this troublesome dependency will be removed in #505
