### ISSUE TITLE
[Android] incorrect folder delimiters on Windows

### ISSUE THREAD

**Issue by TheDuc** [pavjacko/renative#507]
**Describe the bug**
In android(tv) platformBuilds folder there are multiple files with backslashes that should be forward slashes when running on Windows.

**To Reproduce**
Be on Windows, run `npx rnv run -p androidtv` observe error:
```
* Where:
Settings file 'C:\Users\[redacted]\platformBuilds\hor_androidtv\settings.gradle' line: 3

* What went wrong:
Could not compile settings file 'C:\Users\[redacted]\platformBuilds\hor_androidtv\settings.gradle'.
> startup failed:
  settings file 'C:\Users\[redacted]\platformBuilds\hor_androidtv\settings.gradle': 3: unexpected char: '\' @ line 3, column 51.
     ve').projectDir = new File('C:\Users\
                                   ^
```

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Node Version 14.3.0
-   RNV Version 0.29.1-alpha.8

**Additional context**
Files that contain wrong slashes are:
```
settings.gradle ({{PLUGIN_PATHS}})
build.gradle ({{PATH_REACT_NATIVE}} and {{PATH_JSC_ANDROID}})
app/build.gradle ({{PATH_HERMES_ENGINE}}, {{PATH_REACT_NATIVE}} and {{PLUGIN_IMPLEMENTATIONS}})
```

**Comment by pavjacko** [comment]
fixed in `0.30.0`
