### ISSUE TITLE
Platform Engines

### ISSUE THREAD

**Issue by pavjacko** [pavjacko/renative#511]
This feature will enable support of variety of different (including custom) rendering methods in ReNative projects

Current `rnv` package bundles support for multiple platforms into one package including CLI.
This architecture approach was chosen on purpose in order to rapidly develop ReNative but it is reaching the end of its usefulness and more decoupled approach is becoming necessary.

Goal: Separate `rnv` package into decoupled modularised systems:

- `@rnv/core` - core rnv system 
- `@rnv/cli` - decoupled cli console
- `@rnv/system-android` - core manager for android based SDKs / emulators etc 
- `@rnv/system-apple` - core manager for apple based SDKs / emulators etc 
- `@rnv/system-tizen` - core manager for tizen based SDKs / emulators etc 
- `@rnv/system-win` - core manager for UWP based SDKs / emulators etc 
- `@rnv/system-webos` - core manager for webOS based SDKs / emulators etc 
- `@rnv/engine-rn` - react native + web engine (default)
- `@rnv/engine-rn-next` - react native + next engine
- `@rnv/engine-rn-electron` - engine for electron builds
- `@rnv/engine-rn-windows` - engine for react-native-windows
...

This update will allow developers to build their own fully custom engines further enhancing flexibility of the platform.

usage example (configure web platform to use next engine by default):

```
{
    "platforms": {
         "web": {
             "engine": "engine-rn-next"
         }
    }
}
```

**Comment by elmpp** [comment]
[This](https://github.com/yarnpkg/berry/tree/master/packages/yarnpkg-core/sources) is the state of the art with regard to plugin architectures. Also, [createRequire](https://nodejs.org/api/modules.html#modules_module_createrequire_filename) helps enormously

**Comment by SatadruBhattacharjee** [comment]
can we start using the `rnv new --engine <engine-name>` command to select the particular engine (i.e. engine-lightning) ?
