### ISSUE TITLE
Issue on windows when rnv run -p android in project directory 

### ISSUE THREAD

**Issue by JohnLiber** [pavjacko/renative#514]
Can't run project 

**To Reproduce**

1. Run command 'rnv run -p android' in project directory
2. See error

-   OS: Windows 10
-   Node Version v12.17.0
-   RNV Version 0.29.0

`- Waiting for bundler to finish...$ rnv run - _isBundlerRunning:android - Starting!
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\Users\User\Desktop\React'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
COMMAND:

node C:\Users\User\Desktop\React Projects\Test1\node_modules\react-native/local-cli/cli.js start --port 8083 --config=configs/metro.config.android.js

FAILED with ERROR:

Error: Command failed with exit code 1 (Unknown system error -1): node C:\Users\User\Desktop\React Projects\Test1\node_modules\react-native/local-cli/cli.js start --port 8083 --config=configs/metro.config.android.js
    at makeError (C:\Users\User\Desktop\React Projects\Test1\node_modules\rnv\node_modules\execa\lib\error.js:58:11)
    at handlePromise (C:\Users\User\Desktop\React Projects\Test1\node_modules\rnv\node_modules\execa\index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
| Waiting for bundler to finish...$ rnv run - _isBundlerRunning:android - Starting!
\ Waiting for bundler to finish...$ rnv run - _isBundlerRunning:android - Starting!
- Waiting for bundler to finish...$ rnv run - _isBundlerRunning:android - Starting!
× Can't connect to bundler. Try restarting it.`

**Comment by pavjacko** [comment]
@JohnLiber rnv `0.30.0` has been released with path fixes to WIN based android projects
