### ISSUE TITLE
Ejected Schmejected

### ISSUE THREAD

**Issue by elmpp** [pavjacko/renative#516]
**Describe the bug**
RNV reports ejected status of SDK-UI after upgrade to 0.29.1-alpha.19 from 0.29.0 and fails build.

**To Reproduce**
See Travis links below

**Expected behavior**
It builds

**Screenshots or copy&paste**
 - [Failing build](https://travis-ci.com/github/24i/prd-nxg-sdk-ui/jobs/346653585#L2595) (with 0.29.1-alpha.19)
 - [Passing build (with minimal client differences)](https://travis-ci.com/github/24i/prd-nxg-sdk-ui/jobs/344137963#L2630) (with 0.29.0)

**Desktop (please complete the following information):**

┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 6/9/2020, 3:06:51 PM                                          │
│  $ rnv build -p web -c sanityApp -s alpha -r --mono --maxErrorLength 1000 --hosted                                                                            │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.29.1-alpha.19                                           │
│  Project Name: @24i/prd-nxg-sdk-ui                                           │
│  Project Version: 0.15.4                                                     │
│  App Config: sanityApp                                                       │
│  Supported Platforms: ios(ejected), android(ejected), androidtv(ejected),    │
│  androidwear(ejected), web(ejected), tizen(ejected), tvos(ejected),          │
│  webos(ejected), macos(ejected), windows(ejected), tizenwatch(ejected),      │
│  kaios(ejected), firefoxos(ejected), firefoxtv(ejected), web-next(ejected)   │
│  Env Info: linux | x64 | node v10.15.3                                       │
│  Build Scheme: alpha                                                         │
│  Platform: web                                                               │
│  Executed Time: 0h:0m:2s:112ms                                               │
│                                                                              │

**Additional context**

**Comment by pavjacko** [comment]
deleting  `"platformTemplatesDir": "PROJECT_HOME/platformTemplates",` from `renative.json` (marking eject) should fix it
