### ISSUE TITLE
Is Renative A Runtime Dependency?

### ISSUE THREAD

**Issue by elmpp** [pavjacko/renative#518]
Just going through `sdk-ui` and it seems `renative` is [imported](https://github.com/24i/prd-nxg-sdk-ui/blob/develop/index.androidtv.js#L2) a few times but never actually used.

We also have the `Quantum` package which provides 95% of our env values (+ the ability to add more via the extensions mechanism).

Can `renative` be removed from `sdk-ui`?

**Comment by pavjacko** [comment]
`renative` provides set of low level helper tools (documented in more detail here: https://renative.org/docs/api-renative ) to help with low level cross-platform optimisations related to platforms, form factors, fallbacks combined with extension support provided by `rnv`

It is essentially a developer's choice whether to utilise these APIs or build and use their own custom utilities.
