### ISSUE TITLE
Best way to add auto orientation for ios

### ISSUE THREAD

**Issue by elmpp** [pavjacko/renative#521]
Am looking to add orientation support (e.g. rotate screen to trigger landscape layout) for ios but am a bit unsure what values to add. Could i get an example please?

Looking at the [platform docs](https://renative.org/docs/next/api-config#ios-1) it suggests a possible mix of `orientationSupport` and `appDelegateApplicationMethods` but bit out of depth here.

This is for KitchenSink project with no current ios-specific platform config

**Comment by pavjacko** [comment]
add this snippet to `renative.json`

```
  "platforms": {
    "ios": {
      "orientationSupport": {
        "phone": [
          "UIInterfaceOrientationPortrait",
          "UIInterfaceOrientationPortraitUpsideDown",
          "UIInterfaceOrientationLandscapeLeft",
          "UIInterfaceOrientationLandscapeRight"
        ],
        "tab": [
          "UIInterfaceOrientationPortrait",
          "UIInterfaceOrientationPortraitUpsideDown",
          "UIInterfaceOrientationLandscapeLeft",
          "UIInterfaceOrientationLandscapeRight"
        ]
      },
   } 
}
```

will result in:

![Jun-16-2020 11-03-55](https://user-images.githubusercontent.com/4638697/84755022-72ee7300-afc1-11ea-870a-ad5bc6963044.gif)

**Comment by elmpp** [comment]
Thank you!
