### ISSUE TITLE
Cannot run project on ios

### ISSUE THREAD

**Issue by luiscerqueira** [pavjacko/renative#523]
I'm starting a helloworld project and i am trying to run it on an IOS simulator, but with no avail.

## Configurations
- OSX: v10.14.5
- xcode: v10.2.1
- swift: v5.0.1
- cocoa pods: v1.8.4
- simulator: iPhone 6 - 12.2
- rnv: v0.29 (tried in 0.28.18, with te same results)
- node: v12.5.0
- npm: v6.9.0

## Steps
1. `npm install -g rnv`
2. `rnv new`
 - choose rnv as workspace
 - choose  default app id
 - choose hello world template
![image](https://user-images.githubusercontent.com/26207717/84936656-80475280-b0d2-11ea-999f-6c89b0bad722.png)

3. `rnv run -p ios`

After running the ios command, the application build fails
![image](https://user-images.githubusercontent.com/26207717/84936780-ae2c9700-b0d2-11ea-8497-d1ee0f6515ba.png)

The output sugests opening the Xcode workspace, and run the app from there.
Running the app from xcode... there are no compilation errors, but the application fails to load due to connection problems with the development server.
![image](https://user-images.githubusercontent.com/26207717/84937116-301cc000-b0d3-11ea-9d91-0f385ac7acde.png)

(I belive server is stopped when the command exection fails)

Do i need any adicional configurations? The error talks about the BundleIndentifier, but I believe that running in debug mode, it is not mandatory to have a valid certified bundle id (or am i wrong?).

**Comment by pavjacko** [comment]
@luiscerqueira 
connection problem can be fixed by executing `rnv start -p ios` this only starts server and skip compilation / run

could you try `npm install -g rnv@latest` (incoming 0.29.1 alpha)
and same steps above?

if it persists it would be helpful if you post full output of your console to be able to pinpoint the issue

**Comment by pavjacko** [comment]
rnv `0.30.0` has been released with additional fixes to build locations of iOS projects
