### ISSUE TITLE
renative.json not merging with workspace ones

### ISSUE THREAD

**Issue by mihaiblaga89** [pavjacko/renative#524]
**Describe the bug**
if you have a `.workspace/renative.json` it will not get merged with `.rnv/renative.json` so you'll need to define the sdks there as well.

Errors:
- ✅ Found existing android SDK location at /Users/---/Library/Android/sdk? Do you want to use it? (Y/n)
- Cannot read property 'ANDROID_NDK' of undefined

**Expected behavior**
Would expect to have my sdks inherited from the global one.

**Desktop (please complete the following information):**

-   OS: [osx]
-   Node Version [14.3]
-   RNV Version [0.29.1-alpha.12]

**Comment by pavjacko** [comment]
@mihaiblaga89 could you try `0.30.2-alpha.2` from this PR #529
