### ISSUE TITLE
Add Contributing guidelines

### ISSUE THREAD

**Issue by sanderlooijenga** [pavjacko/renative#527]
**Is your feature request related to a problem? Please describe.**
I would like to know how I can correctly contribute to this repo. E.g. do I need to write commits in a certain way (keeping in mind automated changelogs perhaps) and all that good stuff.

**Describe the solution you'd like**
A `CONTRIBUTE.md` on how to correctly contribute to RNV. You can look at Github's docs on this here; https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

**Additional context**
Examples of contributing documentation;

1. https://github.com/angular/angular/blob/master/CONTRIBUTING.md
2. https://github.com/angular/angular.js/blob/master/DEVELOPERS.md

**Comment by pavjacko** [comment]
@sanderlooijenga good point. will put proper contribution guidelines together soon.
