### ISSUE TITLE
Application crashes when trying to launch it on AndroidTV

### ISSUE THREAD

**Issue by doneitas** [pavjacko/renative#53]
![image](https://user-images.githubusercontent.com/36989231/57507231-da3dec00-7306-11e9-867b-e48dc70afecd.png)

`
05-09 15:47:14.089 15050 15050 E AndroidRuntime: FATAL EXCEPTION: main
05-09 15:47:14.089 15050 15050 E AndroidRuntime: Process: reactnativevanilla.helloworld.debug, PID: 15050
05-09 15:47:14.089 15050 15050 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{reactnativevanilla.helloworld.debug/reactnativevanilla.helloworld.debug.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2691)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2752)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6120)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:555)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:457)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:145)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:89)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:75)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:52)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6664)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2644)
05-09 15:47:14.089 15050 15050 E AndroidRuntime: 	... 9 more
`

**Comment by hosek** [comment]
As a quick fix, you can change the AppTheme to the AppCompat one
` <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar" />`

**Comment by pavjacko** [comment]
@doneitas now properly fixed in https://github.com/pavjacko/renative/releases/tag/0.21.6
@hosek thx for the PR!
