### ISSUE TITLE
[Tizen TV] files named *.tizen.js not found by webpack

### ISSUE THREAD

**Issue by TheDuc** [pavjacko/renative#531]
The extension `*.tizen.js` are not found. Only `*.tizen.tv.js`.
I believe that there should be no tv in this line for the tizen platform.
https://github.com/pavjacko/renative/blob/9707e93c6e19a2ddde6aeed45ff7e3180e3fe0d4/packages/rnv/src/constants.js#L99

**Comment by pavjacko** [comment]
@TheDuc good catch! released `0.30.3` with the hotfix.

**Comment by TheDuc** [comment]
thanks!
