### ISSUE TITLE
Recursive/nested plugin scopes/templates

### ISSUE THREAD

**Issue by sanderlooijenga** [pavjacko/renative#535]
**Is your feature request related to a problem? Please describe.**
I know that in RNV we have the possibility of defining a source/scope for plugins, as mentioned [here in the docs](https://renative.org/docs/api-config#source). I was wondering however if we can have this "multiple-levels deep"/recursive.

So e.g. consider the following scenario; within your root (project's) `renative.json` you have defined the following custom scope;

```json
// root project's renative.json
{
  "paths": {
      "pluginTemplates": {
          "myCustomScope": {
              "npm": "some-renative-template-package",
              "path": "./pluginTemplates"
          }
      }
   },
   "plugins": {
        "my-plugin": "source:myCustomScope"
    }
}
```

But then within that custom scope use another (custom scope), so;

```json
// in some-renative-template-package/pluginTemplates/renative.template.json
{
  "paths": {
      "pluginTemplates": {
          "myOtherCustomScope": {
              "npm": "some-other-renative-template-package",
              "path": "./pluginTemplates"
          }
      }
   },
   "plugins": {
        "my-plugin": { // USES THE SAME PLUGIN
            "source": "myOtherCustomScope",
            ...some-override of the config defined within "myOtherCustomScope"
        }
    }
}
```

```json
// in some-other-renative-template-package/pluginTemplates/renative.template.json
{
    "plugins": {
        "my-plugin": {
            …my-plugin configuration
        }
    }
}
```

So in this case the _"my-plugin"_ plugin from the project's perspective would go;

`project root -> some-renative-template-package -> some-other-renative-template-package`

**Describe the solution you'd like**
RNV to allow for recursive plugin scopes/templates.

**Describe alternatives you've considered**
This wouldn't really give us override/reuse behaviour and could lead to duplication, but I guess an alternative could/would be;

```json
// root project's renative.json
{
  "paths": {
      "pluginTemplates": {
          "myCustomScope": {
              "npm": "some-renative-template-package",
              "path": "./pluginTemplates"
          },
          "myOtherCustomScope": {
              "npm": "some-other-renative-template-package",
              "path": "./pluginTemplates"
          },
      }
   },
   "plugins": {
        "my-plugin": "source:myOtherCustomScope"
    }
}
```

**Additional context**
https://renative.org/docs/api-config#source

**Comment by pavjacko** [comment]
this is now supported in `0.31.0` onwards. so closing this issue
