### ISSUE TITLE
Running Renative on an Android TV over TCP/IP

### ISSUE THREAD

**Issue by stevenmcmanus** [pavjacko/renative#538]
Is there a way to connect to an Android TV over TCP/IP? 

I noticed when running (rnv run -p androidtv) it kills the adb server, then starts it again, meaning I can't use a networked TV for debugging, since I have to connect to it manually each time adb server starts.

**Comment by hosek** [comment]
This can by done by combination of parameters `-d` for running on device and `-t` to specify the target 
`npx rnv run -p androidtv -d -t X.X.X.X:5555` (Haven't used it for a while, so I'm not sure if port is needed or not, have to check)

**Comment by stevenmcmanus** [comment]
Adding the port was the problem. Thank you.
