### ISSUE TITLE
Make start/dev Executable Commands Configurable

### ISSUE THREAD

**Issue by elmpp** [pavjacko/renative#542]
**Is your feature request related to a problem? Please describe.**

We now use a [bespoke server](https://github.com/24i/prd-nxg-sdk-ui/pull/161/files#diff-fc744a68017f9d02ec91f92766d534d1) with Nextjs that is not started via the usual `next start/dev` commands that [RNV assumes](https://github.com/pavjacko/renative/blob/0332da928f9721b5a170e67c5d35323faab6b351/packages/rnv/src/platformTools/web/webNext.js#L149)

**Describe the solution you'd like**

It would be good if we can configure this through RNV (we actually invoke `node src/next/server/index.js` but any child_process compatible format would be doable)

**Comment by pavjacko** [comment]
introduction of rnv engines (#511) will bring support for overriding engine specific tasks ie `run`.

Example config:

```json
{
"engines": {
      "engine-rn-next": {
         "platforms": {
             "web": {
                 "tasks": {
                     "run": {
                         "script": {
                             "node ./src/next/server/index.js"
                         }
                     }
                 }
             }
         }
      }
    },
}
```

Example usage:

`rnv run -p web`
