### ISSUE TITLE
Unable to add third party packages in AndroidTV

### ISSUE THREAD

**Issue by SandeepKharbanda** [pavjacko/renative#544]
Hi

In my current application, I am trying to install third-party packages i.e 'react-native-vlc-player', 'react-native-crypto-js' etc. 
and added it in` renative.json` but still Renative doesn't include these package settings in Android TV `settings.gradle`, `app/build.gradle` & `app/src/main/java/rnv/MainApplication.kt`. 

I have also added these files in Renative's `appConfigs/base` folder with the same hierarchy which is required in AndroidTV but after then, the build stopped working.

**Comment by pavjacko** [comment]
@SandeepKharbanda can you share how your  `./renative.json` section:

```
"plugins": {
       "react-native-vlc-player": { .... },
       "react-native-crypto-js": { .... }
}
```

looks like

**Comment by SandeepKharbanda** [comment]
@pavjacko I have tried with both ways but still, I am getting an error.

`"react-native-vlc-player": "source:rnv"`

```
"react-native-vlc-player": {
      "version": "0.2.3",
      "android": {
        "package": "com.ghondar.vlc.VlcPlayerPackage",
        "path": "node_modules/react-native-vlc-player/android"
      }
    }

```
And, the package is working fine in react-native.

**Comment by aurimasmi** [comment]
replace `android` with `androidtv`

```
"react-native-vlc-player": {
      "version": "0.2.3",
      "androidtv": {
        "package": "com.ghondar.vlc.VlcPlayerPackage",
        "path": "node_modules/react-native-vlc-player/android"
      }
    }
```
