### ISSUE TITLE
NextJS upgrade

### ISSUE THREAD

**Issue by elmpp** [pavjacko/renative#546]
As part of some work with handling responses, we're reliant on a new [NextJs feature](https://github.com/vercel/next.js/releases/tag/v9.4.2)

What would be the best method of upgrading?

**Comment by pavjacko** [comment]
atm nextjs upgrade process is a bit cumbersome. it requires local copy of nextjs with applied changes which then need to be build into dist folder which that can be used for specific file overrides.
@mihaiblaga89 was looking into way how to make it less painful. 
but in general this will require more robust override system with support for diffing and build execution to generate updated dist files
looking into the options
