### ISSUE TITLE
Unable to execute application due to version update

### ISSUE THREAD

**Issue by saubhagya23** [pavjacko/renative#547]
Hi,
I'm developing an application in renative. The version of renative being used in application is 0.28.18 and the version installed in my system is 0.30.0.

My application is using creataApp() method of renative navigation which is not working as the navigation is completely different in 0.30.0. How can I execute the application in 0.30.0 version without having to change the whole navigation altogether.

**Comment by pavjacko** [comment]
@saubhagya23 try to downgrade `renative` plugin to `0.28.18` while keeping `rnv` at `0.30.0`

I can't guarantee it will work but most of the files required for old UI to work are in `renative` runtime library. once downgraded you could also extract all required files from `./node_modules/renative/src` and paste them to your project src and remove unused ones and upgrade up to latest renative. 

most of the legacy functionality sits in `./node_modules/renative/src/Navigation`

**Comment by saubhagya23** [comment]
@pavjacko Thank you for your response. I tried the same but it did not work.
**In future will there be such drastic change in upcoming versions around features like navigation, analytics, live streaming, VAST, etc. ?**

**Comment by pavjacko** [comment]
@saubhagya23 unfortunately this change was necessary to ensure `renative` runtime will stay impartial to specific navigation and let plugins determine how you build your app nav and other functionality. 

Longer I would wait more people would rely on very specific implementation + dependencies making it difficult to upgrade in future.

any future "universal" navigation would be made available trough dedicated plugin. I plan something like `@rnv/navigation` making it optional commitment 

no major breaking changes are expected in `renative` at this point https://renative.org/docs/api-renative
