### ISSUE TITLE
React-Native with Recoil, nothing happens

### ISSUE THREAD

**Issue by paulovitin** [pavjacko/renative#549]
**I know is to soon** to do something like using a [non-official support recoil in react-native](https://github.com/facebookexperimental/Recoil/issues/99#issuecomment-641348817), but I tried to do that, and it worked well for web, however, for webos nothing happens. 

I tried to install ipk and use inspect in debug mode, but I get zero information. The only thing I see is the background color defined in the app. it doesn't close, it doesn't give any kind of error, but I also can't know what's going on. 

**Is there any way to inspect what happens on the webos?**

**Comment by pavjacko** [comment]
@paulovitin if you run your command with `--debug` options it should inject weinre debugger.
so run:

`rnv run -p webos --debug`

and then run separate 

`weinre --boundHost -all-` 

and open web debug console at `http://localhost:8080/client/#anonymous`

you should see something like this:

![Jul-17-2020 11-57-58](https://user-images.githubusercontent.com/4638697/87774551-f7345000-c824-11ea-8052-fe5a9e37dffb.gif)

**Comment by paulovitin** [comment]
@pavjacko 🙏  thanks, man. 

I come back with the answer to what I find out. Maybe it helps someone
