### ISSUE TITLE
Storybook integration

### ISSUE THREAD

**Issue by ali-sao** [pavjacko/renative#55]
Hello Guys , and thank you for the amazing contribution and support .

I have been trying to add storybook to the project , insisting not to eject the platforms with no luck.

Do you have an advice on how to make it possible easily

**Comment by sanderlooijenga** [comment]
@VladislavStechr we can probably look into this, right?

**Comment by pavjacko** [comment]
@ali-sao yeah definitely possible. with few tweaks to rnv. @sanderlooijenga good suggestion, should be walk in the park for @VladislavStechr :D otherwise I could do it sometime next+ weekend.

**Comment by ali-sao** [comment]
@pavjacko , any good luck here?

**Comment by rohan3342** [comment]
@pavjacko any updates?
