### ISSUE TITLE
react-native-splash-screen support to androidtv

### ISSUE THREAD

**Issue by JoaoCEAlmeida** [pavjacko/renative#550]
Hi everyone,

I'm using the package react-native-splash-screen to create a spalshscreen for my app, but i noticed that it only supports android and ios. 

![image](https://user-images.githubusercontent.com/9196047/87661176-1913d100-c758-11ea-866d-342ff8147291.png)

I'm wondering if it's possible to give support to androidtv?

Thanks in advance,
Joao

**Comment by pavjacko** [comment]
@JoaoCEAlmeida yeah it looks like ti should be simple to support. I'll look into adding it in next release. 
you can already try it yourself by extending splash plugin in your `renative.json`

and adding relevant splash files to `./appConfigs/<appID>/base/assets/androidtv

from:

```json
{
    "plugins" {
         "react-native-splash-screen": "source:rnv"
    }
}
```


to:

```json
{
    "plugins" {
         "react-native-splash-screen": {
            "androidtv": {
                "package": "org.devio.rn.splashscreen.SplashScreenReactPackage",
                "mainActivity": {
                    "imports": [
                        "org.devio.rn.splashscreen.SplashScreen"
                    ],
                    "createMethods": [
                        "SplashScreen.show(this)"
                    ]
                }
            }
        },
    }
}
```

**Comment by JoaoCEAlmeida** [comment]
@pavjacko thanks for the fast reply.

I'll try extending the splash-screen to androidtv, using your example. :)
