### ISSUE TITLE
timestampAssest how to use it?

### ISSUE THREAD

**Issue by JoaoCEAlmeida** [pavjacko/renative#551]
Good Morning guys,

I'm currently trying to use the timestampAssest in my renative.json:
![image](https://user-images.githubusercontent.com/9196047/87764814-deb93b00-c80e-11ea-8653-6a17c2cfa4b4.png)

When I enabling it, I'm getting the following warning when I run the app:
![image](https://user-images.githubusercontent.com/9196047/87764874-fabcdc80-c80e-11ea-8d07-9d604e575eac.png)

I'm getting the following error in my the DevTools:
![image](https://user-images.githubusercontent.com/9196047/87764954-1922d800-c80f-11ea-886c-d848c3c52b6b.png)

What I noticed is that my app is trying to access to an app.css file timeStamped, but in my platformBuilds folders I only have the normal app.css and not one timeStamped.
![image](https://user-images.githubusercontent.com/9196047/87768698-740afe00-c814-11ea-850a-5a40e9851ce8.png)

My index.html is the following, as you can see my app tries to access the app-1594973772393.css but this css is not generated:
![image](https://user-images.githubusercontent.com/9196047/87765259-85054080-c80f-11ea-84bc-5d597540d84d.png)

Can anyone help me with this problem? How can I enable the timestampAssest in my project?

Thanks in advance.
Joao

**Comment by pavjacko** [comment]
@JoaoCEAlmeida  Looks like a gap in docs. could you also add this part to your config:

```json
{
  "platforms": {
        "web": {
              "timestampAssets": true,
              "timestampBuildFiles": [
                "public/app.css"
              ]
        }
  }
}
```

**Comment by JoaoCEAlmeida** [comment]
@pavjacko Thanks for the fast reply, it seems to work now.

![image](https://user-images.githubusercontent.com/9196047/87778057-7e33f900-c822-11ea-99bb-eb7f9e83c411.png)
