### ISSUE TITLE
Modifying index.html for web application

### ISSUE THREAD

**Issue by saubhagya23** [pavjacko/renative#554]
Hi,
I need to add some scripts to my web application. So I created a new index.html in **./appConfigs/base/builds/web/index.html** to override **./platformBuilds/[APP_ID]_[PLATFORM]/[FILE_PATH]** .

Also I tried copying **platformBuilds/_shared/template.js** to **platformConfig/builds/_shared/template.js** and modify it.  But it didn't work. It only seems to work when the changes are made directly to index.html in platformBuilds itself.

Can you please suggest any solution to this problem?

**Comment by pavjacko** [comment]
@saubhagya23  ah I see. this seems to be a wrong (legacy) documentation. 

instead of `platformConfig/builds/_shared/template.js`
it should be:
`appConfigs/base/builds/_shared/template.js`

That should work

will update the docs to avoid confusion
