### ISSUE TITLE
Babel-loader dependency missing

### ISSUE THREAD

**Issue by elmpp** [pavjacko/renative#555]
**Describe the bug**
Running latest rnv causes babel-loader problem.

**To Reproduce**
rnv run (web platform)

**Expected behavior**
That `run` works

**Screenshots or copy&paste**

https://hastebin.com/opokidazal

![Screenshot 2020-07-30 at 08 54 11](https://user-images.githubusercontent.com/864612/88890680-41b0c600-d242-11ea-9791-855e826cf3b7.png)

**Additional context**
Same codebase was working ok with `0.29.1-alpha.20`. Rnv reran node_modules install but  have also ran `bootstrap-clean` within our project

**Comment by pavjacko** [comment]
should be fixed in `0.31.3`
