### ISSUE TITLE
Swap Jettifier to full dependency

### ISSUE THREAD

**Issue by elmpp** [pavjacko/renative#558]
**Is your feature request related to a problem? Please describe.**

As it's used in a postinstall, jettify needs to be a full dep, not a devDep. That way we can do `npm i --production`

**Comment by pavjacko** [comment]
there is no need for it as rnv uses dep `react-native` which in turn uses jetifier. `npx jetify` should work out of the box.
this covers both npm and yarn.
on top of that rnv runs jetifier after every node_modules invalidation.
this makes `rnv run -p android` working straight away for new rnv projects without the need for postinstall.
also every project varies and developers can choose how to deal with jetifying in variety of custom ways which is outside of the scope of rnv itself
