### ISSUE TITLE
Text Scroll Issue in TVOS

### ISSUE THREAD

**Issue by jasmeet447** [pavjacko/renative#560]
Hii, I've been trying to make a scrollable text component for tvos like the one we see in terms and conditions box in a lot of applications. The code works fine for android tv but the text doesn't scroll down in tvos. 
The code snippet is as follows:

<ScrollView style={
        {      
        flex: 1,
        paddingTop: getScaledValue(50)
        }}
    contentContainerStyle={{
        alignItems: 'center',
        justifyContent: 'center'
    }}
    removeClippedSubviews={false}
   
 > 
      
< Text style={styles.textH2} >
       This is the text portion that needs to be scrolled ............. 
      
< /Text >
< /ScrollView >

Any Help will be appreciated

**Comment by doneitas** [comment]
As far as I know, tvOS would not scroll or do anything if there are no focusable elements. AndroidTV has that default behaviour to scroll even when there is no focused items but if I'm not mistaken tvOS doesn't have that. So that means this approach will not work on tvOS 🤔
