### ISSUE TITLE
Issue with social sign-in

### ISSUE THREAD

**Issue by saubhagya23** [pavjacko/renative#561]
Hello,

I have to implement social sign-ins like via google, facebook ,etc. in my application. While implementing **google sign-in with OAuth2.0** I was facing this issue. The authorised redirect URIs does not consider _http://0.0.0.0:8080_ as a valid URI. So, We are getting the following error: 
**Error 400: invalid_request**
Permission denied to generate login hint for target domain.

How can we resolve this issue?

**Comment by aurimasmi** [comment]
Hi, 

I been working with those social networks integrations time ago and they used to give ability to authorize your development url which typically is your localhost. 
If it's not the case anymore try to create virtual host which would point to your localhost something like: `127.0.0.1       mylocaloauthtest.com` and authorize it
