### ISSUE TITLE
Upgrade Next JS to 9.5

### ISSUE THREAD

**Issue by sanderlooijenga** [pavjacko/renative#565]
**Describe the solution you'd like**
We would like to use the following features available since 9.5;

- https://nextjs.org/docs/api-reference/next.config.js/redirects
- https://nextjs.org/docs/api-reference/next.config.js/rewrites

**Describe alternatives you've considered**
Using Next standalone (so not as a RNV plugin) 😁 

**Additional context**
https://nextjs.org/blog/next-9-5

**Comment by pavjacko** [comment]
@sanderlooijenga rnv `0.31.0` onwards comes with support for next `9.5.3` (via `engine-rn-next`)

**Comment by sanderlooijenga** [comment]
Great stuff! 🚀
