### ISSUE TITLE
How to programmatically focus a touchable opacity component in tvOS ?

### ISSUE THREAD

**Issue by jasmeet447** [pavjacko/renative#567]
Hi, I've been trying to implement a screen on tvOS that has a lot of touchable opacity elements(say movie cards, list elements, etc) and I want to programmatically focus a particular element when some action is performed, say to programmatically select a particular touchable opacity element on back navigation.
 I tried to implement hasTVPreferredFocus = {true}, but this property only focuses on the nearest focusable view from the top left corner of the screen, despite the item it was set to. 
Any help would be appreciated.

**Comment by RicardasN** [comment]
You could try getting the ref of the TouchableOpacity you're trying to focus and then in-act `touchableRef.current.focus()` or alternatively `touchableRef.current.touchableHandleFocus()`

**Comment by jasmeet447** [comment]
Hi @RicardasN, I tried the suggestions you gave me. Both touchableRef.current.focus() and touchableRef.current.touchableHandleFocus() falied to work, touchableRef.current.touchableHandleFocus() gave an error : [TypeError: undefined is not an object (evaluating '_this.settingRefs[element].current.touchableHandleFocus')] .

When I try touchableRef.touchableHandleFocus() instead, It does call the touchableRef's onFocus() method.But when I press the touchableRef, the onPress() function doesn't get called. When I try to press/swipe (Left, Right, Up, or Bottom). It unexpectedly focuses on some other view (say, if I press up, it focuses on the lowermost touchable opacity) , without calling the onBlur() function of the previously focused touchableRef() and giving me two focused views (I change the border color of a focused view). However, if I tap on ok, I can get its onPress() call of the second focused element. Hope you understood what I tried to tell here.
Kindly help me out with a solution!

**Comment by RicardasN** [comment]
> error : [TypeError: undefined is not an object (evaluating '_this.settingRefs[element].current.touchableHandleFocus')]

It appears that you references are either not set at the moment you try to use it's inner methods or incorrect in later case if you're still getting focus on incorrect item. I would try to make sure the ref exists by trying to console.log it. If it does not then probably playing around with callbacks to await until they are set is your best bet. If ref is set however, but only does not get registered for a millisecond you can try this syntax `touchableRef?.current?.focus?.()`. In some cases of our project we use `touchableRef.current.setNativeProps({ hasTVPreferredFocus: true })`, but in those cases the ref is defined (and is not in a list of refs), because this is called in a listener after menu closes, not on page load.

**Comment by jasmeet447** [comment]
Hi @RicardasN, I made sure the ref exists by trying to console.log it and it does give me the item. However, trying to console.log(touchableRef.current) tells it as an undefined object.
I tried both of the syntaxes: touchableRef?.current?.focus?.() and touchableRef.current.setNativeProps({ hasTVPreferredFocus: true }). None of them could help me solve the issue. 
I want to programmatically select a touchable opacity and make it focused so that I can interact with that object. 
Can you suggest me another alternative ?

**Comment by RicardasN** [comment]
> Hi @RicardasN, I made sure the ref exists by trying to console.log it and it does give me the item. However, trying to console.log(touchableRef.current) tells it as an undefined object.

How are you setting your refs?
`<TouchableOpacity ref={touchableRef} />`
If not then obviously current is undefined. However if you're doing
`<TouchableOpacity ref={e=> this.touchableRef = e} />`
current object does not exist and you can try calling `touchableRef?.focus?.()` or alternatively `touchableRef?.setNativeProps?.({ hasTVPreferredFocus: true })`

**Comment by jasmeet447** [comment]
I'm using 
<TouchableOpacity ref={e=> this.touchableRef = e} />
but calling touchableRef?.focus?.() doesn't help.
Already told: touchableRef?.setNativeProps?.({ hasTVPreferredFocus: true }) sets focus only to the nearest focusable opacity from the top-left corner of the screen irrespective of the touchableRefElement it was called for. So I cannot programmatically select and focus a particular view

**Comment by jasmeet447** [comment]
Hi @RicardasN, I'm now understood your point. I can get touchableRef.current and can call touchableRef.current.touchableHandleFocus(). I can see the touchableRef being focused. However, Nothing happens when I press the element. Even its onPress() does not get called. 
Any ideas on how I can resolve this?

**Comment by RicardasN** [comment]
> Any ideas on how I can resolve this?

Sorry, but no clue on this one, never experienced this issue myself

**Comment by aurimasmi** [comment]
`hasTVPreferredFocus` is the way to do that properly. You can even set it programatically by accessing native props:

```
<TouchableOpacity ref={myRef} />
```
```
myRef.current.setNativeProps({ hasTVPreferredFocus: true });
```
Also be aware that there is weird 1 sec delay for tvOS setting `hasTVPrefferedFocus`. You can use this solution as a reference to fix it https://github.com/react-native-community/react-native-tvos/pull/2. I assuming you're not using react-native-tvos so I just would recommend you to override RCTTVView.m you can do that easily with Renative.

**Comment by DevineDecrypter** [comment]
Try using a timeout of 10-50ms before focusing, it may help

**Comment by taj567** [comment]
<TouchableOpacity
      ref={ref}
      hasTVPreferredFocus={focused}
      onFocus={onFocus}
      onBlur={onBlur}
      style={[styles.container]}
    >
      <View style={[styles.animatedContainer]}>
        <Text style={styles.value}>{data}</Text>
      </View>
    </TouchableOpacity>

Facing the issue like after navigation to sidebar and closing it am navigating  to (n - 1) row first element.
 const onCloseSideBar = useCallback(() => {
    // console.log(activeNode,"activeNode")
    // activeRow?.touchableHandleFocus?.();
      // activeRow?.focus?.();
    // alert("closed")
    openSidebar(false);
    console.log("On Close Sidebar!")
  }, [activeNode]);

tried with the focus also not working.

https://github.com/flexn-io/renative/assets/74459204/ee89bd97-eb76-4679-a320-85fe737a44ca
