### ISSUE TITLE
In react-player, How can we add codec to support .mkv, 4k Videos and live stream URLs for tvOS?

### ISSUE THREAD

**Issue by tanujttn** [pavjacko/renative#568]
**Current Behaviour:**
I am unable to play .mkv, 4K & live URLs on tvOS as these URLs are working on other platforms.

**Environment:**
URL attempting to play: http://tivix.eu:8000/movie/demo4/1SVHifcnbO/88814.mkv

**Comment by pavjacko** [comment]
@tanujttn question of supporting specific video formats is usually outside of the scope of ReNative itself. video playback can be achieved by installing once of available community plugins ie https://github.com/react-native-video

Wrt your issue there is similar issue opened here:

https://github.com/react-native-video/react-native-video/issues/1718
