### ISSUE TITLE
How to trigger onkeydown in android tv? 

### ISSUE THREAD

**Issue by ridhimagupta259** [pavjacko/renative#572]
Hi,

I am not able to trigger onkeydown method in Android tv unlike in case of webos and tizen it is working fine .

**Is there a way to trigger it in androidtv?**

**Comment by aurimasmi** [comment]
Are you using [TVEventHandler](https://reactnative.dev/docs/building-for-tv)?

**Comment by ridhimagupta259** [comment]
@aurimasmi  yes

**Comment by aurimasmi** [comment]
Show me code example what are you trying to achieve for better understanding. Because TVEventHandler should do the job

**Comment by ridhimagupta259** [comment]
@aurimasmi 
TVEventHandler does not support key code for colour buttons(red,blue,green,yellow) of android tv remote .

Thats why i was thinking maybe using onkeydown i can add colour keycodes conditions.

I am using TVEventHandler like this

`this._tvEventHandler = new TVEventHandler();
        this._tvEventHandler.enable(this, function (cmp, evt) {
            if (evt && (evt.eventType === 'right' || evt.eventType === 'left' || evt.eventType === 'up')) {
                cmp._handleEvent(evt.eventType)
            }
        });`

but tveventhandler only supports the following keycodes

`private static final Map<Integer, String> KEY_EVENTS_ACTIONS =
MapBuilder.<Integer, String>builder()
.put(KeyEvent.KEYCODE_DPAD_CENTER, "select")
.put(KeyEvent.KEYCODE_ENTER, "select")
.put(KeyEvent.KEYCODE_SPACE, "select")
.put(KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE, "playPause")
.put(KeyEvent.KEYCODE_MEDIA_REWIND, "rewind")
.put(KeyEvent.KEYCODE_MEDIA_FAST_FORWARD, "fastForward")
.put(KeyEvent.KEYCODE_DPAD_UP, "up")
.put(KeyEvent.KEYCODE_DPAD_RIGHT, "right")
.put(KeyEvent.KEYCODE_DPAD_DOWN, "down")
.put(KeyEvent.KEYCODE_DPAD_LEFT, "left")
.build();`

is there any other way for the support of color keys(red,blue,green,yellow)?

**Comment by aurimasmi** [comment]
Right, yes TVEventHandler doesn't support that since tvOS and ATV remote controllers doesn't have those buttons. There is one lib around which captures keyboard and remote controller events. I never tried it but it might be helpful for you: https://github.com/kevinejohn/react-native-keyevent

**Comment by ridhimagupta259** [comment]
I tried using this lib but i am not able to make the configuration changes in MainActivity.java file as it says
