### ISSUE TITLE
How to trigger onkeyup  on samsung tizen 

### ISSUE THREAD

**Issue by CharlesNjau** [pavjacko/renative#573]
For some risen when deploying renative apps on real samsung televeision the arrows or any butto  events can't be triggered how can i resolve this

**Comment by ali-sao** [comment]
You have to register the key first.
tizen.tvinputdevice.registerKey(key)

**Comment by ali-sao** [comment]
Hello @CharlesNjau , you should register the key first :

`tizen.tvinputdevice.registerKey(key)`

**Comment by CharlesNjau** [comment]
> Hello @CharlesNjau , you should register the key first :
> 
> `tizen.tvinputdevice.registerKey(key)`

Can you provide an example cause i have tried to register this but still i am not able to move up and down

**Comment by SandeepKharbanda** [comment]
@CharlesNjau : You have to add on onKeyDown prop on your View where you'll get the keycodes. 

```
<View
                onKeyDown={(e) => {
                    switch (e.keyCode) {
                        case 13: {
                            //OK button
                            return;
                        }
                        case 39: {
                            //Right arrow button
                            return;
                        }
                        case 37: {
                            //Left arrow button
                            return;
                        }
                        case 38: {
                            //UP arrow
                            return;
                        }
                        case 40: {
                            //DOWN arrow
                            return;
                        }
                    }
                }}>
            </View>

```
For registerKey, please use the below link for your reference
https://developer.samsung.com/smarttv/develop/guides/user-interaction/remote-control.html

**Comment by chmiiller** [comment]
Maybe this one can be closed
