### ISSUE TITLE
Tizen platform builds are failing.

### ISSUE THREAD

**Issue by itsmefreitas** [pavjacko/renative#578]
**Describe the bug**

**To Reproduce**

1. Start a new rnv project with rnv new;
2. Cd to the newly created project folder and issue the command: `rnv run -p tizen`;
3. Check the tizen cli logging output attached in the Screenshots or copy&paste section.

**Expected behavior**
Rnv run and/or build scripts should produce valid targets.

**Screenshots or copy&paste**
Logger output from Tizen cli, written to when running `rnv run -p tizen`: [cli.log](https://github.com/pavjacko/renative/files/5260726/cli.log)

**Desktop (please complete the following information):**

-   OS: Windows 10 Pro
-   Node Version v12.16.1
-   RNV Version 0.30.4

**Additional context**
This seems to happen when generating certificate profiles and across several versions of node and/or rnv, has occurred on more than one machine. Judging from the Java exception trace, this seems to involved arguments not being properly passed to the relevant class method, i.e. `org.tizen.ncli.subcommands.sign.SignCLICommand.getSigningProfile`, when signing build products. This happens on both new and existing installations of Tizen SDK.

**Comment by damakvarshney** [comment]
Same issue with me Help someone,
I just started working on it,
Encourage me !!

**Comment by pavjacko** [comment]
@damakvarshney @itsmefreitas looking into this. 
@damakvarshney are you also on same env? (Win vs Mac) SUMMARY box from command line output once error occurred would help to clarify these quickly

**Comment by damakvarshney** [comment]
@pavjacko Sir, I am working on Windows where i have raised a issue here ..

---------
� $ rnv run -p tizen - ERRROR! COMMAND:

C:\Users\ok\tizen-studio\tools\ide\bin\tizen.bat package -- C:\Users\ok\Desktop\Practice\ReNative\cuisine\platformBuilds\helloworld_tizen\build -s RNVanillaCert -t wgt -o C:\Users\ok\Desktop\Practice\ReNative\cuisine\platformBuilds\helloworld_tizen\output

FAILED with ERROR:

Distributor1 password: An error has occurred. See the log file tizen-sdk\tools\ide\cli.log.

**Comment by damakvarshney** [comment]
I found the solution .... the problem is with distributor password in tizen studio which can be solved just by going to tizen studio and then to certification manager and write distributor password to "tizenpkcs12passfordsigner"

Good luck

**Comment by pavjacko** [comment]
@damakvarshney thank you for reporting the solution back!
