### ISSUE TITLE
Web browser assets available only at root.

### ISSUE THREAD

**Issue by saubhagya23** [pavjacko/renative#586]
Hello,
I'm building a web application using **renative** version **0.30.4.** 

When navigating to urls such as _http://localhost:8080/user/:userId_ , it searches resources at path _http://localhost:8080/users/assets/<Asset>_ and does not find any asset. The **assets** are available only at the **root path** i.e. _http://localhost:8080/assets/<Asset>_.

For such navigation paths, how can we make the assets available?

**Comment by kasinskas** [comment]
in `appConfigs/.../renative.json` you should see 
```
"web": {
            ...
            "buildSchemes": {
                "debug": {
                    ...
                    "webpackConfig": {
                        "baseUrl": ""
                    }
                },
              ...
```

Assets should become available if you change `"baseUrl": ""` to `"baseUrl": "/"`

**Comment by saubhagya23** [comment]
@kasinskas Changing the _**appConfigs/.renative.json**_ didn't work for me. However changing **baseUrl** in **generateConfig()** method in _**/appConfigs/base/builds/_shared/configs.js**_ worked for me. 

Thank you.
