### ISSUE TITLE
How can we run tvOS build on real Apple TV device?

### ISSUE THREAD

**Issue by SandeepKharbanda** [pavjacko/renative#589]
I am trying to run my app on a physical Apple TV 4k device but every time I run the command, it fails. 

`rnv run -t "APPLE_TV_Name" -p tvos`

I even tried the same thing with XCode as well but after then I got the Metro bundler error.

And how can we also add a certificate & provisioning profile in our tvOS project?

**Comment by pavjacko** [comment]
@SandeepKharbanda you need to use `-d` or `--device` option to mark your target as physical device.
rnv will try to find existing devices available.

NOTE: you need to make sure 
- your apple tv is connected to same wifi as your computer 
- you have connected it to your dev machine via usb c cable.

you can check whether your apple tv is visible in xcode or via:

```
rnv target list -p tvos
```

so your command should be:

```
rnv run -p tvos -d
```

WRT Provisioning profiles, there are 2 ways. automatic and manual.

Automatic: 

ensure that you have following properties set in `./appConfigs/<APP_ID>/renative.json`

```
"platforms": {
    "tvos": {
      "teamID": "<YOUR_APPLE_TEAM_ID>",
      "provisioningStyle": "Automatic",
      "signingConfig": "Debug"
    },
  }
```

Manual:

```
"platforms": {
    "tvos": {
      "provisioningStyle": "Manual",
      "codeSignIdentity": "iPhone Distribution",
      "provisionProfileSpecifier": "<NAME_OF_PROVISIONING_PROFILE>",
    },
  }
```
