### ISSUE TITLE
[web] load custom font in css file is not woking

### ISSUE THREAD

**Issue by whdgmawkd** [pavjacko/renative#592]
font file is loacted in 'src/fonts/fontname.woff'
css 
```
@font-face{
    font-family: 'fontfamily';
    src: url('./fonts/fontname.woff') format('woff');
}
```

but browser cannot load woff because './asset/asset/randomhex.woff' is not found

where should i put woff file?

**Comment by pavjacko** [comment]
@whdgmawkd 
just released the patch to support woff extensions. could you try to run this in `rnv@0.31.1`

what you need is to place your fontname.woff in `./appConfigs/base/fonts` folder.

rnv takes care of the rest for you.

in your code you simply use it as standard font family:

```js
const styles = StyleSheet.create({
    someComponent: {
        fontFamily: 'Your-Custom-Font-Name`,
    }
});
```

behind the scenes explanation:

rnv loads all font files in the folder:

`packages/app/appConfigs/base/fonts`

based on your renative.json prop you can configure:

```
"includedFonts": ["*"],
```

then generates:
`packages/app/platformAssets/runtime/fontManager.web.js`
and
`packages/app/platformAssets/runtime/fonts.web.js`
