### ISSUE TITLE
Replace weinre with chii

### ISSUE THREAD

**Issue by EyMaddis** [pavjacko/renative#596]
**Is your feature request related to a problem? Please describe.**
Weinre is a very old project that is no longer maintained. I found https://github.com/liriliri/chii which uses the new UI from the chrome developer tools.

It seems to work pretty nicely.

**Describe the solution you'd like**
Use `chii` instead or in addition to `weinre`.

I began implementing a PR supporting both. Would you be interested? 
The current problem is the automatic opening of the browser cannot open the screen for that app, but an overview screen for all connections, because the fragment in  `...target/target-script-min.js#${platform}` is not supported by chii.

**Comment by EyMaddis** [comment]
Related but a bit off topic: For tizen the weinre window opens *every time*, even without `--debug`. Is that by design or a bug?

**Comment by pavjacko** [comment]
@EyMaddis that looks definitely interesting! 

wrt to --debug it's a bit of 50/50 here. by default, when you run you app in non production mode you usually get console support out of the box (react-native console itself,  web inspector console etc) with tizen you get nothing. so idea was to have natural console output friendly env setup out of the box as that's what you do in non production env.. develop actively.

that ofc puts a question-mark on the purpose of `--debug` which is leaning more towards "breakpoints" and active debugging. it is definitely a blurry line when you put multiple platforms side by side. 

Open for feedback.

**Comment by EyMaddis** [comment]
I opened https://github.com/pavjacko/renative/pull/598. :) 

`--debug`: I get where this is coming from. I was very confused that the behavior was different on that platform. I also find it annoying that my browser was opening every time (especially while working on webpack configs).
