### ISSUE TITLE
[rnv 0.31] Broken TypeScript support

### ISSUE THREAD

**Issue by rroslaniec** [pavjacko/renative#599]
**Describe the bug**
After update from 0.30 to 0.31 typescript files are not transpiled and it causes error on compiling time.

**To Reproduce**
1. Create new project (e.g. blank template)
2. Rename ./src/app/index.js to ./src/app/index.tsx

**Expected behavior**
Project should compile correctly and it should work

**Screenshots or copy&paste**

![image](https://user-images.githubusercontent.com/3448993/96338260-011c5800-108d-11eb-9150-9ea2536ee10d.png)
**Desktop (please complete the following information):**

-   OS: OSX
-   Node Version v14.13.1
-   RNV Version 0.31.1

**Comment by pavjacko** [comment]
@rroslaniec could you try `0.31.2` . should be fixed

**Comment by rroslaniec** [comment]
@pavjacko works, thanks for fast fix 🚀
