### ISSUE TITLE
Generating source maps

### ISSUE THREAD

**Issue by ix42** [pavjacko/renative#600]
Is there an easy way to generate source maps automatically during the web docker export process?

Thank  you

**Comment by pavjacko** [comment]
@ix42 from rnv `0.31.3` you can extend webpack directly in renative.json. if you add this to your web platform config:

```
  "web": {
            "webpackConfig": {
               "extend": {
                  "devtool": "source-map"
               }
            }
        },
```

it will produce source maps in your web build.

**Comment by ix42** [comment]
Thank you for the feature (and the help)
