### ISSUE TITLE
Webpack typescript config for web application

### ISSUE THREAD

**Issue by marjen0** [pavjacko/renative#601]
Hi, 

When running web project which is written in typescript with npx rnv run -p web I get the following error.
**_You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders_**
Android and AndroidTV projects work just fine.

I would like to ask where and how do I config my project to use typescript?

Thanks.

**Comment by pavjacko** [comment]
@marjen0 which rnv version are you running? you need to run rnv `0.31.2` or higher

NOTE: ideally always provide SUMMARY box from your console output. helps speed up issue resolutions

**Comment by marjen0** [comment]
Updating rnv to 0.31.2 version fixed the issue, thanks again.
