### ISSUE TITLE
How to use dynamic injectors?

### ISSUE THREAD

**Issue by rroslaniec** [pavjacko/renative#603]
I've tried to manage inject some env variables (for example API domain). By docs (https://renative.org/docs/config-overview#dynamic-injectors) it is easy:

1. add variable in common object in renative.*.json (let's assume that is renative.local.json in root folder)
2. in ANY file use {{{{configProps.API}}}}

But it doesn't work with ***.ts** files, what else I can do?

**Comment by pavjacko** [comment]
@rroslaniec could you be more specific?

- what exactly do you add to renative.json?
- how exactly does your ts file look like?
- where is your ts file located?

**Comment by rroslaniec** [comment]
sure, so:

- added API key in renative.json common property.
- ts file (./src/api/base.ts): 
```ts
class APILayer {
   static BASE_URL = "{{{{configProps .API}}}}";
}
```

**Comment by pavjacko** [comment]
@rroslaniec sorry missed this one to answer
dynamic injects only work for injected files ie ones in `./appConfigs/*` and `renative.json` . what you referring is `src` folder which is not injected. it is actual source of your app.

if you want to inject some property from `renative.json` you can still do it by importing `./platformAssets/renative.runtime.json` into your code in src.

you can inject properties from `renative.json` into  `./platformAssets/renative.runtime.json` by adding `runtime` object in your `renative.json`

Example:

```json
{
  "common": {
    "license": "MIT",
    "includedPlugins": [
      "*"
    ],
    "includedFonts": [
      "*"
    ],
    "backgroundColor": "#111111",
    "runtime": {
      "welcomeMessage": "Hello ReNative!"
    }
  }
}
```

will add following property to  `./platformAssets/renative.runtime.json` 

```json
{
    "welcomeMessage": "Hello ReNative!"
}
```

**Comment by rroslaniec** [comment]
For sure it would be nice to add more detailed info in docs about that https://renative.org/docs/next/advanced/guide-overview#dynamic-injectors. Personally I thought it works in whole project.
