### ISSUE TITLE
ADB via Wifi without USB

### ISSUE THREAD

**Issue by YeonV** [pavjacko/renative#607]
Hey guys,

first of all: AMAZING project!!

Im trying to build for wearos. I've got my watch in ADB wifi debug and i can conntect with 
```adb connect<ip>:<port>```
I can also connect inside Android Studio.
But if I try to rnv like said [here](https://github.com/pavjacko/renative/issues/296#issuecomment-573109542):
```rnv run -p androidwear -d -t <ip>:<port>```
The Step with ```adb kill-server``` and  ```adb start-server``` disconnects the adb wifi connection, so I get an empty output of ```adb devices -l``` and the rest of the script cannot find my device.
Info: I do NOT have a working ADB via USB connection, so I need a wifi only solution.

Is there a way to skip the kill-server or hook into that part and add a adb connect after start-server?

Sorry for this noob-ish question and thank you very much
Yeon

![renative](https://user-images.githubusercontent.com/28861537/97164287-32c6aa80-1782-11eb-9b2b-6074c5e72036.png)

**Comment by pavjacko** [comment]
@YeonV thx!. wrt your issue, could you skip port (rnv adds it for you). You also don't need `-d` as you specifying exact target

So could you try command in this format:

`rnv run -p androidwear -t 192.168.1.50`
