### ISSUE TITLE
Modify Gradle Wrapper Version from 5.5 to 6.3 AndroidTV

### ISSUE THREAD

**Issue by arcalumis** [pavjacko/renative#608]
I can't find where to set or modify the gradle wrapper properties to choose a different version.

The error I'm seeing is

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

Which I can modify by ejecting the app and changing the config in androidtv/gradle/wrapper/gradle-wrapper.properties

When I try to reconnect the app to build, it doesn't seem to have persisted as I get the same error.

I don't see anything about configuring this value in the docs.

Any help would be appreciated.

Thank you

**Comment by hosek** [comment]
Hi, gradle version cannot be changed via config for now, but you can use build injection.
Edit the `gradle-wrapper.properties` file and put it in your appConfig: 
![Screenshot 2020-10-26 at 20 29 08](https://user-images.githubusercontent.com/9611327/97219341-28300380-17ca-11eb-8d35-ff8bb9a1cd9d.png)
Then this file will be automatically injected into your project androidtv folder
