### ISSUE TITLE
Android and AndroidTV builds failing while using JDK 14/15

### ISSUE THREAD

**Issue by zatlodan** [pavjacko/renative#619]
**Describe the bug**

While trying to run a renative project on Android or AndroidTV platform with the Java JDK 14 or 15 the following error appears:
![image](https://user-images.githubusercontent.com/43817853/100229311-55381900-2f24-11eb-80d2-b799219a43e0.png)

**Possible solution**

I have updated the gradle distribution and gradle build tools in the `templates/platforms` and created a showcase fix on a branch which worked for our project: https://github.com/pavjacko/renative/pull/618

**To Reproduce**

1. Install the latest JDK from [official site](https://www.oracle.com/java/technologies/javase-downloads.html)
2. Create a new rnv project `rnv new`
3. Try to run the project on android or andoirdtv `npx rnv run -p android` or `npx rnv run -p androidtv`

**Expected behavior**

The project should build without errors

**Desktop (please complete the following information):**

-   OS: osx
-   Node Version: 14.15.1
-   RNV Version: 0.31.2 and 0.31.0-alpha.23

**Comment by pavjacko** [comment]
@zatlodan added support for customising this directly via `renative.json`  included in `0.32.0-alpha.21`

Example of your use case:

```
"platforms": {
    "android": {
        "gradleBuildToolsVersion": "4.1.0",
        "gradleWrapperVersion": "6.7.1"
    }
}
```
