### ISSUE TITLE
Dependencies with different versions

### ISSUE THREAD

**Issue by ix42** [pavjacko/renative#620]
Is it possible to include different versions of a dependency for web and ios for example?
Thank you

**Comment by pavjacko** [comment]
@ix42  do you mean different npm versions in single project?
more specific example would help here

**Comment by ix42** [comment]
Yes, different dependency versions in a single project, say some library 1.0.0 on web and 1.0.1 on mobile. 
I tried via appConfig renative.json plugins, but i think i'm doing something wrong and did not figure out how it should work

**Comment by pavjacko** [comment]
I see. yes you can only define single npm dep atm. but it should be possible to add this feature. but afaik you can do this in npm (under one project) only if you use aliases ie:

```
"dependencies": {
    "my-library": "npm:my-library@1.0.0",
    "my-library-1.0.1": "npm:my-library@1.0.1",
}
```

and then require them in the code accordingly.

If that's what you after it should be straightforward to add this so you could define your plugin in format like this:

```
"my-library": {
    "version": "1.0.0"
    "ios": {
        "version": "1.0.1",
        "npmAlias": "my-library-1.0.1"
    }
}
```

additionally it could be possible to define more dynamic aliasing in babel so you only require `my-library` no matter which platform you run but I'd need bit more time to investigate it.

**Comment by ix42** [comment]
Thank you, i think including via npmAlias will solve my problem

**Comment by pavjacko** [comment]
@ix42 you can try following example. this should allow support for different plugin versions under same project:

```
//renative.json

"my-library": {
    "version": "1.0.0",
    "npm": {
        "my-library-1.0.1": "npm:my-library@1.0.1"
    },
    "ios": {
        "path": "/node_modules/my-library-1.0.1/ios"
    }
}

// src/myLib.js

export * from 'my-library'

// src/myLib.ios.js

export * from 'my-library-1.0.1'

// src.app.js

import { *** } from './myLib'

```

**Comment by ix42** [comment]
Thank you, this solution looks good
