### ISSUE TITLE
How to setup Tizen SDK and webOS SDK for macOS 11.0.1 (Big Sur)

### ISSUE THREAD

**Issue by tvotan** [pavjacko/renative#627]
> OS: macOS Version 11.0.1
> Oracle VirtualBox: Version 6.1.16 r140961 (Qt5.6.3)

Hi,

I need some assistance to install Tizen SDK and LG webOS SDK. I followed these instructions:
- https://developer.tizen.org/ko/development/tizen-studio/configurable-sdk
- http://webostv.developer.lge.com/sdk/installation/

But anyway I get error messages like these:

**webOS**

<img width="260" alt="Screenshot 2020-12-10 at 17 00 06" src="https://user-images.githubusercontent.com/39995527/101796995-d2a97f00-3b09-11eb-843d-e5f3668ffb41.png">

**Tizen**

<img width="1582" alt="101662428-cb22a100-3a49-11eb-803e-e8f11130e316" src="https://user-images.githubusercontent.com/39995527/101797377-40ee4180-3b0a-11eb-86de-e9dfa4a0b4fc.png">

Can anyone help me please?

**Comment by pavjacko** [comment]
@tvotan yes this is known issue with big sur and tizen SDK/IDE. 

I managed to get around above popups by manually enabling each module in settings security tab (around 10-15 popups!)
However tized IDE would still not launch properly
Ironically SDK manager does work

In the nutshell, Tizen + big sur is a mess ATM.

one of the issues tracking this:
https://forum.developer.samsung.com/t/tizen-studio-problem-on-macos-big-sur/9410

Samsung is promising fix before end of the year. let's see

**Comment by pavjacko** [comment]
@tvotan I can confirm that latest release of Tizen IDE/SDK (Dec 21, 2020) is finally working with big sur 🎉 

https://developer.tizen.org/ko/development/tizen-studio/download
