### ISSUE TITLE
[webos] cli fails when running webos ERROR in Template execution failed: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by TheDuc** [pavjacko/renative#629]
**Describe the bug**
When running `npx rnv run -p webos -t Target`, I get `ERROR in Template execution failed: RangeError: Maximum call stack size exceeded`

**To Reproduce**

1. Run command `npx rnv run -p webos -t Target`
2. See error `ERROR in Template execution failed: RangeError: Maximum call stack size exceeded`

**Expected behavior**
To run the app without errors.

**Desktop (please complete the following information):**

-   OS: Big Sur 11.0.1
-   Node Version 14.7.0
-   RNV Version 0.32.0-alpha.23

**Additional context**
This issue is related to https://github.com/TehShrike/deepmerge/issues/221
I think this can easily be fixed by using "is-plain-object" as isMergeableObject
https://github.com/pavjacko/renative/blob/fe34693b4ad5ca4f6f3b8eb0a7bfe49c3164f35c/packages/rnv-engine-rn-web/templates/platforms/_shared/template.js
```
    const config = merge(DEFAULT_CONFIG, options, {
        isMergeableObject: isPlainObject
    });
```

**Comment by pavjacko** [comment]
@TheDuc ok finally managed to replicate it but only after upgrading to webpack 4.44.2 :) 
but fixed by using good old fashioned Object.assign

Let me know if that worked for you!  `0.32.0-alpha.25`
