### ISSUE TITLE
Issue with using react-native-video player plugin

### ISSUE THREAD

**Issue by Aravind-k08** [pavjacko/renative#683]
Hi,
While trying to add the react-native-video player plugin for native video playback, we wanted to use android-exoplayer libraries available as part of the react-native-video plugin. However, since the settings.gradle is auto generated while building for android platform, we were unable to edit it manually. 
The code right now is:
project(':react-native-video').projectDir = new File('/Users/aravind.k08/Rainbow-rnv/node_modules/react-native-video/android')
The expected code is: 
project(':react-native-video').projectDir = new File('/Users/aravind.k08/Rainbow-rnv/node_modules/react-native-video/android-exoplayer')

Is there any way to customise this in settings.gradle using the renative.json?

**Comment by Aravind-k08** [comment]
Using the following:
"react-native-video": "5.0.2",
"renative": "0.31.3",

**Comment by ngethe** [comment]
Hi @Aravind-k08  how did this go did you solve it ?
looking for complete streaming solution let me know if you have it

**Comment by Aravind-k08** [comment]
Hi @ngethe yes we did solve this. I will ask my colleague to share the snip

**Comment by sreeramsanal** [comment]
Hi @ngethe  we resolved the problem by adding the following in renative.json file: 
"react-native-video": {
            "version": "5.0.2",
            "android": {
                "package": "com.brentvatne.react.ReactVideoPackage",
                "path": "node_modules/react-native-video/android-exoplayer"
            },
            "androidtv": {
                "package": "com.brentvatne.react.ReactVideoPackage",
                "path": "node_modules/react-native-video/android-exoplayer"
            }
        },

**Comment by ngethe** [comment]
Thanks for the feedback

**Comment by mihaiblaga89** [comment]
considering closed
