### ISSUE TITLE
External lib to Renative

### ISSUE THREAD

**Issue by jonatasts** [pavjacko/renative#698]
How can I add an external lib to renative?

**Comment by RicardasN** [comment]
If by lib you mean plugin, then this is what you're looking for - https://github.com/pavjacko/renative/tree/develop/packages/rnv/pluginTemplates

Here you can add the plugin to `renative.plugins.json` file, don't forget to link it though as auto linking is disabled at the moment. 
If you need to add tvOS support or override something that does not work by default you can also override the plugins here. Just add a folder `pluginName/overrides/..(whatever you're overriding, but it needs to match the original plugin structure)`

P.S. you don't necessarily need to wait for your PR to be merged to renative, you can also use pluginTemplates locally next to your own project. In our case it's published as separate NPM package as it used in multiple places.
![image](https://user-images.githubusercontent.com/36963057/125062438-0e63f180-e0b7-11eb-88a0-d25656255462.png)
