### ISSUE TITLE
How to focus a touchable opacity component in a FlatList in tvOS

### ISSUE THREAD

**Issue by jonatasts** [pavjacko/renative#705]
![image](https://user-images.githubusercontent.com/49213782/129034104-1c1c88d9-ff45-4a9b-b398-1b8ad5c805fb.png)

I'm focusing on a FlatList button that selects the video's caption, but when I open the modal again and navigate between the buttons, the focus goes to the top of the list instead of the button that is focused.

https://www.loom.com/share/e572acde4ee94319ad3106c394b8e238

![image](https://user-images.githubusercontent.com/49213782/129034586-d90c0954-8bf3-4395-a202-02396389a36f.png)
![image](https://user-images.githubusercontent.com/49213782/129034719-94ddf71e-fc64-45f4-967c-63772ce6f911.png)
![image](https://user-images.githubusercontent.com/49213782/129034868-e70376ab-af6d-43c3-add5-0600abf7cd86.png)
![image](https://user-images.githubusercontent.com/49213782/129034947-f7f28f0a-08af-4afc-8693-a795353f17bb.png)

When I select a subtitle by pressing the button, the modal closes and when it is opened again the selected subtitle button appears focused, but when pressing the up arrow the focus goes to the top of the list or the focus goes down to the end of the list. instead of starting from the button that is focused.

**Comment by jonatasts** [comment]
I used scrollview instead of FlatList, but the same thing happened before.

**Comment by doneitas** [comment]
Hey. Not really sure what causes this issue, but I've noticed interesting choice here with button ref:

![image](https://user-images.githubusercontent.com/36989231/129547800-478619db-d421-4351-b58a-eb839313b8f9.png)

Idk if it has anything to do with your issue but maybe it would be better to have an array of buttonRefs and control these modal buttons that way, instead of providing the single buttonRef to different button every time focus changes 🤔

**Comment by doneitas** [comment]
> Tried with an array, but it didn't work either.
> Instead of FlatList I just used ScrollView and used react-native's native modal instead of this lib.
> The first button is now focused, previously none of the buttons were focused when displaying modal unless you navigated between buttons.
> But I couldn't focus on a specific button and navigate from it, the first one is always focused and I navigate from it.

Did you try `hasTVPreferredFocus` prop?

**Comment by jonatasts** [comment]
> > Tried with an array, but it didn't work either.
> > Instead of FlatList I just used ScrollView and used react-native's native modal instead of this lib.
> > The first button is now focused, previously none of the buttons were focused when displaying modal unless you navigated between buttons.
> > But I couldn't focus on a specific button and navigate from it, the first one is always focused and I navigate from it.
> 
> Did you try `hasTVPreferredFocus` prop?

**Comment by jonatasts** [comment]
> > Tried with an array, but it didn't work either.
> > Instead of FlatList I just used ScrollView and used react-native's native modal instead of this lib.
> > The first button is now focused, previously none of the buttons were focused when displaying modal unless you navigated between buttons.
> > But I couldn't focus on a specific button and navigate from it, the first one is always focused and I navigate from it.
> 
> Did you try `hasTVPreferredFocus` prop?

I tried that too but it keeps focusing on the first button and navigation also starts from the first button.
And in this case with `hasTvPreferredFocus` the bug of showing as if there were two buttons selected happened again.
So, as a workaround, I let autofocus on the first button happen and reordered the list by moving the selected button to the first one in the list.
