### ISSUE TITLE
Streaming App multi-platform development 

### ISSUE THREAD

**Issue by ngethe** [pavjacko/renative#718]
Hi I am looking for someone that has done a streaming application at least for WebOS, Tizen TV, Android TV please inbox me if you have a ready or almost ready streaming application

**Comment by Luiz-Monad** [comment]
Hello, I have an almost ready player and streaming services. You can contact me for business at my mail address in my github profile.

**Comment by ngethe** [comment]
Thanks @Luiz-Monad check your email
