### ISSUE TITLE
k is not defined installing plugins

### ISSUE THREAD

**Issue by Kikketer** [pavjacko/renative#72]
**Problem**:
I get a `k is not defined` error when attempting to add a plugin.

**Steps to reproduce**:
1. run `yarn global add renative@latest`
2. run `rnv app create`
3. I used "test" for name and picked `ios` and `android` as the targets
4. `cd test/` (the name of the app)
5. run `rnv plugin add`
6. I tried 20 and 22, both throw the error

**Error**:
```
Installing:
- react-native-svg v(9.4.0)

readline.js:1020
            throw err;
            ^

ReferenceError: k is not defined
    at /Users/n0148094/.config/yarn/global/node_modules/renative/rnv-cli/dist/cli/plugin.js:1:3554
```

**Versions**
Node: v8.12.0
rnv: 0.22.0-alpha.4

**Comment by pavjacko** [comment]
@Kikketer thx for the bug report! fixed in `0.22.0-alpha.5`
