### ISSUE TITLE
react-native-snap-carousel not working with Tizen and WebOS

### ISSUE THREAD

**Issue by phillipcmittmann** [pavjacko/renative#720]
**Describe the bug**
The package works as intended on android and iOS, but breaks on Tizen and WebOS.

**To Reproduce**

1. Run command `npx rnv plugin add react-native-snap-carousel` (ran `yarn add react-native-snap-carousel` after, same result)
2. Run command `npx rnv run -p tizen --hosted`
3. Run command `npx rnv run -p webos --hosted`

**Expected behavior**
Not present errors on the console.

**Screenshots or copy&paste**

![Captura de Tela 2021-11-03 às 15 35 22](https://user-images.githubusercontent.com/54452466/140171795-969a8f6b-a90f-4a79-94be-f70e24b64a61.png)

**Desktop (please complete the following information):**

-   OS: osx 10.15.7
-   Node Version v14.18.1
-   RNV Version 0.31.3

**Comment by doneitas** [comment]
I've never tried using this library on these platforms (tizen, webos), but I doubt that it supports these platforms and that it would work properly

**Comment by phillipcmittmann** [comment]
> I've never tried using this library on these platforms (tizen, webos), but I doubt that it supports these platforms and that it would work properly

The thing is, the docs says that the plugin works on these platforms, as the image bellow

![Captura de Tela 2021-11-04 às 08 33 22](https://user-images.githubusercontent.com/54452466/140306632-be3f85b2-6875-4c7a-93d7-f1a0a9339723.png)

Im trying to do something like the example from here https://github.com/NoriginMedia/react-spatial-navigation, but with FlatList since Im not sure the amount of items i will have. And Im not entirely sure how the FocusableView works, since every time I tried occurred an error, but thats another issue.

**Comment by doneitas** [comment]
I see. Did you try exact version 3.7.5 ?

But you don't really need react-native-snap-carousel for that example from `react-spatial-navigation` 🤔

**Comment by phillipcmittmann** [comment]
> I see. Did you try exact version 3.7.5 ?

I changed to 3.7.5 and pinpointed the problem directly from the console. `View.propTypes.style` is undefined for whatever reason. Changing to `View.propTypes?.style` resolved the issue.

> But you don't really need react-native-snap-carousel for that example from `react-spatial-navigation` 🤔

IIRC, using `map()` has a worse performance than a FlatList, and the data I will display probably will be "heavy".
