### ISSUE TITLE
kotlinVersion prop not parsed correctly

### ISSUE THREAD

**Issue by TheDuc** [pavjacko/renative#734]
**Describe the bug**
Setting kotlinVersion in renative.json currently does not work (as of version 0.32.0)

**Expected behavior**
To be able to set kotlinVersion

**Additional context**
`kotlinVersion` prop has been added to `gradleParser.js`, but is not retrieved from `renative.json`.
I believe this is due to the fact that `getConfigProp` is not called for `kotlinVersion`

**Comment by mihaiblaga89** [comment]
released in 0.32.1
