### ISSUE TITLE
androidwear The app keeps crashing

### ISSUE THREAD

**Issue by A-Mostafa-B** [pavjacko/renative#741]
**Describe the bug**
App crashes when i try to use any of those
- fetch web request 

  const SendRequest = async(strUrl){
      var objRequestConfiguration = {
          method: 'GET',
          headers: { "Accept": 'application/json', 'Content-Type': 'application/json' }
      };
      try {
       //strUrl is local network get api
          var varFetchResponse = await fetch(strUrl, objRequestConfiguration);
           var varFetchResponseJson = await varFetchResponse.json();
          alert(JSON.stringify(varFetchResponseJson))
       } catch (e) {
              alert('ErrorSendRequest ' + JSON.stringify(e))
              console.log('ErrorSendRequest ' + e);
         }
  }

![Capture](https://user-images.githubusercontent.com/54144866/142869812-d0c0c11d-d60f-4817-a668-0a1bc1e67e68.PNG)

- play sound by react-native-sound 
    var Sound = require('react-native-sound');
    Sound.setCategory('Playback');
    var whoosh = new Sound('whoosh.mp3', Sound.MAIN_BUNDLE, (error) => {
      if (error) {
        console.log('failed to load the sound', error);
        return;
      }
      // loaded successfully
      console.log('duration in seconds: ' + whoosh.getDuration() + 'number of channels: ' + whoosh.getNumberOfChannels());
    
      // Play the sound with an onEnd callback
      whoosh.play((success) => {
        if (success) {
          console.log('successfully finished playing');
        } else {
          console.log('playback failed due to audio decoding errors');
        }
      });
    });

- add event listener on keydown to handle watch's button click

     const handleUserKeyPress = useCallback(event => {
          const { key, keyCode } = event;
           alert("KeyCode=" + keyCode)
       }, []);
  
       useEffect(() => {
           window.addEventListener("keydown", handleUserKeyPress);
           return () => {
              window.removeEventListener("keydown", handleUserKeyPress);
           };
      , [handleUserKeyPress]);

**Comment by mihaiblaga89** [comment]
please follow the bug report template otherwise we have no information on what to debug

**Comment by A-Mostafa-B** [comment]
> please follow the bug report template otherwise we have no information on what to debug

i updated the issue

**Comment by mihaiblaga89** [comment]
so you're saying that any of these 3 snippets cause your android wear to crash? At first glance, I see a window on the 3rd one, you don't have a window object in RN environment. You could use `adb` to get the device logs so you'll know why the app crashed.

**Comment by A-Mostafa-B** [comment]
okay .. i will try get device logs but can you tell me how is that?
and how can i handle watch button onClick event ?

**Comment by A-Mostafa-B** [comment]
![Capture](https://user-images.githubusercontent.com/54144866/142869691-bc480fb7-3db6-4465-ab8a-1b3b9a0f7779.PNG)

**Comment by A-Mostafa-B** [comment]
I updated the issue with logs

**Comment by A-Mostafa-B** [comment]
> so you're saying that any of these 3 snippets cause your android wear to crash? At first glance, I see a window on the 3rd one, you don't have a window object in RN environment. You could use `adb` to get the device logs so you'll know why the app crashed.

I updated the issue with logs

**Comment by A-Mostafa-B** [comment]
I tried to change the version of okhttp (as someone recommend me this solution) , but the version go back after build to default 3.6.0
so how can i change it ?
![Capture1](https://user-images.githubusercontent.com/54144866/142979775-5e958bcf-4329-4d9e-a6f1-a07848858cba.PNG)

**Comment by A-Mostafa-B** [comment]
How can i see console log from bundler ?

**Comment by A-Mostafa-B** [comment]
I solved the fetch and sound issues by register the libraries in plugins renative.json

**Comment by A-Mostafa-B** [comment]
i will search how to handle watch button onClick event

Thanks

**Comment by karigarweb** [comment]
> I solved the fetch and sound issues by register the libraries in plugins renative.json

Can you please share the final solution here. I am experiencing the similar issue
