### ISSUE TITLE
How to pass params in navigation?

### ISSUE THREAD

**Issue by phillipcmittmann** [pavjacko/renative#743]
Im not sure how to do this for all platforms, since the docs don't provide a clear example. Currently I have component like this:

```
<FlatList
    horizontal={true}
    showsHorizontalScrollIndicator={false}
    data={videos}
    extraData={playlistRef}
    ref={playlistRef}
    keyExtractor={(_, index) => index.toString()}
    onViewableItemsChanged={onViewableRef.current}
    viewabilityConfig={viewabilityConfigRef.current}
    renderItem={({ item, index }) => {
        return (
            <ThumbnailVideo
                key={index.toString()}
                focusKey={`playlist-${chave}/video-${index}`}
                onBecameFocused={handleFocus}
                index={index}
                onPress={() => navigate(ROUTES.PLAYER, `/[slug]`)}
                onEnterPress={() => navigate(ROUTES.PLAYER, `/[slug]`)}
            />
        )
    }}
/>
```

I need to pass `item.id` on navigation to get the right video on the player. I tried `() => navigate(ROUTES.PLAYER, '/[slug]', { id: item.id })`, but no success. On the same note, how do I access this param on the screen that I navigated to?

The platforms that Im developing for are Tizen, WebOS, Web, tvOS and mobile.

**Comment by pavjacko** [comment]
@phillipcmittmann if you use hello-world template as a baseline, it uses `@reach/router` for web implementation (including tizentv)

so correct syntax should be:

```
navigate(ROUTES. PLAYER, '/[slug]', { state: { id: item.id } });
```

and to receive the params in player page:

```
props.location.state.id
```

note, you do not have to use `@reach/router`. you can pick any routing library and build your own navigation system

but good point. we'll add param passing (for all platforms) to the example for 0.33 release

**Comment by phillipcmittmann** [comment]
Sadly still didn't work, but I will build my own navigation system like you said. Thanks for the help.
