### ISSUE TITLE
How to use Java instead of Kotlin

### ISSUE THREAD

**Issue by MwareSolutons** [pavjacko/renative#89]
hi there, is there a way to use Java instead of Kotlin for the android platforms?

if so how do we do that ?

**Comment by pavjacko** [comment]
You can use Java on Android project out of the box. in fact most of the plugins ReNative uses are written in java. you can even replace existing classes in platformTemplate android project (after running `rnv platform eject` ) note if you do so you will need to maintain platform template (android project) yourself unless you run `rnv platform connect` to switch back to RNV default
